# Reshaping and Pivot table

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel('data\Electricity_Net_Generation__Total_(All_Sectors).xlsx',sheet_name='Monthly Data (2)')

In [3]:
df.head()

,Month,"Electricity Net Generation From Coal, All Sectors (Million Kilowatthours)","Electricity Net Generation From Petroleum, All Sectors (Million Kilowatthours)","Electricity Net Generation From Natural Gas, All Sectors","Electricity Net Generation From Other Gases, All Sectors","Electricity Net Generation From Nuclear Electric Power, All Sectors","Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors","Electricity Net Generation From Conventional Hydroelectric Power, All Sectors","Electricity Net Generation From Wood, All Sectors","Electricity Net Generation From Waste, All Sectors","Electricity Net Generation From Geothermal, All Sectors","Electricity Net Generation From Solar, All Sectors","Electricity Net Generation From Wind, All Sectors","Electricity Net Generation Total (including from sources not shown), All Sectors"
0,1973-01-01,75190.149,31183.619,21184.967,Not Available,6246.251,Not Available,26249.203,5.157,15.152,143.490,Not Available,Not Available,160217.989
1,1973-02-01,67797.946,26086.952,20252.525,Not Available,5928.069,Not Available,23313.025,15.138,13.874,131.171,Not Available,Not Available,143538.699
2,1973-03-01,67387.612,24033.245,24043.248,Not Available,6649.007,Not Available,25874.466,17.940,16.913,135.938,Not Available,Not Available,148158.370
3,1973-04-01,63935.049,20195.424,25030.266,Not Available,5876.392,Not Available,24370.510,6.323,16.771,158.705,Not Available,Not Available,139589.440
4,1973-05-01,64927.181,21741.975,29755.984,Not Available,5696.657,Not Available,25100.563,4.589,20.209,147.965,Not Available,Not Available,147395.124

In [4]:
df.iloc[0]

Month                                                                               1973-01-01 00:00:00
Electricity Net Generation From Coal, All Sectors (Million Kilowatthours)                     75190.149
Electricity Net Generation From Petroleum, All Sectors (Million Kilowatthours)                31183.619
Electricity Net Generation From Natural Gas, All Sectors                                      21184.967
Electricity Net Generation From Other Gases, All Sectors                                  Not Available
Electricity Net Generation From Nuclear Electric Power, All Sectors                            6246.251
Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors                 Not Available
Electricity Net Generation From Conventional Hydroelectric Power, All Sectors                 26249.203
Electricity Net Generation From Wood, All Sectors                                                 5.157
Electricity Net Generation From Waste, All Sectors                                               15.152
Electricity Net Generation From Geothermal, All Sectors                                          143.49
Electricity Net Generation From Solar, All Sectors                                        Not Available
Electricity Net Generation From Wind, All Sectors                                         Not Available
Electricity Net Generation Total (including from sources not shown), All Sectors             160217.989
Name: 0, dtype: object

In [5]:
df.dtypes

Month                                                                               datetime64[ns]
Electricity Net Generation From Coal, All Sectors (Million Kilowatthours)                  float64
Electricity Net Generation From Petroleum, All Sectors (Million Kilowatthours)             float64
Electricity Net Generation From Natural Gas, All Sectors                                   float64
Electricity Net Generation From Other Gases, All Sectors                                    object
Electricity Net Generation From Nuclear Electric Power, All Sectors                        float64
Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors                   object
Electricity Net Generation From Conventional Hydroelectric Power, All Sectors              float64
Electricity Net Generation From Wood, All Sectors                                          float64
Electricity Net Generation From Waste, All Sectors                                         float64
Electricity Net Generation From Geothermal, All Sectors                                    float64
Electricity Net Generation From Solar, All Sectors                                          object
Electricity Net Generation From Wind, All Sectors                                           object
Electricity Net Generation Total (including from sources not shown), All Sectors           float64
dtype: object

In [6]:
df

,Month,"Electricity Net Generation From Coal, All Sectors (Million Kilowatthours)","Electricity Net Generation From Petroleum, All Sectors (Million Kilowatthours)","Electricity Net Generation From Natural Gas, All Sectors","Electricity Net Generation From Other Gases, All Sectors","Electricity Net Generation From Nuclear Electric Power, All Sectors","Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors","Electricity Net Generation From Conventional Hydroelectric Power, All Sectors","Electricity Net Generation From Wood, All Sectors","Electricity Net Generation From Waste, All Sectors","Electricity Net Generation From Geothermal, All Sectors","Electricity Net Generation From Solar, All Sectors","Electricity Net Generation From Wind, All Sectors","Electricity Net Generation Total (including from sources not shown), All Sectors"
0,1973-01-01,75190.149,31183.619,21184.967,Not Available,6246.251,Not Available,26249.203,5.157,15.152,143.490,Not Available,Not Available,160217.989
1,1973-02-01,67797.946,26086.952,20252.525,Not Available,5928.069,Not Available,23313.025,15.138,13.874,131.171,Not Available,Not Available,143538.699
2,1973-03-01,67387.612,24033.245,24043.248,Not Available,6649.007,Not Available,25874.466,17.940,16.913,135.938,Not Available,Not Available,148158.370
3,1973-04-01,63935.049,20195.424,25030.266,Not Available,5876.392,Not Available,24370.510,6.323,16.771,158.705,Not Available,Not Available,139589.440
4,1973-05-01,64927.181,21741.975,29755.984,Not Available,5696.657,Not Available,25100.563,4.589,20.209,147.965,Not Available,Not Available,147395.124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,2021-12-01,59878.052,1476.845,127168.673,889.284,70719.837,-445.116,25649.675,3188.972,1597.551,1454.154,6354.878,40675.582,339684.017
588,2022-01-01,87505.587,3784.942,136317.103,971.401,70576.875,-493.31,27016.979,3084.085,1488.615,1499.622,8003.896,38193.633,378966.702
589,2022-02-01,70761.756,1604.619,115615.259,832.322,61861.903,-412.258,23669.921,2991.538,1336.161,1250.063,9202.56,38162.282,327766.846
590,2022-03-01,60767.670,1422.594,112002.542,894.172,63153.701,-317.508,26139.444,3020.778,1449.529,1326.450,11890.566,43230.383,325952.002
591,2022-04-01,55056.190,1237.486,105934.050,903.778,55289.540,-265.226,20194.347,2733.715,1364.032,1276.166,13484.08,46217.243,304348.709

In [7]:
df_columns = df.columns

In [8]:
df_columns

Index(['Month',
       'Electricity Net Generation From Coal, All Sectors (Million Kilowatthours)',
       'Electricity Net Generation From Petroleum, All Sectors (Million Kilowatthours)',
       'Electricity Net Generation From Natural Gas, All Sectors',
       'Electricity Net Generation From Other Gases, All Sectors',
       'Electricity Net Generation From Nuclear Electric Power, All Sectors',
       'Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors',
       'Electricity Net Generation From Conventional Hydroelectric Power, All Sectors',
       'Electricity Net Generation From Wood, All Sectors',
       'Electricity Net Generation From Waste, All Sectors',
       'Electricity Net Generation From Geothermal, All Sectors',
       'Electricity Net Generation From Solar, All Sectors',
       'Electricity Net Generation From Wind, All Sectors',
       'Electricity Net Generation Total (including from sources not shown), All Sectors'],
      dtype='object')

In [21]:
# list(df.index)

In [10]:
df['Month']

0     1973-01-01
1     1973-02-01
2     1973-03-01
3     1973-04-01
4     1973-05-01
         ...
587   2021-12-01
588   2022-01-01
589   2022-02-01
590   2022-03-01
591   2022-04-01
Name: Month, Length: 592, dtype: datetime64[ns]

### 1.Reshaping by pivoting DataFrame objects

In [11]:
df1=df

In [12]:
df1.columns = 'Month Coal Petroleum Natural_gas Other_gases Nuclear_Electirc_Power Hydroelectric_Pumped_Storage Conventional_Hydroelectric_Power Wood Waste Geothermal Solar Wind Total'.split()

In [13]:
df1

,Month,Coal,Petroleum,Natural_gas,Other_gases,Nuclear_Electirc_Power,Hydroelectric_Pumped_Storage,Conventional_Hydroelectric_Power,Wood,Waste,Geothermal,Solar,Wind,Total
0,1973-01-01,75190.149,31183.619,21184.967,Not Available,6246.251,Not Available,26249.203,5.157,15.152,143.490,Not Available,Not Available,160217.989
1,1973-02-01,67797.946,26086.952,20252.525,Not Available,5928.069,Not Available,23313.025,15.138,13.874,131.171,Not Available,Not Available,143538.699
2,1973-03-01,67387.612,24033.245,24043.248,Not Available,6649.007,Not Available,25874.466,17.940,16.913,135.938,Not Available,Not Available,148158.370
3,1973-04-01,63935.049,20195.424,25030.266,Not Available,5876.392,Not Available,24370.510,6.323,16.771,158.705,Not Available,Not Available,139589.440
4,1973-05-01,64927.181,21741.975,29755.984,Not Available,5696.657,Not Available,25100.563,4.589,20.209,147.965,Not Available,Not Available,147395.124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,2021-12-01,59878.052,1476.845,127168.673,889.284,70719.837,-445.116,25649.675,3188.972,1597.551,1454.154,6354.878,40675.582,339684.017
588,2022-01-01,87505.587,3784.942,136317.103,971.401,70576.875,-493.31,27016.979,3084.085,1488.615,1499.622,8003.896,38193.633,378966.702
589,2022-02-01,70761.756,1604.619,115615.259,832.322,61861.903,-412.258,23669.921,2991.538,1336.161,1250.063,9202.56,38162.282,327766.846
590,2022-03-01,60767.670,1422.594,112002.542,894.172,63153.701,-317.508,26139.444,3020.778,1449.529,1326.450,11890.566,43230.383,325952.002
591,2022-04-01,55056.190,1237.486,105934.050,903.778,55289.540,-265.226,20194.347,2733.715,1364.032,1276.166,13484.08,46217.243,304348.709

In [14]:
# df

In [15]:
df1['Total'].isnull().sum()

0

In [16]:
Tot_mean = df1['Total'].mean()

In [17]:
df1['month'] = pd.DatetimeIndex(df1['Month']).month
df1['year'] = pd.DatetimeIndex(df1['Month']).year

In [18]:
df1 = df1.drop('Month Coal Petroleum Natural_gas Other_gases Nuclear_Electirc_Power Hydroelectric_Pumped_Storage Conventional_Hydroelectric_Power Wood Waste Geothermal Solar Wind'.split(),axis=1)
df1

          Total  month  year
0    160217.989      1  1973
1    143538.699      2  1973
2    148158.370      3  1973
3    139589.440      4  1973
4    147395.124      5  1973
..          ...    ...   ...
587  339684.017     12  2021
588  378966.702      1  2022
589  327766.846      2  2022
590  325952.002      3  2022
591  304348.709      4  2022

[592 rows x 3 columns]

In [19]:
df1[df1["month"] == 1]  # to check the total of each year 1st month

          Total  month  year
0    160217.989      1  1973
12   157554.691      1  1974
24   164623.080      1  1975
36   178608.612      1  1976
48   196665.182      1  1977
60   198107.635      1  1978
72   209986.749      1  1979
84   200296.330      1  1980
96   206758.205      1  1981
108  209694.373      1  1982
120  195870.844      1  1983
132  216923.729      1  1984
144  228147.888      1  1985
156  217761.136      1  1986
168  223040.975      1  1987
180  238188.434      1  1988
192  246766.176      1  1989
204  255187.021      1  1990
216  269214.313      1  1991
228  267772.670      1  1992
240  271020.902      1  1993
252  289768.406      1  1994
264  279773.101      1  1995
276  296922.971      1  1996
288  300573.901      1  1997
300  295260.404      1  1998
312  315813.690      1  1999
324  327993.944      1  2000
336  332493.160      1  2001
348  319941.472      1  2002
360  341988.899      1  2003
372  346545.627      1  2004
384  343121.453      1  2005
396  328657.739      1  2006
408  353531.095      1  2007
420  362998.429      1  2008
432  354992.636      1  2009
444  360957.167      1  2010
456  362871.893      1  2011
468  339528.259      1  2012
480  348967.378      1  2013
492  377254.711      1  2014
504  360455.167      1  2015
516  352719.066      1  2016
528  344332.034      1  2017
540  373230.280      1  2018
552  359509.234      1  2019
564  341850.206      1  2020
576  350795.813      1  2021
588  378966.702      1  2022

In [20]:
df1.pivot(index='year',columns='month',values='Total')

month,1,2,3,4,5,6,7,8,9,10,11,12
year,,,,,,,,,,,,
1973,160217.989,143538.699,148158.370,139589.440,147395.124,161243.674,173733.007,177365.364,156875.032,154197.466,148137.609,153604.858
1974,157554.691,142748.458,150342.206,142311.633,153812.873,156440.089,178247.304,174119.001,152467.442,152195.832,150070.855,160009.019
1975,164623.080,147349.000,155760.211,146494.879,153531.080,162716.960,177056.505,179930.892,155440.826,155187.742,153035.097,169628.296
1976,178608.612,156965.799,164466.676,153467.392,157664.467,173673.719,186691.040,186638.696,165237.437,164009.445,169346.291,184144.107
1977,196665.182,162949.088,169437.171,157117.355,169596.403,181031.212,199167.726,196363.166,176497.560,166645.282,167388.072,184589.270
1978,198107.635,173745.731,173460.887,160012.982,175548.628,188585.386,202947.293,206658.749,185802.058,176013.116,176389.093,192105.353
1979,209986.749,186587.309,183154.004,170260.472,178409.356,186976.379,202522.477,205100.592,180974.646,179953.363,177769.508,188970.171
1980,200296.330,188961.379,187744.800,169016.585,176066.486,189748.486,217057.853,215629.382,191697.740,178761.034,178771.361,195848.927
1981,206758.205,179859.910,185833.882,172841.342,178138.553,203020.751,220654.747,210639.415,187051.489,181557.590,175791.753,195825.699
1982,209694.373,180545.573,187967.965,172876.502,177479.981,186447.119,210865.079,205891.676,180875.268,173172.248,173598.759,184957.943
1983,195870.844,172725.190,182768.722,170668.876,174724.813,191367.206,220446.836,230193.460,195817.014,183136.711,183170.681,212555.333
1984,216923.729,189810.043,200387.475,181381.139,192550.198,209967.314,221526.162,229531.666,195411.388,191142.430,190601.865,200231.958
1985,228147.888,198488.497,195250.388,185173.312,197122.843,205681.971,227003.762,226286.447,202712.422,194995.217,192648.952,219490.423
1986,217761.136,192582.016,197114.555,186370.454,197647.498,215334.156,242953.552,225402.481,206905.101,197959.776,196653.686,213786.542
1987,223040.975,194280.625,202129.944,189792.417,206406.878,225907.915,248196.221,247880.760,213221.249,203214.924,200479.386,220736.372
1988,238188.434,217183.084,214293.615,196297.111,208703.604,233065.853,257742.125,267928.593,220392.242,210813.885,209814.992,232987.639
1989,246766.176,233782.777,241946.410,222868.586,234824.770,250919.110,273457.735,275419.519,242793.798,235669.018,234249.810,274448.378
1990,255187.021,229499.204,244761.483,229769.727,241773.529,268992.258,287447.762,290655.259,258356.632,244372.250,231242.377,255769.835
1991,269214.313,228290.131,240561.216,227798.971,254873.018,269099.254,294647.834,292158.580,256027.328,245378.242,241661.365,254088.633
1992,267772.670,239514.031,247733.163,233405.563,242411.928,261076.926,293616.745,281927.430,259925.035,244993.925,244161.999,267342.791
1993,271020.902,248015.328,261247.551,234695.127,244325.583,275359.600,312224.835,311450.190,264032.481,250552.792,252102.138,272164.570
1994,289768.406,249172.290,257998.052,240636.581,252744.936,294161.782,311256.823,307604.584,266262.327,256528.490,251868.348,269519.769
1995,279773.101,252307.149,261342.562,244735.923,264288.242,286258.135,330416.095,345780.079,277575.357,263978.440,261478.399,285553.882
1996,296922.971,270685.247,275019.018,251612.875,282266.414,302716.899,327708.462,329286.330,283151.263,271446.494,269122.035,284249.613
1997,300573.901,258131.029,272258.227,258284.482,272913.783,299091.561,344516.455,332898.630,301056.672,284970.629,271120.816,296356.097
1998,295260.404,260589.918,286877.989,261229.604,299639.908,328903.002,361936.460,357365.610,318924.466,284445.547,267136.408,297986.181
1999,315813.690,274820.273,298144.718,280719.013,300098.190,328923.833,376538.308,364031.383,305515.654,283934.839,271095.672,295174.237
2000,327993.944,294169.282,301579.821,285577.749,322953.681,339053.660,356527.917,368669.365,312446.647,289451.903,284670.275,319010.798
2001,332493.160,282940.198,300706.544,278078.871,300491.621,327693.978,357613.700,370532.828,306928.866,294733.613,278933.942,305496.328
2002,319941.472,281825.708,302549.007,289848.252,307674.569,341023.145,381542.109,374585.823,331279.434,307059.462,296289.561,324833.704
2003,341988.899,299248.775,304317.263,285755.700,307544.887,328693.699,374396.049,381816.318,323135.536,306740.934,297866.713,331680.431
2004,346545.627,314279.910,308812.096,290559.914,327380.264,345085.079,377331.697,368439.037,335622.198,312450.223,302101.256,341947.963
2005,343121.453,298500.316,317458.276,289562.400,315062.110,363671.636,402273.846,404940.681,350217.801,316397.924,306115.236,348101.071
2006,328657.739,307333.430,318729.800,297858.078,330615.570,364259.798,410420.793,407762.536,332055.321,321567.091,309158.826,336283.246
2007,353531.095,323230.395,320471.243,303129.064,330202.758,362754.877,393226.432,421796.659,355393.912,332615.416,314102.543,346290.331
2008,362998.429,325105.597,324629.850,305865.031,325244.802,373109.027,402900.336,388986.719,338056.130,318547.343,310046.241,343898.254
2009,354992.636,300887.398,310602.964,289537.255,311305.872,347658.241,372542.226,381221.417,327400.612,307040.341,296634.670,350507.295
2010,360957.167,319734.727,312167.640,287800.227,327936.492,375759.478,409725.440,408884.155,346045.172,307920.691,306009.629,362119.081
2011,362871.893,313126.607,318709.941,302400.724,323628.238,367727.015,418692.755,406511.315,337931.318,308698.504,304102.155,335740.463
2012,339528.259,309389.420,309090.569,295228.216,336517.631,360826.151,414639.671,395699.566,334584.877,311650.774,305975.035,334635.089
2013,348967.378,309728.080,325398.834,299332.868,322155.640,356822.647,394845.621,385285.745,340940.902,314925.463,314539.642,353021.248
2014,377254.711,324348.436,331823.059,297630.588,324724.300,357844.043,385779.552,384341.148,339886.506,314521.999,317495.009,337956.656
2015,360455.167,334475.546,324191.894,294133.343,322086.912,362409.202,400418.853,392116.203,350121.648,312111.680,300653.268,324427.224
2016,352719.066,313685.401,304389.581,292893.550,316784.457,367781.196,411886.942,409700.812,351484.468,312945.164,297061.772,345342.577
2017,344332.034,291049.672,319335.755,295360.591,323446.738,358522.007,404432.474,384738.580,335914.910,318669.649,308052.342,350415.808
2018,373230.280,306894.214,321546.954,300756.440,338947.606,371885.761,411290.320,408027.757,356258.302,324931.943,322368.657,342139.112
2019,359509.234,315026.484,326657.208,296662.569,330423.048,352988.074,410037.810,401429.694,360518.468,320351.885,315849.092,338401.647
2020,341850.206,319550.114,309586.723,279583.265,304593.238,351744.930,409561.700,398279.697,333258.048,313531.271,301250.181,344346.095
2021,350795.813,326223.389,312284.622,292503.539,318858.513,373754.405,404748.717,413353.176,348200.651,319638.396,315494.917,339684.017
2022,378966.702,327766.846,325952.002,304348.709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df1.pivot(index='month',columns='year',values='Total')

year,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
month,,,,,,,,,,,,,,,,,,,,,
1,160217.989,157554.691,164623.080,178608.612,196665.182,198107.635,209986.749,200296.330,206758.205,209694.373,...,348967.378,377254.711,360455.167,352719.066,344332.034,373230.280,359509.234,341850.206,350795.813,378966.702
2,143538.699,142748.458,147349.000,156965.799,162949.088,173745.731,186587.309,188961.379,179859.910,180545.573,...,309728.080,324348.436,334475.546,313685.401,291049.672,306894.214,315026.484,319550.114,326223.389,327766.846
3,148158.370,150342.206,155760.211,164466.676,169437.171,173460.887,183154.004,187744.800,185833.882,187967.965,...,325398.834,331823.059,324191.894,304389.581,319335.755,321546.954,326657.208,309586.723,312284.622,325952.002
4,139589.440,142311.633,146494.879,153467.392,157117.355,160012.982,170260.472,169016.585,172841.342,172876.502,...,299332.868,297630.588,294133.343,292893.550,295360.591,300756.440,296662.569,279583.265,292503.539,304348.709
5,147395.124,153812.873,153531.080,157664.467,169596.403,175548.628,178409.356,176066.486,178138.553,177479.981,...,322155.640,324724.300,322086.912,316784.457,323446.738,338947.606,330423.048,304593.238,318858.513,NaN
6,161243.674,156440.089,162716.960,173673.719,181031.212,188585.386,186976.379,189748.486,203020.751,186447.119,...,356822.647,357844.043,362409.202,367781.196,358522.007,371885.761,352988.074,351744.930,373754.405,NaN
7,173733.007,178247.304,177056.505,186691.040,199167.726,202947.293,202522.477,217057.853,220654.747,210865.079,...,394845.621,385779.552,400418.853,411886.942,404432.474,411290.320,410037.810,409561.700,404748.717,NaN
8,177365.364,174119.001,179930.892,186638.696,196363.166,206658.749,205100.592,215629.382,210639.415,205891.676,...,385285.745,384341.148,392116.203,409700.812,384738.580,408027.757,401429.694,398279.697,413353.176,NaN
9,156875.032,152467.442,155440.826,165237.437,176497.560,185802.058,180974.646,191697.740,187051.489,180875.268,...,340940.902,339886.506,350121.648,351484.468,335914.910,356258.302,360518.468,333258.048,348200.651,NaN
10,154197.466,152195.832,155187.742,164009.445,166645.282,176013.116,179953.363,178761.034,181557.590,173172.248,...,314925.463,314521.999,312111.680,312945.164,318669.649,324931.943,320351.885,313531.271,319638.396,NaN
11,148137.609,150070.855,153035.097,169346.291,167388.072,176389.093,177769.508,178771.361,175791.753,173598.759,...,314539.642,317495.009,300653.268,297061.772,308052.342,322368.657,315849.092,301250.181,315494.917,NaN
12,153604.858,160009.019,169628.296,184144.107,184589.270,192105.353,188970.171,195848.927,195825.699,184957.943,...,353021.248,337956.656,324427.224,345342.577,350415.808,342139.112,338401.647,344346.095,339684.017,NaN

In [19]:
df1

          Total  month  year
0    160217.989      1  1973
1    143538.699      2  1973
2    148158.370      3  1973
3    139589.440      4  1973
4    147395.124      5  1973
..          ...    ...   ...
587  339684.017     12  2021
588  378966.702      1  2022
589  327766.846      2  2022
590  325952.002      3  2022
591  304348.709      4  2022

[592 rows x 3 columns]

In [20]:
df1['tot/mean_tot'] = df1['Total']/Tot_mean

In [21]:
df1

          Total  month  year  tot/mean_tot
0    160217.989      1  1973      0.584437
1    143538.699      2  1973      0.523595
2    148158.370      3  1973      0.540446
3    139589.440      4  1973      0.509189
4    147395.124      5  1973      0.537662
..          ...    ...   ...           ...
587  339684.017     12  2021      1.239086
588  378966.702      1  2022      1.382380
589  327766.846      2  2022      1.195615
590  325952.002      3  2022      1.188995
591  304348.709      4  2022      1.110191

[592 rows x 4 columns]

###### If the values argument is omitted, and the input DataFrame has more than one column of values which are not used as column or index inputs to pivot(), then the resulting “pivoted” DataFrame will have hierarchical columns whose topmost level indicates the respective value column:

In [22]:
pivot2= df1.pivot(index='year',columns='month')
pivot2

            Total                                                              \
month          1           2           3           4           5           6
year
1973   160217.989  143538.699  148158.370  139589.440  147395.124  161243.674
1974   157554.691  142748.458  150342.206  142311.633  153812.873  156440.089
1975   164623.080  147349.000  155760.211  146494.879  153531.080  162716.960
1976   178608.612  156965.799  164466.676  153467.392  157664.467  173673.719
1977   196665.182  162949.088  169437.171  157117.355  169596.403  181031.212
1978   198107.635  173745.731  173460.887  160012.982  175548.628  188585.386
1979   209986.749  186587.309  183154.004  170260.472  178409.356  186976.379
1980   200296.330  188961.379  187744.800  169016.585  176066.486  189748.486
1981   206758.205  179859.910  185833.882  172841.342  178138.553  203020.751
1982   209694.373  180545.573  187967.965  172876.502  177479.981  186447.119
1983   195870.844  172725.190  182768.722  170668.876  174724.813  191367.206
1984   216923.729  189810.043  200387.475  181381.139  192550.198  209967.314
1985   228147.888  198488.497  195250.388  185173.312  197122.843  205681.971
1986   217761.136  192582.016  197114.555  186370.454  197647.498  215334.156
1987   223040.975  194280.625  202129.944  189792.417  206406.878  225907.915
1988   238188.434  217183.084  214293.615  196297.111  208703.604  233065.853
1989   246766.176  233782.777  241946.410  222868.586  234824.770  250919.110
1990   255187.021  229499.204  244761.483  229769.727  241773.529  268992.258
1991   269214.313  228290.131  240561.216  227798.971  254873.018  269099.254
1992   267772.670  239514.031  247733.163  233405.563  242411.928  261076.926
1993   271020.902  248015.328  261247.551  234695.127  244325.583  275359.600
1994   289768.406  249172.290  257998.052  240636.581  252744.936  294161.782
1995   279773.101  252307.149  261342.562  244735.923  264288.242  286258.135
1996   296922.971  270685.247  275019.018  251612.875  282266.414  302716.899
1997   300573.901  258131.029  272258.227  258284.482  272913.783  299091.561
1998   295260.404  260589.918  286877.989  261229.604  299639.908  328903.002
1999   315813.690  274820.273  298144.718  280719.013  300098.190  328923.833
2000   327993.944  294169.282  301579.821  285577.749  322953.681  339053.660
2001   332493.160  282940.198  300706.544  278078.871  300491.621  327693.978
2002   319941.472  281825.708  302549.007  289848.252  307674.569  341023.145
2003   341988.899  299248.775  304317.263  285755.700  307544.887  328693.699
2004   346545.627  314279.910  308812.096  290559.914  327380.264  345085.079
2005   343121.453  298500.316  317458.276  289562.400  315062.110  363671.636
2006   328657.739  307333.430  318729.800  297858.078  330615.570  364259.798
2007   353531.095  323230.395  320471.243  303129.064  330202.758  362754.877
2008   362998.429  325105.597  324629.850  305865.031  325244.802  373109.027
2009   354992.636  300887.398  310602.964  289537.255  311305.872  347658.241
2010   360957.167  319734.727  312167.640  287800.227  327936.492  375759.478
2011   362871.893  313126.607  318709.941  302400.724  323628.238  367727.015
2012   339528.259  309389.420  309090.569  295228.216  336517.631  360826.151
2013   348967.378  309728.080  325398.834  299332.868  322155.640  356822.647
2014   377254.711  324348.436  331823.059  297630.588  324724.300  357844.043
2015   360455.167  334475.546  324191.894  294133.343  322086.912  362409.202
2016   352719.066  313685.401  304389.581  292893.550  316784.457  367781.196
2017   344332.034  291049.672  319335.755  295360.591  323446.738  358522.007
2018   373230.280  306894.214  321546.954  300756.440  338947.606  371885.761
2019   359509.234  315026.484  326657.208  296662.569  330423.048  352988.074
2020   341850.206  319550.114  309586.723  279583.265  304593.238  351744.930
2021   350795.813  326223.389  312284.622  292503.539  318858.513  373754.405
2022   378966.702  327766.846  325952.002  304348.709         NaN         NaN

                                                       ... tot/mean_tot  \
month          7           8           9           10  ...           3
year                                                   ...
1973   173733.007  177365.364  156875.032  154197.466  ...     0.540446
1974   178247.304  174119.001  152467.442  152195.832  ...     0.548412
1975   177056.505  179930.892  155440.826  155187.742  ...     0.568176
1976   186691.040  186638.696  165237.437  164009.445  ...     0.599935
1977   199167.726  196363.166  176497.560  166645.282  ...     0.618066
1978   202947.293  206658.749  185802.058  176013.116  ...     0.632744
1979   202522.477  205100.592  180974.646  179953.363  ...     0.668102
1980   217057.853  215629.382  191697.740  178761.034  ...     0.684848
1981   220654.747  210639.415  187051.489  181557.590  ...     0.677878
1982   210865.079  205891.676  180875.268  173172.248  ...     0.685662
1983   220446.836  230193.460  195817.014  183136.711  ...     0.666697
1984   221526.162  229531.666  195411.388  191142.430  ...     0.730966
1985   227003.762  226286.447  202712.422  194995.217  ...     0.712227
1986   242953.552  225402.481  206905.101  197959.776  ...     0.719027
1987   248196.221  247880.760  213221.249  203214.924  ...     0.737322
1988   257742.125  267928.593  220392.242  210813.885  ...     0.781692
1989   273457.735  275419.519  242793.798  235669.018  ...     0.882563
1990   287447.762  290655.259  258356.632  244372.250  ...     0.892831
1991   294647.834  292158.580  256027.328  245378.242  ...     0.877510
1992   293616.745  281927.430  259925.035  244993.925  ...     0.903671
1993   312224.835  311450.190  264032.481  250552.792  ...     0.952969
1994   311256.823  307604.584  266262.327  256528.490  ...     0.941115
1995   330416.095  345780.079  277575.357  263978.440  ...     0.953315
1996   327708.462  329286.330  283151.263  271446.494  ...     1.003204
1997   344516.455  332898.630  301056.672  284970.629  ...     0.993133
1998   361936.460  357365.610  318924.466  284445.547  ...     1.046462
1999   376538.308  364031.383  305515.654  283934.839  ...     1.087561
2000   356527.917  368669.365  312446.647  289451.903  ...     1.100091
2001   357613.700  370532.828  306928.866  294733.613  ...     1.096906
2002   381542.109  374585.823  331279.434  307059.462  ...     1.103626
2003   374396.049  381816.318  323135.536  306740.934  ...     1.110077
2004   377331.697  368439.037  335622.198  312450.223  ...     1.126473
2005   402273.846  404940.681  350217.801  316397.924  ...     1.158012
2006   410420.793  407762.536  332055.321  321567.091  ...     1.162650
2007   393226.432  421796.659  355393.912  332615.416  ...     1.169002
2008   402900.336  388986.719  338056.130  318547.343  ...     1.184172
2009   372542.226  381221.417  327400.612  307040.341  ...     1.133005
2010   409725.440  408884.155  346045.172  307920.691  ...     1.138713
2011   418692.755  406511.315  337931.318  308698.504  ...     1.162578
2012   414639.671  395699.566  334584.877  311650.774  ...     1.127488
2013   394845.621  385285.745  340940.902  314925.463  ...     1.186977
2014   385779.552  384341.148  339886.506  314521.999  ...     1.210411
2015   400418.853  392116.203  350121.648  312111.680  ...     1.182575
2016   411886.942  409700.812  351484.468  312945.164  ...     1.110340
2017   404432.474  384738.580  335914.910  318669.649  ...     1.164860
2018   411290.320  408027.757  356258.302  324931.943  ...     1.172926
2019   410037.810  401429.694  360518.468  320351.885  ...     1.191567
2020   409561.700  398279.697  333258.048  313531.271  ...     1.129298
2021   404748.717  413353.176  348200.651  319638.396  ...     1.139140
2022          NaN         NaN         NaN         NaN  ...     1.188995

                                                                             \
month        4         5         6         7         8         9         10
year
1973   0.509189  0.537662  0.588178  0.633736  0.646986  0.572243  0.562475
1974   0.519119  0.561073  0.570656  0.650204  0.635144  0.556165  0.555174
1975   0.534378  0.560045  0.593553  0.645860  0.656345  0.567011  0.566088
1976   0.559812  0.575122  0.633520  0.681004  0.680813  0.602747  0.598267
1977   0.573127  0.618647  0.660359  0.726516  0.716286  0.643821  0.607882
1978   0.583689  0.640359  0.687914  0.740303  0.753842  0.677761  0.642054
1979   0.621069  0.650795  0.682045  0.738754  0.748158  0.660152  0.656427
1980   0.616532  0.642248  0.692157  0.791775  0.786564  0.699268  0.652078
1981   0.630484  0.649807  0.740571  0.804896  0.768362  0.682319  0.662279
1982   0.630612  0.647405  0.680115  0.769185  0.751044  0.659790  0.631691
1983   0.622559  0.637354  0.698062  0.804137  0.839691  0.714294  0.668039
1984   0.661635  0.702377  0.765911  0.808074  0.837277  0.712814  0.697242
1985   0.675468  0.719057  0.750279  0.828055  0.825439  0.739446  0.711296
1986   0.679835  0.720971  0.785488  0.886236  0.822214  0.754740  0.722110
1987   0.692317  0.752923  0.824058  0.905360  0.904210  0.777780  0.741279
1988   0.716045  0.761301  0.850169  0.940182  0.977339  0.803938  0.768999
1989   0.812971  0.856585  0.915293  0.997508  1.004665  0.885654  0.859664
1990   0.838145  0.881932  0.981219  1.048541  1.060241  0.942423  0.891412
1991   0.830956  0.929716  0.981610  1.074805  1.065725  0.933926  0.895081
1992   0.851408  0.884261  0.952346  1.071044  1.028404  0.948144  0.893679
1993   0.856112  0.891241  1.004446  1.138922  1.136096  0.963127  0.913957
1994   0.877785  0.921953  1.073032  1.135390  1.122068  0.971261  0.935755
1995   0.892738  0.964060  1.044201  1.205279  1.261323  1.012529  0.962930
1996   0.917824  1.029640  1.104239  1.195402  1.201158  1.032868  0.990172
1997   0.942160  0.995524  1.091015  1.256714  1.214335  1.098183  1.039505
1998   0.952903  1.093015  1.199760  1.320258  1.303584  1.163360  1.037589
1999   1.023996  1.094686  1.199836  1.373522  1.327899  1.114448  1.035726
2000   1.041719  1.178058  1.236787  1.300529  1.344818  1.139731  1.055851
2001   1.014365  1.096122  1.195349  1.304489  1.351615  1.119603  1.075118
2002   1.057297  1.122323  1.243971  1.391774  1.366400  1.208428  1.120080
2003   1.042368  1.121850  1.198996  1.365707  1.392775  1.178721  1.118918
2004   1.059893  1.194205  1.258788  1.376416  1.343978  1.224270  1.139744
2005   1.056254  1.149271  1.326587  1.467399  1.477127  1.277511  1.154144
2006   1.086515  1.206007  1.328733  1.497117  1.487420  1.211258  1.173000
2007   1.105742  1.204501  1.323243  1.434396  1.538613  1.296392  1.213302
2008   1.115723  1.186415  1.361013  1.469684  1.418931  1.233148  1.161985
2009   1.056163  1.135569  1.268174  1.358945  1.390605  1.194279  1.120010
2010   1.049826  1.196234  1.370681  1.494580  1.491512  1.262290  1.123221
2011   1.103086  1.180518  1.341380  1.527291  1.482856  1.232693  1.126058
2012   1.076922  1.227536  1.316208  1.512506  1.443417  1.220486  1.136828
2013   1.091895  1.175147  1.301604  1.440302  1.405430  1.243671  1.148773
2014   1.085685  1.184517  1.305330  1.407232  1.401985  1.239825  1.147301
2015   1.072928  1.174896  1.321982  1.460632  1.430346  1.277160  1.138509
2016   1.068406  1.155554  1.341578  1.502465  1.494491  1.282131  1.141549
2017   1.077405  1.179856  1.307803  1.475273  1.403434  1.225337  1.162431
2018   1.097088  1.236400  1.356550  1.500289  1.488388  1.299545  1.185274
2019   1.082154  1.205304  1.287616  1.495720  1.464320  1.315085  1.168567
2020   1.019853  1.111083  1.283081  1.493983  1.452829  1.215646  1.143687
2021   1.066983  1.163120  1.363367  1.476427  1.507814  1.270153  1.165964
2022   1.110191       NaN       NaN       NaN       NaN       NaN       NaN


month        11        12
year
1973   0.540371  0.560314
1974   0.547423  0.583675
1975   0.558235  0.618763
1976   0.617735  0.671714
1977   0.610592  0.673338
1978   0.643425  0.700754
1979   0.648461  0.689318
1980   0.652115  0.714410
1981   0.641246  0.714325
1982   0.633247  0.674682
1983   0.668163  0.775351
1984   0.695270  0.730398
1985   0.702737  0.800649
1986   0.717346  0.779842
1987   0.731301  0.805194
1988   0.765355  0.849883
1989   0.854487  1.001122
1990   0.843517  0.932987
1991   0.881523  0.926855
1992   0.890645  0.975203
1993   0.919608  0.992791
1994   0.918756  0.983144
1995   0.953811  1.041632
1996   0.981693  1.036875
1997   0.988984  1.081036
1998   0.974450  1.086982
1999   0.988892  1.076725
2000   1.038409  1.163675
2001   1.017484  1.114378
2002   1.080793  1.184916
2003   1.086547  1.209891
2004   1.101993  1.247344
2005   1.116635  1.269789
2006   1.127737  1.226681
2007   1.145771  1.263184
2008   1.130975  1.254459
2009   1.082052  1.278567
2010   1.116250  1.320924
2011   1.109292  1.224701
2012   1.116124  1.220669
2013   1.147365  1.287737
2014   1.158146  1.232785
2015   1.096711  1.183433
2016   1.083610  1.259727
2017   1.123701  1.278233
2018   1.175924  1.248042
2019   1.152142  1.234408
2020   1.098889  1.256092
2021   1.150850  1.239086
2022        NaN       NaN

[50 rows x 24 columns]

In [23]:
pivot2['tot/mean_tot']   #we can select subsets from the pivoted dataframe

month,1,2,3,4,5,6,7,8,9,10,11,12
year,,,,,,,,,,,,
1973,0.584437,0.523595,0.540446,0.509189,0.537662,0.588178,0.633736,0.646986,0.572243,0.562475,0.540371,0.560314
1974,0.574722,0.520712,0.548412,0.519119,0.561073,0.570656,0.650204,0.635144,0.556165,0.555174,0.547423,0.583675
1975,0.600506,0.537494,0.568176,0.534378,0.560045,0.593553,0.645860,0.656345,0.567011,0.566088,0.558235,0.618763
1976,0.651522,0.572574,0.599935,0.559812,0.575122,0.633520,0.681004,0.680813,0.602747,0.598267,0.617735,0.671714
1977,0.717388,0.594399,0.618066,0.573127,0.618647,0.660359,0.726516,0.716286,0.643821,0.607882,0.610592,0.673338
1978,0.722649,0.633783,0.632744,0.583689,0.640359,0.687914,0.740303,0.753842,0.677761,0.642054,0.643425,0.700754
1979,0.765981,0.680626,0.668102,0.621069,0.650795,0.682045,0.738754,0.748158,0.660152,0.656427,0.648461,0.689318
1980,0.730633,0.689286,0.684848,0.616532,0.642248,0.692157,0.791775,0.786564,0.699268,0.652078,0.652115,0.714410
1981,0.754204,0.656086,0.677878,0.630484,0.649807,0.740571,0.804896,0.768362,0.682319,0.662279,0.641246,0.714325
1982,0.764915,0.658587,0.685662,0.630612,0.647405,0.680115,0.769185,0.751044,0.659790,0.631691,0.633247,0.674682
1983,0.714490,0.630060,0.666697,0.622559,0.637354,0.698062,0.804137,0.839691,0.714294,0.668039,0.668163,0.775351
1984,0.791286,0.692382,0.730966,0.661635,0.702377,0.765911,0.808074,0.837277,0.712814,0.697242,0.695270,0.730398
1985,0.832229,0.724039,0.712227,0.675468,0.719057,0.750279,0.828055,0.825439,0.739446,0.711296,0.702737,0.800649
1986,0.794341,0.702493,0.719027,0.679835,0.720971,0.785488,0.886236,0.822214,0.754740,0.722110,0.717346,0.779842
1987,0.813600,0.708689,0.737322,0.692317,0.752923,0.824058,0.905360,0.904210,0.777780,0.741279,0.731301,0.805194
1988,0.868854,0.792232,0.781692,0.716045,0.761301,0.850169,0.940182,0.977339,0.803938,0.768999,0.765355,0.849883
1989,0.900144,0.852784,0.882563,0.812971,0.856585,0.915293,0.997508,1.004665,0.885654,0.859664,0.854487,1.001122
1990,0.930861,0.837158,0.892831,0.838145,0.881932,0.981219,1.048541,1.060241,0.942423,0.891412,0.843517,0.932987
1991,0.982029,0.832748,0.877510,0.830956,0.929716,0.981610,1.074805,1.065725,0.933926,0.895081,0.881523,0.926855
1992,0.976771,0.873690,0.903671,0.851408,0.884261,0.952346,1.071044,1.028404,0.948144,0.893679,0.890645,0.975203
1993,0.988619,0.904701,0.952969,0.856112,0.891241,1.004446,1.138922,1.136096,0.963127,0.913957,0.919608,0.992791
1994,1.057006,0.908921,0.941115,0.877785,0.921953,1.073032,1.135390,1.122068,0.971261,0.935755,0.918756,0.983144
1995,1.020545,0.920356,0.953315,0.892738,0.964060,1.044201,1.205279,1.261323,1.012529,0.962930,0.953811,1.041632
1996,1.083104,0.987395,1.003204,0.917824,1.029640,1.104239,1.195402,1.201158,1.032868,0.990172,0.981693,1.036875
1997,1.096422,0.941600,0.993133,0.942160,0.995524,1.091015,1.256714,1.214335,1.098183,1.039505,0.988984,1.081036
1998,1.077039,0.950570,1.046462,0.952903,1.093015,1.199760,1.320258,1.303584,1.163360,1.037589,0.974450,1.086982
1999,1.152013,1.002479,1.087561,1.023996,1.094686,1.199836,1.373522,1.327899,1.114448,1.035726,0.988892,1.076725
2000,1.196443,1.073059,1.100091,1.041719,1.178058,1.236787,1.300529,1.344818,1.139731,1.055851,1.038409,1.163675
2001,1.212856,1.032098,1.096906,1.014365,1.096122,1.195349,1.304489,1.351615,1.119603,1.075118,1.017484,1.114378
2002,1.167070,1.028033,1.103626,1.057297,1.122323,1.243971,1.391774,1.366400,1.208428,1.120080,1.080793,1.184916
2003,1.247494,1.091588,1.110077,1.042368,1.121850,1.198996,1.365707,1.392775,1.178721,1.118918,1.086547,1.209891
2004,1.264116,1.146418,1.126473,1.059893,1.194205,1.258788,1.376416,1.343978,1.224270,1.139744,1.101993,1.247344
2005,1.251625,1.088858,1.158012,1.056254,1.149271,1.326587,1.467399,1.477127,1.277511,1.154144,1.116635,1.269789
2006,1.198865,1.121079,1.162650,1.086515,1.206007,1.328733,1.497117,1.487420,1.211258,1.173000,1.127737,1.226681
2007,1.289597,1.179067,1.169002,1.105742,1.204501,1.323243,1.434396,1.538613,1.296392,1.213302,1.145771,1.263184
2008,1.324131,1.185907,1.184172,1.115723,1.186415,1.361013,1.469684,1.418931,1.233148,1.161985,1.130975,1.254459
2009,1.294928,1.097565,1.133005,1.056163,1.135569,1.268174,1.358945,1.390605,1.194279,1.120010,1.082052,1.278567
2010,1.316685,1.166316,1.138713,1.049826,1.196234,1.370681,1.494580,1.491512,1.262290,1.123221,1.116250,1.320924
2011,1.323670,1.142211,1.162578,1.103086,1.180518,1.341380,1.527291,1.482856,1.232693,1.126058,1.109292,1.224701
2012,1.238518,1.128579,1.127488,1.076922,1.227536,1.316208,1.512506,1.443417,1.220486,1.136828,1.116124,1.220669
2013,1.272950,1.129814,1.186977,1.091895,1.175147,1.301604,1.440302,1.405430,1.243671,1.148773,1.147365,1.287737
2014,1.376135,1.183146,1.210411,1.085685,1.184517,1.305330,1.407232,1.401985,1.239825,1.147301,1.158146,1.232785
2015,1.314854,1.220087,1.182575,1.072928,1.174896,1.321982,1.460632,1.430346,1.277160,1.138509,1.096711,1.183433
2016,1.286635,1.144249,1.110340,1.068406,1.155554,1.341578,1.502465,1.494491,1.282131,1.141549,1.083610,1.259727
2017,1.256041,1.061680,1.164860,1.077405,1.179856,1.307803,1.475273,1.403434,1.225337,1.162431,1.123701,1.278233
2018,1.361455,1.119477,1.172926,1.097088,1.236400,1.356550,1.500289,1.488388,1.299545,1.185274,1.175924,1.248042
2019,1.311404,1.149141,1.191567,1.082154,1.205304,1.287616,1.495720,1.464320,1.315085,1.168567,1.152142,1.234408
2020,1.246988,1.165642,1.129298,1.019853,1.111083,1.283081,1.493983,1.452829,1.215646,1.143687,1.098889,1.256092
2021,1.279619,1.189985,1.139140,1.066983,1.163120,1.363367,1.476427,1.507814,1.270153,1.165964,1.150850,1.239086
2022,1.382380,1.195615,1.188995,1.110191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# pivot2.stack()

### 2.Reshaping by stacking and unstacking

In [25]:
df2= df
df

,Month,Coal,Petroleum,Natural_gas,Other_gases,Nuclear_Electirc_Power,Hydroelectric_Pumped_Storage,Conventional_Hydroelectric_Power,Wood,Waste,Geothermal,Solar,Wind,Total,month,year
0,1973-01-01,75190.149,31183.619,21184.967,Not Available,6246.251,Not Available,26249.203,5.157,15.152,143.490,Not Available,Not Available,160217.989,1,1973
1,1973-02-01,67797.946,26086.952,20252.525,Not Available,5928.069,Not Available,23313.025,15.138,13.874,131.171,Not Available,Not Available,143538.699,2,1973
2,1973-03-01,67387.612,24033.245,24043.248,Not Available,6649.007,Not Available,25874.466,17.940,16.913,135.938,Not Available,Not Available,148158.370,3,1973
3,1973-04-01,63935.049,20195.424,25030.266,Not Available,5876.392,Not Available,24370.510,6.323,16.771,158.705,Not Available,Not Available,139589.440,4,1973
4,1973-05-01,64927.181,21741.975,29755.984,Not Available,5696.657,Not Available,25100.563,4.589,20.209,147.965,Not Available,Not Available,147395.124,5,1973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,2021-12-01,59878.052,1476.845,127168.673,889.284,70719.837,-445.116,25649.675,3188.972,1597.551,1454.154,6354.878,40675.582,339684.017,12,2021
588,2022-01-01,87505.587,3784.942,136317.103,971.401,70576.875,-493.31,27016.979,3084.085,1488.615,1499.622,8003.896,38193.633,378966.702,1,2022
589,2022-02-01,70761.756,1604.619,115615.259,832.322,61861.903,-412.258,23669.921,2991.538,1336.161,1250.063,9202.56,38162.282,327766.846,2,2022
590,2022-03-01,60767.670,1422.594,112002.542,894.172,63153.701,-317.508,26139.444,3020.778,1449.529,1326.450,11890.566,43230.383,325952.002,3,2022
591,2022-04-01,55056.190,1237.486,105934.050,903.778,55289.540,-265.226,20194.347,2733.715,1364.032,1276.166,13484.08,46217.243,304348.709,4,2022

In [26]:
df2.dtypes

Month                               datetime64[ns]
Coal                                       float64
Petroleum                                  float64
Natural_gas                                float64
Other_gases                                 object
Nuclear_Electirc_Power                     float64
Hydroelectric_Pumped_Storage                object
Conventional_Hydroelectric_Power           float64
Wood                                       float64
Waste                                      float64
Geothermal                                 float64
Solar                                       object
Wind                                        object
Total                                      float64
month                                        int64
year                                         int64
dtype: object

In [27]:
# df2 = df2.replace(to_replace="Not Available",
#            value= 0)
# df2 = df2.astype({'Other_gases':'float','Hydroelectric_Pumped_Storage':'float','Solar':'float','Wind':'float'})
# # df2['Other_gases'] = df2['Other_gases'].astype(float)
# df2.dtypes
df2['Other_gases']= pd.to_numeric(df2['Other_gases'],errors = 'coerce')
df2['Hydroelectric_Pumped_Storage']= pd.to_numeric(df2['Hydroelectric_Pumped_Storage'],errors = 'coerce')
df2['Solar']= pd.to_numeric(df2['Solar'],errors = 'coerce')
df2['Wind']= pd.to_numeric(df2['Wind'],errors = 'coerce')

df2= df2.fillna(value=0)

In [28]:
df2.dtypes

Month                               datetime64[ns]
Coal                                       float64
Petroleum                                  float64
Natural_gas                                float64
Other_gases                                float64
Nuclear_Electirc_Power                     float64
Hydroelectric_Pumped_Storage               float64
Conventional_Hydroelectric_Power           float64
Wood                                       float64
Waste                                      float64
Geothermal                                 float64
Solar                                      float64
Wind                                       float64
Total                                      float64
month                                        int64
year                                         int64
dtype: object

In [29]:
# df2[df2['Natural_gas']== 'Not Available']
# df2['Other_gases'].str.lstrip('$').astype(float)
# df2.fillna(value=0)

In [30]:
df2['non-renewable'] = df2.Coal + df2.Petroleum + df2.Natural_gas + df2.Other_gases + df2.Nuclear_Electirc_Power 
df2['renewable']  = df2.Wind + df2.Solar + df2.Geothermal + df2.Waste + df2.Wood + df2.Conventional_Hydroelectric_Power + df2.Hydroelectric_Pumped_Storage

In [31]:
df2

,Month,Coal,Petroleum,Natural_gas,Other_gases,Nuclear_Electirc_Power,Hydroelectric_Pumped_Storage,Conventional_Hydroelectric_Power,Wood,Waste,Geothermal,Solar,Wind,Total,month,year,non-renewable,renewable
0,1973-01-01,75190.149,31183.619,21184.967,0.000,6246.251,0.000,26249.203,5.157,15.152,143.490,0.000,0.000,160217.989,1,1973,133804.986,26413.002
1,1973-02-01,67797.946,26086.952,20252.525,0.000,5928.069,0.000,23313.025,15.138,13.874,131.171,0.000,0.000,143538.699,2,1973,120065.492,23473.208
2,1973-03-01,67387.612,24033.245,24043.248,0.000,6649.007,0.000,25874.466,17.940,16.913,135.938,0.000,0.000,148158.370,3,1973,122113.112,26045.257
3,1973-04-01,63935.049,20195.424,25030.266,0.000,5876.392,0.000,24370.510,6.323,16.771,158.705,0.000,0.000,139589.440,4,1973,115037.131,24552.309
4,1973-05-01,64927.181,21741.975,29755.984,0.000,5696.657,0.000,25100.563,4.589,20.209,147.965,0.000,0.000,147395.124,5,1973,122121.797,25273.326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,2021-12-01,59878.052,1476.845,127168.673,889.284,70719.837,-445.116,25649.675,3188.972,1597.551,1454.154,6354.878,40675.582,339684.017,12,2021,260132.691,78475.696
588,2022-01-01,87505.587,3784.942,136317.103,971.401,70576.875,-493.310,27016.979,3084.085,1488.615,1499.622,8003.896,38193.633,378966.702,1,2022,299155.908,78793.520
589,2022-02-01,70761.756,1604.619,115615.259,832.322,61861.903,-412.258,23669.921,2991.538,1336.161,1250.063,9202.560,38162.282,327766.846,2,2022,250675.859,76200.267
590,2022-03-01,60767.670,1422.594,112002.542,894.172,63153.701,-317.508,26139.444,3020.778,1449.529,1326.450,11890.566,43230.383,325952.002,3,2022,238240.679,86739.642
591,2022-04-01,55056.190,1237.486,105934.050,903.778,55289.540,-265.226,20194.347,2733.715,1364.032,1276.166,13484.080,46217.243,304348.709,4,2022,218421.044,85004.357

In [32]:
# df2['month'] = pd.DatetimeIndex(df2['Month']).month
# df2['year'] = pd.DatetimeIndex(df2['Month']).year
df2 = df2.drop('Month Coal Petroleum Natural_gas Other_gases Nuclear_Electirc_Power Hydroelectric_Pumped_Storage Conventional_Hydroelectric_Power Wood Waste Geothermal Solar Wind'.split(),axis=1)
df2

          Total  month  year  non-renewable  renewable
0    160217.989      1  1973     133804.986  26413.002
1    143538.699      2  1973     120065.492  23473.208
2    148158.370      3  1973     122113.112  26045.257
3    139589.440      4  1973     115037.131  24552.309
4    147395.124      5  1973     122121.797  25273.326
..          ...    ...   ...            ...        ...
587  339684.017     12  2021     260132.691  78475.696
588  378966.702      1  2022     299155.908  78793.520
589  327766.846      2  2022     250675.859  76200.267
590  325952.002      3  2022     238240.679  86739.642
591  304348.709      4  2022     218421.044  85004.357

[592 rows x 5 columns]

In [33]:
#same

In [34]:
pivot3= df2.pivot(index='year',columns='month')

In [35]:
pivot3

            Total                                                              \
month          1           2           3           4           5           6
year
1973   160217.989  143538.699  148158.370  139589.440  147395.124  161243.674
1974   157554.691  142748.458  150342.206  142311.633  153812.873  156440.089
1975   164623.080  147349.000  155760.211  146494.879  153531.080  162716.960
1976   178608.612  156965.799  164466.676  153467.392  157664.467  173673.719
1977   196665.182  162949.088  169437.171  157117.355  169596.403  181031.212
1978   198107.635  173745.731  173460.887  160012.982  175548.628  188585.386
1979   209986.749  186587.309  183154.004  170260.472  178409.356  186976.379
1980   200296.330  188961.379  187744.800  169016.585  176066.486  189748.486
1981   206758.205  179859.910  185833.882  172841.342  178138.553  203020.751
1982   209694.373  180545.573  187967.965  172876.502  177479.981  186447.119
1983   195870.844  172725.190  182768.722  170668.876  174724.813  191367.206
1984   216923.729  189810.043  200387.475  181381.139  192550.198  209967.314
1985   228147.888  198488.497  195250.388  185173.312  197122.843  205681.971
1986   217761.136  192582.016  197114.555  186370.454  197647.498  215334.156
1987   223040.975  194280.625  202129.944  189792.417  206406.878  225907.915
1988   238188.434  217183.084  214293.615  196297.111  208703.604  233065.853
1989   246766.176  233782.777  241946.410  222868.586  234824.770  250919.110
1990   255187.021  229499.204  244761.483  229769.727  241773.529  268992.258
1991   269214.313  228290.131  240561.216  227798.971  254873.018  269099.254
1992   267772.670  239514.031  247733.163  233405.563  242411.928  261076.926
1993   271020.902  248015.328  261247.551  234695.127  244325.583  275359.600
1994   289768.406  249172.290  257998.052  240636.581  252744.936  294161.782
1995   279773.101  252307.149  261342.562  244735.923  264288.242  286258.135
1996   296922.971  270685.247  275019.018  251612.875  282266.414  302716.899
1997   300573.901  258131.029  272258.227  258284.482  272913.783  299091.561
1998   295260.404  260589.918  286877.989  261229.604  299639.908  328903.002
1999   315813.690  274820.273  298144.718  280719.013  300098.190  328923.833
2000   327993.944  294169.282  301579.821  285577.749  322953.681  339053.660
2001   332493.160  282940.198  300706.544  278078.871  300491.621  327693.978
2002   319941.472  281825.708  302549.007  289848.252  307674.569  341023.145
2003   341988.899  299248.775  304317.263  285755.700  307544.887  328693.699
2004   346545.627  314279.910  308812.096  290559.914  327380.264  345085.079
2005   343121.453  298500.316  317458.276  289562.400  315062.110  363671.636
2006   328657.739  307333.430  318729.800  297858.078  330615.570  364259.798
2007   353531.095  323230.395  320471.243  303129.064  330202.758  362754.877
2008   362998.429  325105.597  324629.850  305865.031  325244.802  373109.027
2009   354992.636  300887.398  310602.964  289537.255  311305.872  347658.241
2010   360957.167  319734.727  312167.640  287800.227  327936.492  375759.478
2011   362871.893  313126.607  318709.941  302400.724  323628.238  367727.015
2012   339528.259  309389.420  309090.569  295228.216  336517.631  360826.151
2013   348967.378  309728.080  325398.834  299332.868  322155.640  356822.647
2014   377254.711  324348.436  331823.059  297630.588  324724.300  357844.043
2015   360455.167  334475.546  324191.894  294133.343  322086.912  362409.202
2016   352719.066  313685.401  304389.581  292893.550  316784.457  367781.196
2017   344332.034  291049.672  319335.755  295360.591  323446.738  358522.007
2018   373230.280  306894.214  321546.954  300756.440  338947.606  371885.761
2019   359509.234  315026.484  326657.208  296662.569  330423.048  352988.074
2020   341850.206  319550.114  309586.723  279583.265  304593.238  351744.930
2021   350795.813  326223.389  312284.622  292503.539  318858.513  373754.405
2022   378966.702  327766.846  325952.002  304348.709         NaN         NaN

                                                       ...  renewable  \
month          7           8           9           10  ...         3
year                                                   ...
1973   173733.007  177365.364  156875.032  154197.466  ...  26045.257
1974   178247.304  174119.001  152467.442  152195.832  ...  28053.082
1975   177056.505  179930.892  155440.826  155187.742  ...  28480.561
1976   186691.040  186638.696  165237.437  164009.445  ...  27201.037
1977   199167.726  196363.166  176497.560  166645.282  ...  20436.963
1978   202947.293  206658.749  185802.058  176013.116  ...  25161.617
1979   202522.477  205100.592  180974.646  179953.363  ...  26608.010
1980   217057.853  215629.382  191697.740  178761.034  ...  25013.631
1981   220654.747  210639.415  187051.489  181557.590  ...  21393.690
1982   210865.079  205891.676  180875.268  173172.248  ...  30495.266
1983   220446.836  230193.460  195817.014  183136.711  ...  31037.573
1984   221526.162  229531.666  195411.388  191142.430  ...  31434.051
1985   227003.762  226286.447  202712.422  194995.217  ...  25850.124
1986   242953.552  225402.481  206905.101  197959.776  ...  29729.505
1987   248196.221  247880.760  213221.249  203214.924  ...  24562.927
1988   257742.125  267928.593  220392.242  210813.885  ...  20835.409
1989   273457.735  275419.519  242793.798  235669.018  ...  27761.137
1990   287447.762  290655.259  258356.632  244372.250  ...  34828.779
1991   294647.834  292158.580  256027.328  245378.242  ...  31844.584
1992   293616.745  281927.430  259925.035  244993.925  ...  27999.393
1993   312224.835  311450.190  264032.481  250552.792  ...  31930.748
1994   311256.823  307604.584  266262.327  256528.490  ...  30186.453
1995   330416.095  345780.079  277575.357  263978.440  ...  33754.542
1996   327708.462  329286.330  283151.263  271446.494  ...  39565.711
1997   344516.455  332898.630  301056.672  284970.629  ...  40712.864
1998   361936.460  357365.610  318924.466  284445.547  ...  37954.135
1999   376538.308  364031.383  305515.654  283934.839  ...  37380.334
2000   356527.917  368669.365  312446.647  289451.903  ...  33200.063
2001   357613.700  370532.828  306928.866  294733.613  ...  25499.065
2002   381542.109  374585.823  331279.434  307059.462  ...  26678.710
2003   374396.049  381816.318  323135.536  306740.934  ...  30143.422
2004   377331.697  368439.037  335622.198  312450.223  ...  29261.554
2005   402273.846  404940.681  350217.801  316397.924  ...  29807.860
2006   410420.793  407762.536  332055.321  321567.091  ...  32388.490
2007   393226.432  421796.659  355393.912  332615.416  ...  32483.761
2008   402900.336  388986.719  338056.130  318547.343  ...  31819.053
2009   372542.226  381221.417  327400.612  307040.341  ...  34462.001
2010   409725.440  408884.155  346045.172  307920.691  ...  35214.695
2011   418692.755  406511.315  337931.318  308698.504  ...  47435.791
2012   414639.671  395699.566  334584.877  311650.774  ...  45828.117
2013   394845.621  385285.745  340940.902  314925.463  ...  42882.331
2014   385779.552  384341.148  339886.506  314521.999  ...  49686.405
2015   400418.853  392116.203  350121.648  312111.680  ...  47814.907
2016   411886.942  409700.812  351484.468  312945.164  ...  58089.881
2017   404432.474  384738.580  335914.910  318669.649  ...  66027.418
2018   411290.320  408027.757  356258.302  324931.943  ...  63626.543
2019   410037.810  401429.694  360518.468  320351.885  ...  63860.077
2020   409561.700  398279.697  333258.048  313531.271  ...  65420.145
2021   404748.717  413353.176  348200.651  319638.396  ...  76624.292
2022          NaN         NaN         NaN         NaN  ...  86739.642

                                                                         \
month         4          5          6          7          8          9
year
1973   24552.309  25273.326  24240.615  22884.694  21578.636  17480.982
1974   28346.187  28453.726  27097.194  26735.794  24474.015  21794.475
1975   27133.136  28268.477  27734.136  26075.189  23170.172  21039.506
1976   24748.570  26110.084  26158.453  26659.362  24413.543  20897.571
1977   19225.473  19282.856  17805.593  17364.344  17266.370  16999.677
1978   25788.224  29256.131  25619.274  24968.745  22744.596  21725.694
1979   26029.779  29629.392  25619.443  23392.849  21914.771  19555.501
1980   26455.027  29665.334  28420.038  25225.145  21184.607  19173.210
1981   21519.438  24896.566  27161.385  25937.479  22371.409  18572.955
1982   28552.739  28684.615  28729.295  28060.188  24610.375  20576.777
1983   30709.732  31882.370  31473.524  28959.589  26801.321  22602.813
1984   30961.957  32819.440  29745.637  28424.295  26167.086  21851.936
1985   25482.422  27569.849  24945.752  22459.120  21151.129  19867.121
1986   28710.832  28440.455  27515.672  25398.166  22483.632  22221.906
1987   23287.172  25546.673  22252.261  21578.831  19783.505  19404.348
1988   20359.579  22493.063  20156.057  18268.892  17747.021  17484.716
1989   28808.607  32621.442  30678.854  27670.139  25421.615  24087.527
1990   31732.310  32871.153  32997.759  29496.012  27436.640  23098.894
1991   31033.293  34484.794  31800.550  30056.089  28712.427  25711.324
1992   25380.240  27677.794  29267.757  26672.614  25574.923  23938.070
1993   32283.431  35573.202  32596.186  29951.968  27222.600  24361.909
1994   30572.712  30800.985  30105.325  29936.896  26374.394  22193.363
1995   30558.997  32667.449  35157.625  34457.327  32178.920  26522.622
1996   36497.549  38292.055  38017.707  36317.861  33630.210  28281.778
1997   38323.973  40956.937  40111.762  38208.348  33668.706  29231.105
1998   34045.670  38647.879  36417.367  34869.031  31445.370  27450.052
1999   33453.790  36174.055  36403.530  36335.047  31874.173  27043.516
2000   35068.774  33954.613  30817.602  30702.559  28462.447  23358.549
2001   23043.770  24291.245  25918.383  23452.814  24492.409  20097.295
2002   30204.788  32883.433  34415.516  31529.231  27193.340  22892.180
2003   30887.070  35271.056  34502.096  31107.035  28956.093  24248.269
2004   27114.370  30670.154  31632.078  29891.889  27800.605  26452.188
2005   29921.811  34355.997  34004.470  32896.820  28178.683  23977.444
2006   35828.296  38409.736  37116.575  32923.071  28927.413  24292.914
2007   32209.740  34121.009  30842.830  30254.305  28184.553  22841.729
2008   33073.233  37734.119  39950.646  35089.216  30095.762  24584.489
2009   38483.532  41075.300  40474.468  34080.568  30758.784  27535.090
2010   34368.614  39269.294  43591.310  37066.804  32619.031  30071.332
2011   48853.949  49807.917  48868.248  44577.418  39124.787  33842.048
2012   44592.247  47169.856  44621.589  41597.086  37835.099  32574.498
2013   48765.761  51370.317  47980.078  45506.910  38550.712  35513.919
2014   51537.603  49765.439  49554.961  44856.931  37987.699  35425.809
2015   48750.922  45937.412  42576.926  43955.301  41317.620  38197.460
2016   55092.596  53876.725  48975.925  49043.898  43132.802  42181.713
2017   65484.645  67376.721  62782.187  54427.234  47581.462  47842.690
2018   66241.346  67322.238  65772.266  54525.608  54565.891  49241.161
2019   68955.286  70511.306  64177.848  60977.064  56421.730  55293.288
2020   66322.848  73510.051  72920.106  65425.812  60887.218  54737.452
2021   71541.439  74236.846  68244.802  61085.897  65121.239  63258.203
2022   85004.357        NaN        NaN        NaN        NaN        NaN


month         10         11         12
year
1973   18661.753  20446.638  26674.160
1974   20413.638  21576.359  23568.166
1975   23223.672  25002.478  26578.416
1976   21623.302  20357.866  20818.147
1977   17792.227  21033.467  23415.655
1978   19947.472  20450.822  22662.299
1979   20793.550  23016.992  23450.383
1980   18605.275  19959.082  23031.770
1981   18825.826  19649.741  24571.374
1982   20465.608  24037.895  28410.580
1983   21664.692  25536.461  32455.752
1984   21911.040  23307.830  26961.539
1985   21102.722  24206.379  26707.559
1986   22413.363  24156.389  27222.208
1987   19175.907  18061.373  22336.027
1988   16331.662  19672.899  21129.235
1989   25411.036  26590.750  27212.986
1990   24766.087  25809.528  30447.023
1991   24385.390  25179.259  29253.126
1992   23798.983  26660.055  31527.586
1993   24366.667  25709.171  28920.301
1994   24248.402  25657.207  28593.727
1995   30280.790  32125.433  35126.135
1996   30049.380  30383.764  36450.551
1997   31956.575  29634.547  31535.308
1998   25770.058  25454.783  32718.519
1999   25549.099  27482.290  30895.383
2000   23891.357  26125.954  25343.866
2001   20669.729  20314.962  24761.946
2002   23049.535  25313.337  27485.909
2003   24361.051  25550.490  30450.654
2004   25010.362  26763.898  32585.291
2005   24577.195  26120.574  29218.983
2006   24842.875  28023.545  29433.155
2007   23397.767  24049.086  27329.076
2008   25620.068  25961.225  32753.622
2009   31974.019  33488.244  37406.982
2010   31036.353  34876.844  37997.858
2011   35736.646  38812.204  40408.541
2012   35347.292  36540.606  43809.058
2013   37883.538  40294.260  42333.508
2014   39430.053  44901.356  44470.386
2015   40895.098  47117.376  51486.763
2016   46527.055  47020.477  54357.769
2017   52498.813  51769.453  53838.024
2018   51451.998  53647.218  56340.436
2019   57428.569  54903.006  57216.976
2020   59910.591  65222.203  64343.520
2021   65065.088  69649.783  78475.696
2022         NaN        NaN        NaN

[50 rows x 36 columns]

In [36]:
# pivot3.stack(level=['month'])

In [37]:
pivot3.columns

MultiIndex([(        'Total',  1),
            (        'Total',  2),
            (        'Total',  3),
            (        'Total',  4),
            (        'Total',  5),
            (        'Total',  6),
            (        'Total',  7),
            (        'Total',  8),
            (        'Total',  9),
            (        'Total', 10),
            (        'Total', 11),
            (        'Total', 12),
            ('non-renewable',  1),
            ('non-renewable',  2),
            ('non-renewable',  3),
            ('non-renewable',  4),
            ('non-renewable',  5),
            ('non-renewable',  6),
            ('non-renewable',  7),
            ('non-renewable',  8),
            ('non-renewable',  9),
            ('non-renewable', 10),
            ('non-renewable', 11),
            ('non-renewable', 12),
            (    'renewable',  1),
            (    'renewable',  2),
            (    'renewable',  3),
            (    'renewable',  4),
            (    'renewable',  5),
            (    'renewable',  6),
            (    'renewable',  7),
            (    'renewable',  8),
            (    'renewable',  9),
            (    'renewable', 10),
            (    'renewable', 11),
            (    'renewable', 12)],
           names=[None, 'month'])

In [38]:
stacked1= pivot3.stack()  #stack(1) #stack('month')    # stack inner coloumn
stacked1

                 Total  non-renewable  renewable
year month
1973 1      160217.989     133804.986  26413.002
     2      143538.699     120065.492  23473.208
     3      148158.370     122113.112  26045.257
     4      139589.440     115037.131  24552.309
     5      147395.124     122121.797  25273.326
...                ...            ...        ...
2021 12     339684.017     260132.691  78475.696
2022 1      378966.702     299155.908  78793.520
     2      327766.846     250675.859  76200.267
     3      325952.002     238240.679  86739.642
     4      304348.709     218421.044  85004.357

[592 rows x 3 columns]

In [39]:
stacked1.columns

Index(['Total', 'non-renewable', 'renewable'], dtype='object')

In [40]:
stacked3= pivot3.stack(0)   # stack the outmost or 0th index of column
stacked3

month                       1           2           3           4   \
year
1973 Total          160217.989  143538.699  148158.370  139589.440
     non-renewable  133804.986  120065.492  122113.112  115037.131
     renewable       26413.002   23473.208   26045.257   24552.309
1974 Total          157554.691  142748.458  150342.206  142311.633
     non-renewable  128161.539  115739.129  122289.124  113965.447
...                        ...         ...         ...         ...
2021 non-renewable  281855.100  265166.887  234599.545  220001.226
     renewable       67835.764   60136.633   76624.292   71541.439
2022 Total          378966.702  327766.846  325952.002  304348.709
     non-renewable  299155.908  250675.859  238240.679  218421.044
     renewable       78793.520   76200.267   86739.642   85004.357

month                       5           6           7           8   \
year
1973 Total          147395.124  161243.674  173733.007  177365.364
     non-renewable  122121.797  137003.059  150848.314  155786.728
     renewable       25273.326   24240.615   22884.694   21578.636
1974 Total          153812.873  156440.089  178247.304  174119.001
     non-renewable  125359.148  129342.894  151511.511  149644.987
...                        ...         ...         ...         ...
2021 non-renewable  243624.101  304507.145  342615.752  347196.954
     renewable       74236.846   68244.802   61085.897   65121.239
2022 Total                 NaN         NaN         NaN         NaN
     non-renewable         NaN         NaN         NaN         NaN
     renewable             NaN         NaN         NaN         NaN

month                       9           10          11          12
year
1973 Total          156875.032  154197.466  148137.609  153604.858
     non-renewable  139394.051  135535.713  127690.969  126930.696
     renewable       17480.982   18661.753   20446.638   26674.160
1974 Total          152467.442  152195.832  150070.855  160009.019
     non-renewable  130672.968  131782.193  128494.496  136440.854
...                        ...         ...         ...         ...
2021 non-renewable  283963.927  253594.212  244867.182  260132.691
     renewable       63258.203   65065.088   69649.783   78475.696
2022 Total                 NaN         NaN         NaN         NaN
     non-renewable         NaN         NaN         NaN         NaN
     renewable             NaN         NaN         NaN         NaN

[150 rows x 12 columns]

In [41]:
pivot3.stack(0).index.names

FrozenList(['year', None])

In [42]:
stacked2 = stacked1.stack()  
stacked2

year  month
1973  1      Total            160217.989
             non-renewable    133804.986
             renewable         26413.002
      2      Total            143538.699
             non-renewable    120065.492
                                 ...
2022  3      non-renewable    238240.679
             renewable         86739.642
      4      Total            304348.709
             non-renewable    218421.044
             renewable         85004.357
Length: 1776, dtype: float64

In [43]:
type(stacked2)

pandas.core.series.Series

In [44]:
unstacked1 = stacked2.unstack()
unstacked1

                 Total  non-renewable  renewable
year month
1973 1      160217.989     133804.986  26413.002
     2      143538.699     120065.492  23473.208
     3      148158.370     122113.112  26045.257
     4      139589.440     115037.131  24552.309
     5      147395.124     122121.797  25273.326
...                ...            ...        ...
2021 12     339684.017     260132.691  78475.696
2022 1      378966.702     299155.908  78793.520
     2      327766.846     250675.859  76200.267
     3      325952.002     238240.679  86739.642
     4      304348.709     218421.044  85004.357

[592 rows x 3 columns]

In [45]:
stacked2.unstack('month')   # stacked2.unstack(1)

month                       1           2           3           4   \
year
1973 Total          160217.989  143538.699  148158.370  139589.440
     non-renewable  133804.986  120065.492  122113.112  115037.131
     renewable       26413.002   23473.208   26045.257   24552.309
1974 Total          157554.691  142748.458  150342.206  142311.633
     non-renewable  128161.539  115739.129  122289.124  113965.447
...                        ...         ...         ...         ...
2021 non-renewable  281855.100  265166.887  234599.545  220001.226
     renewable       67835.764   60136.633   76624.292   71541.439
2022 Total          378966.702  327766.846  325952.002  304348.709
     non-renewable  299155.908  250675.859  238240.679  218421.044
     renewable       78793.520   76200.267   86739.642   85004.357

month                       5           6           7           8   \
year
1973 Total          147395.124  161243.674  173733.007  177365.364
     non-renewable  122121.797  137003.059  150848.314  155786.728
     renewable       25273.326   24240.615   22884.694   21578.636
1974 Total          153812.873  156440.089  178247.304  174119.001
     non-renewable  125359.148  129342.894  151511.511  149644.987
...                        ...         ...         ...         ...
2021 non-renewable  243624.101  304507.145  342615.752  347196.954
     renewable       74236.846   68244.802   61085.897   65121.239
2022 Total                 NaN         NaN         NaN         NaN
     non-renewable         NaN         NaN         NaN         NaN
     renewable             NaN         NaN         NaN         NaN

month                       9           10          11          12
year
1973 Total          156875.032  154197.466  148137.609  153604.858
     non-renewable  139394.051  135535.713  127690.969  126930.696
     renewable       17480.982   18661.753   20446.638   26674.160
1974 Total          152467.442  152195.832  150070.855  160009.019
     non-renewable  130672.968  131782.193  128494.496  136440.854
...                        ...         ...         ...         ...
2021 non-renewable  283963.927  253594.212  244867.182  260132.691
     renewable       63258.203   65065.088   69649.783   78475.696
2022 Total                 NaN         NaN         NaN         NaN
     non-renewable         NaN         NaN         NaN         NaN
     renewable             NaN         NaN         NaN         NaN

[150 rows x 12 columns]

In [46]:
# df2['range'] = 'Low'

In [47]:
# df2['range'][df2['Total']>=Tot_mean]= 'High'

In [48]:
# df2

In [49]:
# df2.pivot(values='Total',index=['year','month'],columns=['range'])

In [50]:
#Multiple levels

In [51]:
stacked3 = pivot3.stack(0)
stacked3

month                       1           2           3           4   \
year
1973 Total          160217.989  143538.699  148158.370  139589.440
     non-renewable  133804.986  120065.492  122113.112  115037.131
     renewable       26413.002   23473.208   26045.257   24552.309
1974 Total          157554.691  142748.458  150342.206  142311.633
     non-renewable  128161.539  115739.129  122289.124  113965.447
...                        ...         ...         ...         ...
2021 non-renewable  281855.100  265166.887  234599.545  220001.226
     renewable       67835.764   60136.633   76624.292   71541.439
2022 Total          378966.702  327766.846  325952.002  304348.709
     non-renewable  299155.908  250675.859  238240.679  218421.044
     renewable       78793.520   76200.267   86739.642   85004.357

month                       5           6           7           8   \
year
1973 Total          147395.124  161243.674  173733.007  177365.364
     non-renewable  122121.797  137003.059  150848.314  155786.728
     renewable       25273.326   24240.615   22884.694   21578.636
1974 Total          153812.873  156440.089  178247.304  174119.001
     non-renewable  125359.148  129342.894  151511.511  149644.987
...                        ...         ...         ...         ...
2021 non-renewable  243624.101  304507.145  342615.752  347196.954
     renewable       74236.846   68244.802   61085.897   65121.239
2022 Total                 NaN         NaN         NaN         NaN
     non-renewable         NaN         NaN         NaN         NaN
     renewable             NaN         NaN         NaN         NaN

month                       9           10          11          12
year
1973 Total          156875.032  154197.466  148137.609  153604.858
     non-renewable  139394.051  135535.713  127690.969  126930.696
     renewable       17480.982   18661.753   20446.638   26674.160
1974 Total          152467.442  152195.832  150070.855  160009.019
     non-renewable  130672.968  131782.193  128494.496  136440.854
...                        ...         ...         ...         ...
2021 non-renewable  283963.927  253594.212  244867.182  260132.691
     renewable       63258.203   65065.088   69649.783   78475.696
2022 Total                 NaN         NaN         NaN         NaN
     non-renewable         NaN         NaN         NaN         NaN
     renewable             NaN         NaN         NaN         NaN

[150 rows x 12 columns]

In [52]:
stacked3.index.names=['year','source']
stacked3

month                       1           2           3           4   \
year source
1973 Total          160217.989  143538.699  148158.370  139589.440
     non-renewable  133804.986  120065.492  122113.112  115037.131
     renewable       26413.002   23473.208   26045.257   24552.309
1974 Total          157554.691  142748.458  150342.206  142311.633
     non-renewable  128161.539  115739.129  122289.124  113965.447
...                        ...         ...         ...         ...
2021 non-renewable  281855.100  265166.887  234599.545  220001.226
     renewable       67835.764   60136.633   76624.292   71541.439
2022 Total          378966.702  327766.846  325952.002  304348.709
     non-renewable  299155.908  250675.859  238240.679  218421.044
     renewable       78793.520   76200.267   86739.642   85004.357

month                       5           6           7           8   \
year source
1973 Total          147395.124  161243.674  173733.007  177365.364
     non-renewable  122121.797  137003.059  150848.314  155786.728
     renewable       25273.326   24240.615   22884.694   21578.636
1974 Total          153812.873  156440.089  178247.304  174119.001
     non-renewable  125359.148  129342.894  151511.511  149644.987
...                        ...         ...         ...         ...
2021 non-renewable  243624.101  304507.145  342615.752  347196.954
     renewable       74236.846   68244.802   61085.897   65121.239
2022 Total                 NaN         NaN         NaN         NaN
     non-renewable         NaN         NaN         NaN         NaN
     renewable             NaN         NaN         NaN         NaN

month                       9           10          11          12
year source
1973 Total          156875.032  154197.466  148137.609  153604.858
     non-renewable  139394.051  135535.713  127690.969  126930.696
     renewable       17480.982   18661.753   20446.638   26674.160
1974 Total          152467.442  152195.832  150070.855  160009.019
     non-renewable  130672.968  131782.193  128494.496  136440.854
...                        ...         ...         ...         ...
2021 non-renewable  283963.927  253594.212  244867.182  260132.691
     renewable       63258.203   65065.088   69649.783   78475.696
2022 Total                 NaN         NaN         NaN         NaN
     non-renewable         NaN         NaN         NaN         NaN
     renewable             NaN         NaN         NaN         NaN

[150 rows x 12 columns]

In [53]:
stacked4 =stacked3.stack()
stacked4

year  source         month
1973  Total          1        160217.989
                     2        143538.699
                     3        148158.370
                     4        139589.440
                     5        147395.124
                                 ...
2022  non-renewable  4        218421.044
      renewable      1         78793.520
                     2         76200.267
                     3         86739.642
                     4         85004.357
Length: 1776, dtype: float64

In [54]:
stacked4.unstack(level=['source','month'])

source       Total                                                  \
month           1           2           3           4           5
year
1973    160217.989  143538.699  148158.370  139589.440  147395.124
1974    157554.691  142748.458  150342.206  142311.633  153812.873
1975    164623.080  147349.000  155760.211  146494.879  153531.080
1976    178608.612  156965.799  164466.676  153467.392  157664.467
1977    196665.182  162949.088  169437.171  157117.355  169596.403
1978    198107.635  173745.731  173460.887  160012.982  175548.628
1979    209986.749  186587.309  183154.004  170260.472  178409.356
1980    200296.330  188961.379  187744.800  169016.585  176066.486
1981    206758.205  179859.910  185833.882  172841.342  178138.553
1982    209694.373  180545.573  187967.965  172876.502  177479.981
1983    195870.844  172725.190  182768.722  170668.876  174724.813
1984    216923.729  189810.043  200387.475  181381.139  192550.198
1985    228147.888  198488.497  195250.388  185173.312  197122.843
1986    217761.136  192582.016  197114.555  186370.454  197647.498
1987    223040.975  194280.625  202129.944  189792.417  206406.878
1988    238188.434  217183.084  214293.615  196297.111  208703.604
1989    246766.176  233782.777  241946.410  222868.586  234824.770
1990    255187.021  229499.204  244761.483  229769.727  241773.529
1991    269214.313  228290.131  240561.216  227798.971  254873.018
1992    267772.670  239514.031  247733.163  233405.563  242411.928
1993    271020.902  248015.328  261247.551  234695.127  244325.583
1994    289768.406  249172.290  257998.052  240636.581  252744.936
1995    279773.101  252307.149  261342.562  244735.923  264288.242
1996    296922.971  270685.247  275019.018  251612.875  282266.414
1997    300573.901  258131.029  272258.227  258284.482  272913.783
1998    295260.404  260589.918  286877.989  261229.604  299639.908
1999    315813.690  274820.273  298144.718  280719.013  300098.190
2000    327993.944  294169.282  301579.821  285577.749  322953.681
2001    332493.160  282940.198  300706.544  278078.871  300491.621
2002    319941.472  281825.708  302549.007  289848.252  307674.569
2003    341988.899  299248.775  304317.263  285755.700  307544.887
2004    346545.627  314279.910  308812.096  290559.914  327380.264
2005    343121.453  298500.316  317458.276  289562.400  315062.110
2006    328657.739  307333.430  318729.800  297858.078  330615.570
2007    353531.095  323230.395  320471.243  303129.064  330202.758
2008    362998.429  325105.597  324629.850  305865.031  325244.802
2009    354992.636  300887.398  310602.964  289537.255  311305.872
2010    360957.167  319734.727  312167.640  287800.227  327936.492
2011    362871.893  313126.607  318709.941  302400.724  323628.238
2012    339528.259  309389.420  309090.569  295228.216  336517.631
2013    348967.378  309728.080  325398.834  299332.868  322155.640
2014    377254.711  324348.436  331823.059  297630.588  324724.300
2015    360455.167  334475.546  324191.894  294133.343  322086.912
2016    352719.066  313685.401  304389.581  292893.550  316784.457
2017    344332.034  291049.672  319335.755  295360.591  323446.738
2018    373230.280  306894.214  321546.954  300756.440  338947.606
2019    359509.234  315026.484  326657.208  296662.569  330423.048
2020    341850.206  319550.114  309586.723  279583.265  304593.238
2021    350795.813  326223.389  312284.622  292503.539  318858.513
2022    378966.702  327766.846  325952.002  304348.709         NaN

source                                                              ...  \
month           6           7           8           9           10  ...
year                                                                ...
1973    161243.674  173733.007  177365.364  156875.032  154197.466  ...
1974    156440.089  178247.304  174119.001  152467.442  152195.832  ...
1975    162716.960  177056.505  179930.892  155440.826  155187.742  ...
1976    173673.719  186691.040  186638.696  165237.437  164009.445  ...
1977    181031.212  199167.726  196363.166  176497.560  166645.282  ...
1978    188585.386  202947.293  206658.749  185802.058  176013.116  ...
1979    186976.379  202522.477  205100.592  180974.646  179953.363  ...
1980    189748.486  217057.853  215629.382  191697.740  178761.034  ...
1981    203020.751  220654.747  210639.415  187051.489  181557.590  ...
1982    186447.119  210865.079  205891.676  180875.268  173172.248  ...
1983    191367.206  220446.836  230193.460  195817.014  183136.711  ...
1984    209967.314  221526.162  229531.666  195411.388  191142.430  ...
1985    205681.971  227003.762  226286.447  202712.422  194995.217  ...
1986    215334.156  242953.552  225402.481  206905.101  197959.776  ...
1987    225907.915  248196.221  247880.760  213221.249  203214.924  ...
1988    233065.853  257742.125  267928.593  220392.242  210813.885  ...
1989    250919.110  273457.735  275419.519  242793.798  235669.018  ...
1990    268992.258  287447.762  290655.259  258356.632  244372.250  ...
1991    269099.254  294647.834  292158.580  256027.328  245378.242  ...
1992    261076.926  293616.745  281927.430  259925.035  244993.925  ...
1993    275359.600  312224.835  311450.190  264032.481  250552.792  ...
1994    294161.782  311256.823  307604.584  266262.327  256528.490  ...
1995    286258.135  330416.095  345780.079  277575.357  263978.440  ...
1996    302716.899  327708.462  329286.330  283151.263  271446.494  ...
1997    299091.561  344516.455  332898.630  301056.672  284970.629  ...
1998    328903.002  361936.460  357365.610  318924.466  284445.547  ...
1999    328923.833  376538.308  364031.383  305515.654  283934.839  ...
2000    339053.660  356527.917  368669.365  312446.647  289451.903  ...
2001    327693.978  357613.700  370532.828  306928.866  294733.613  ...
2002    341023.145  381542.109  374585.823  331279.434  307059.462  ...
2003    328693.699  374396.049  381816.318  323135.536  306740.934  ...
2004    345085.079  377331.697  368439.037  335622.198  312450.223  ...
2005    363671.636  402273.846  404940.681  350217.801  316397.924  ...
2006    364259.798  410420.793  407762.536  332055.321  321567.091  ...
2007    362754.877  393226.432  421796.659  355393.912  332615.416  ...
2008    373109.027  402900.336  388986.719  338056.130  318547.343  ...
2009    347658.241  372542.226  381221.417  327400.612  307040.341  ...
2010    375759.478  409725.440  408884.155  346045.172  307920.691  ...
2011    367727.015  418692.755  406511.315  337931.318  308698.504  ...
2012    360826.151  414639.671  395699.566  334584.877  311650.774  ...
2013    356822.647  394845.621  385285.745  340940.902  314925.463  ...
2014    357844.043  385779.552  384341.148  339886.506  314521.999  ...
2015    362409.202  400418.853  392116.203  350121.648  312111.680  ...
2016    367781.196  411886.942  409700.812  351484.468  312945.164  ...
2017    358522.007  404432.474  384738.580  335914.910  318669.649  ...
2018    371885.761  411290.320  408027.757  356258.302  324931.943  ...
2019    352988.074  410037.810  401429.694  360518.468  320351.885  ...
2020    351744.930  409561.700  398279.697  333258.048  313531.271  ...
2021    373754.405  404748.717  413353.176  348200.651  319638.396  ...
2022           NaN         NaN         NaN         NaN         NaN  ...

source  renewable                                                         \
month          3          4          5          6          7          8
year
1973    26045.257  24552.309  25273.326  24240.615  22884.694  21578.636
1974    28053.082  28346.187  28453.726  27097.194  26735.794  24474.015
1975    28480.561  27133.136  28268.477  27734.136  26075.189  23170.172
1976    27201.037  24748.570  26110.084  26158.453  26659.362  24413.543
1977    20436.963  19225.473  19282.856  17805.593  17364.344  17266.370
1978    25161.617  25788.224  29256.131  25619.274  24968.745  22744.596
1979    26608.010  26029.779  29629.392  25619.443  23392.849  21914.771
1980    25013.631  26455.027  29665.334  28420.038  25225.145  21184.607
1981    21393.690  21519.438  24896.566  27161.385  25937.479  22371.409
1982    30495.266  28552.739  28684.615  28729.295  28060.188  24610.375
1983    31037.573  30709.732  31882.370  31473.524  28959.589  26801.321
1984    31434.051  30961.957  32819.440  29745.637  28424.295  26167.086
1985    25850.124  25482.422  27569.849  24945.752  22459.120  21151.129
1986    29729.505  28710.832  28440.455  27515.672  25398.166  22483.632
1987    24562.927  23287.172  25546.673  22252.261  21578.831  19783.505
1988    20835.409  20359.579  22493.063  20156.057  18268.892  17747.021
1989    27761.137  28808.607  32621.442  30678.854  27670.139  25421.615
1990    34828.779  31732.310  32871.153  32997.759  29496.012  27436.640
1991    31844.584  31033.293  34484.794  31800.550  30056.089  28712.427
1992    27999.393  25380.240  27677.794  29267.757  26672.614  25574.923
1993    31930.748  32283.431  35573.202  32596.186  29951.968  27222.600
1994    30186.453  30572.712  30800.985  30105.325  29936.896  26374.394
1995    33754.542  30558.997  32667.449  35157.625  34457.327  32178.920
1996    39565.711  36497.549  38292.055  38017.707  36317.861  33630.210
1997    40712.864  38323.973  40956.937  40111.762  38208.348  33668.706
1998    37954.135  34045.670  38647.879  36417.367  34869.031  31445.370
1999    37380.334  33453.790  36174.055  36403.530  36335.047  31874.173
2000    33200.063  35068.774  33954.613  30817.602  30702.559  28462.447
2001    25499.065  23043.770  24291.245  25918.383  23452.814  24492.409
2002    26678.710  30204.788  32883.433  34415.516  31529.231  27193.340
2003    30143.422  30887.070  35271.056  34502.096  31107.035  28956.093
2004    29261.554  27114.370  30670.154  31632.078  29891.889  27800.605
2005    29807.860  29921.811  34355.997  34004.470  32896.820  28178.683
2006    32388.490  35828.296  38409.736  37116.575  32923.071  28927.413
2007    32483.761  32209.740  34121.009  30842.830  30254.305  28184.553
2008    31819.053  33073.233  37734.119  39950.646  35089.216  30095.762
2009    34462.001  38483.532  41075.300  40474.468  34080.568  30758.784
2010    35214.695  34368.614  39269.294  43591.310  37066.804  32619.031
2011    47435.791  48853.949  49807.917  48868.248  44577.418  39124.787
2012    45828.117  44592.247  47169.856  44621.589  41597.086  37835.099
2013    42882.331  48765.761  51370.317  47980.078  45506.910  38550.712
2014    49686.405  51537.603  49765.439  49554.961  44856.931  37987.699
2015    47814.907  48750.922  45937.412  42576.926  43955.301  41317.620
2016    58089.881  55092.596  53876.725  48975.925  49043.898  43132.802
2017    66027.418  65484.645  67376.721  62782.187  54427.234  47581.462
2018    63626.543  66241.346  67322.238  65772.266  54525.608  54565.891
2019    63860.077  68955.286  70511.306  64177.848  60977.064  56421.730
2020    65420.145  66322.848  73510.051  72920.106  65425.812  60887.218
2021    76624.292  71541.439  74236.846  68244.802  61085.897  65121.239
2022    86739.642  85004.357        NaN        NaN        NaN        NaN

source
month          9          10         11         12
year
1973    17480.982  18661.753  20446.638  26674.160
1974    21794.475  20413.638  21576.359  23568.166
1975    21039.506  23223.672  25002.478  26578.416
1976    20897.571  21623.302  20357.866  20818.147
1977    16999.677  17792.227  21033.467  23415.655
1978    21725.694  19947.472  20450.822  22662.299
1979    19555.501  20793.550  23016.992  23450.383
1980    19173.210  18605.275  19959.082  23031.770
1981    18572.955  18825.826  19649.741  24571.374
1982    20576.777  20465.608  24037.895  28410.580
1983    22602.813  21664.692  25536.461  32455.752
1984    21851.936  21911.040  23307.830  26961.539
1985    19867.121  21102.722  24206.379  26707.559
1986    22221.906  22413.363  24156.389  27222.208
1987    19404.348  19175.907  18061.373  22336.027
1988    17484.716  16331.662  19672.899  21129.235
1989    24087.527  25411.036  26590.750  27212.986
1990    23098.894  24766.087  25809.528  30447.023
1991    25711.324  24385.390  25179.259  29253.126
1992    23938.070  23798.983  26660.055  31527.586
1993    24361.909  24366.667  25709.171  28920.301
1994    22193.363  24248.402  25657.207  28593.727
1995    26522.622  30280.790  32125.433  35126.135
1996    28281.778  30049.380  30383.764  36450.551
1997    29231.105  31956.575  29634.547  31535.308
1998    27450.052  25770.058  25454.783  32718.519
1999    27043.516  25549.099  27482.290  30895.383
2000    23358.549  23891.357  26125.954  25343.866
2001    20097.295  20669.729  20314.962  24761.946
2002    22892.180  23049.535  25313.337  27485.909
2003    24248.269  24361.051  25550.490  30450.654
2004    26452.188  25010.362  26763.898  32585.291
2005    23977.444  24577.195  26120.574  29218.983
2006    24292.914  24842.875  28023.545  29433.155
2007    22841.729  23397.767  24049.086  27329.076
2008    24584.489  25620.068  25961.225  32753.622
2009    27535.090  31974.019  33488.244  37406.982
2010    30071.332  31036.353  34876.844  37997.858
2011    33842.048  35736.646  38812.204  40408.541
2012    32574.498  35347.292  36540.606  43809.058
2013    35513.919  37883.538  40294.260  42333.508
2014    35425.809  39430.053  44901.356  44470.386
2015    38197.460  40895.098  47117.376  51486.763
2016    42181.713  46527.055  47020.477  54357.769
2017    47842.690  52498.813  51769.453  53838.024
2018    49241.161  51451.998  53647.218  56340.436
2019    55293.288  57428.569  54903.006  57216.976
2020    54737.452  59910.591  65222.203  64343.520
2021    63258.203  65065.088  69649.783  78475.696
2022          NaN        NaN        NaN        NaN

[50 rows x 36 columns]

In [55]:
stacked4.unstack(level=[1,2])

source       Total                                                  \
month           1           2           3           4           5
year
1973    160217.989  143538.699  148158.370  139589.440  147395.124
1974    157554.691  142748.458  150342.206  142311.633  153812.873
1975    164623.080  147349.000  155760.211  146494.879  153531.080
1976    178608.612  156965.799  164466.676  153467.392  157664.467
1977    196665.182  162949.088  169437.171  157117.355  169596.403
1978    198107.635  173745.731  173460.887  160012.982  175548.628
1979    209986.749  186587.309  183154.004  170260.472  178409.356
1980    200296.330  188961.379  187744.800  169016.585  176066.486
1981    206758.205  179859.910  185833.882  172841.342  178138.553
1982    209694.373  180545.573  187967.965  172876.502  177479.981
1983    195870.844  172725.190  182768.722  170668.876  174724.813
1984    216923.729  189810.043  200387.475  181381.139  192550.198
1985    228147.888  198488.497  195250.388  185173.312  197122.843
1986    217761.136  192582.016  197114.555  186370.454  197647.498
1987    223040.975  194280.625  202129.944  189792.417  206406.878
1988    238188.434  217183.084  214293.615  196297.111  208703.604
1989    246766.176  233782.777  241946.410  222868.586  234824.770
1990    255187.021  229499.204  244761.483  229769.727  241773.529
1991    269214.313  228290.131  240561.216  227798.971  254873.018
1992    267772.670  239514.031  247733.163  233405.563  242411.928
1993    271020.902  248015.328  261247.551  234695.127  244325.583
1994    289768.406  249172.290  257998.052  240636.581  252744.936
1995    279773.101  252307.149  261342.562  244735.923  264288.242
1996    296922.971  270685.247  275019.018  251612.875  282266.414
1997    300573.901  258131.029  272258.227  258284.482  272913.783
1998    295260.404  260589.918  286877.989  261229.604  299639.908
1999    315813.690  274820.273  298144.718  280719.013  300098.190
2000    327993.944  294169.282  301579.821  285577.749  322953.681
2001    332493.160  282940.198  300706.544  278078.871  300491.621
2002    319941.472  281825.708  302549.007  289848.252  307674.569
2003    341988.899  299248.775  304317.263  285755.700  307544.887
2004    346545.627  314279.910  308812.096  290559.914  327380.264
2005    343121.453  298500.316  317458.276  289562.400  315062.110
2006    328657.739  307333.430  318729.800  297858.078  330615.570
2007    353531.095  323230.395  320471.243  303129.064  330202.758
2008    362998.429  325105.597  324629.850  305865.031  325244.802
2009    354992.636  300887.398  310602.964  289537.255  311305.872
2010    360957.167  319734.727  312167.640  287800.227  327936.492
2011    362871.893  313126.607  318709.941  302400.724  323628.238
2012    339528.259  309389.420  309090.569  295228.216  336517.631
2013    348967.378  309728.080  325398.834  299332.868  322155.640
2014    377254.711  324348.436  331823.059  297630.588  324724.300
2015    360455.167  334475.546  324191.894  294133.343  322086.912
2016    352719.066  313685.401  304389.581  292893.550  316784.457
2017    344332.034  291049.672  319335.755  295360.591  323446.738
2018    373230.280  306894.214  321546.954  300756.440  338947.606
2019    359509.234  315026.484  326657.208  296662.569  330423.048
2020    341850.206  319550.114  309586.723  279583.265  304593.238
2021    350795.813  326223.389  312284.622  292503.539  318858.513
2022    378966.702  327766.846  325952.002  304348.709         NaN

source                                                              ...  \
month           6           7           8           9           10  ...
year                                                                ...
1973    161243.674  173733.007  177365.364  156875.032  154197.466  ...
1974    156440.089  178247.304  174119.001  152467.442  152195.832  ...
1975    162716.960  177056.505  179930.892  155440.826  155187.742  ...
1976    173673.719  186691.040  186638.696  165237.437  164009.445  ...
1977    181031.212  199167.726  196363.166  176497.560  166645.282  ...
1978    188585.386  202947.293  206658.749  185802.058  176013.116  ...
1979    186976.379  202522.477  205100.592  180974.646  179953.363  ...
1980    189748.486  217057.853  215629.382  191697.740  178761.034  ...
1981    203020.751  220654.747  210639.415  187051.489  181557.590  ...
1982    186447.119  210865.079  205891.676  180875.268  173172.248  ...
1983    191367.206  220446.836  230193.460  195817.014  183136.711  ...
1984    209967.314  221526.162  229531.666  195411.388  191142.430  ...
1985    205681.971  227003.762  226286.447  202712.422  194995.217  ...
1986    215334.156  242953.552  225402.481  206905.101  197959.776  ...
1987    225907.915  248196.221  247880.760  213221.249  203214.924  ...
1988    233065.853  257742.125  267928.593  220392.242  210813.885  ...
1989    250919.110  273457.735  275419.519  242793.798  235669.018  ...
1990    268992.258  287447.762  290655.259  258356.632  244372.250  ...
1991    269099.254  294647.834  292158.580  256027.328  245378.242  ...
1992    261076.926  293616.745  281927.430  259925.035  244993.925  ...
1993    275359.600  312224.835  311450.190  264032.481  250552.792  ...
1994    294161.782  311256.823  307604.584  266262.327  256528.490  ...
1995    286258.135  330416.095  345780.079  277575.357  263978.440  ...
1996    302716.899  327708.462  329286.330  283151.263  271446.494  ...
1997    299091.561  344516.455  332898.630  301056.672  284970.629  ...
1998    328903.002  361936.460  357365.610  318924.466  284445.547  ...
1999    328923.833  376538.308  364031.383  305515.654  283934.839  ...
2000    339053.660  356527.917  368669.365  312446.647  289451.903  ...
2001    327693.978  357613.700  370532.828  306928.866  294733.613  ...
2002    341023.145  381542.109  374585.823  331279.434  307059.462  ...
2003    328693.699  374396.049  381816.318  323135.536  306740.934  ...
2004    345085.079  377331.697  368439.037  335622.198  312450.223  ...
2005    363671.636  402273.846  404940.681  350217.801  316397.924  ...
2006    364259.798  410420.793  407762.536  332055.321  321567.091  ...
2007    362754.877  393226.432  421796.659  355393.912  332615.416  ...
2008    373109.027  402900.336  388986.719  338056.130  318547.343  ...
2009    347658.241  372542.226  381221.417  327400.612  307040.341  ...
2010    375759.478  409725.440  408884.155  346045.172  307920.691  ...
2011    367727.015  418692.755  406511.315  337931.318  308698.504  ...
2012    360826.151  414639.671  395699.566  334584.877  311650.774  ...
2013    356822.647  394845.621  385285.745  340940.902  314925.463  ...
2014    357844.043  385779.552  384341.148  339886.506  314521.999  ...
2015    362409.202  400418.853  392116.203  350121.648  312111.680  ...
2016    367781.196  411886.942  409700.812  351484.468  312945.164  ...
2017    358522.007  404432.474  384738.580  335914.910  318669.649  ...
2018    371885.761  411290.320  408027.757  356258.302  324931.943  ...
2019    352988.074  410037.810  401429.694  360518.468  320351.885  ...
2020    351744.930  409561.700  398279.697  333258.048  313531.271  ...
2021    373754.405  404748.717  413353.176  348200.651  319638.396  ...
2022           NaN         NaN         NaN         NaN         NaN  ...

source  renewable                                                         \
month          3          4          5          6          7          8
year
1973    26045.257  24552.309  25273.326  24240.615  22884.694  21578.636
1974    28053.082  28346.187  28453.726  27097.194  26735.794  24474.015
1975    28480.561  27133.136  28268.477  27734.136  26075.189  23170.172
1976    27201.037  24748.570  26110.084  26158.453  26659.362  24413.543
1977    20436.963  19225.473  19282.856  17805.593  17364.344  17266.370
1978    25161.617  25788.224  29256.131  25619.274  24968.745  22744.596
1979    26608.010  26029.779  29629.392  25619.443  23392.849  21914.771
1980    25013.631  26455.027  29665.334  28420.038  25225.145  21184.607
1981    21393.690  21519.438  24896.566  27161.385  25937.479  22371.409
1982    30495.266  28552.739  28684.615  28729.295  28060.188  24610.375
1983    31037.573  30709.732  31882.370  31473.524  28959.589  26801.321
1984    31434.051  30961.957  32819.440  29745.637  28424.295  26167.086
1985    25850.124  25482.422  27569.849  24945.752  22459.120  21151.129
1986    29729.505  28710.832  28440.455  27515.672  25398.166  22483.632
1987    24562.927  23287.172  25546.673  22252.261  21578.831  19783.505
1988    20835.409  20359.579  22493.063  20156.057  18268.892  17747.021
1989    27761.137  28808.607  32621.442  30678.854  27670.139  25421.615
1990    34828.779  31732.310  32871.153  32997.759  29496.012  27436.640
1991    31844.584  31033.293  34484.794  31800.550  30056.089  28712.427
1992    27999.393  25380.240  27677.794  29267.757  26672.614  25574.923
1993    31930.748  32283.431  35573.202  32596.186  29951.968  27222.600
1994    30186.453  30572.712  30800.985  30105.325  29936.896  26374.394
1995    33754.542  30558.997  32667.449  35157.625  34457.327  32178.920
1996    39565.711  36497.549  38292.055  38017.707  36317.861  33630.210
1997    40712.864  38323.973  40956.937  40111.762  38208.348  33668.706
1998    37954.135  34045.670  38647.879  36417.367  34869.031  31445.370
1999    37380.334  33453.790  36174.055  36403.530  36335.047  31874.173
2000    33200.063  35068.774  33954.613  30817.602  30702.559  28462.447
2001    25499.065  23043.770  24291.245  25918.383  23452.814  24492.409
2002    26678.710  30204.788  32883.433  34415.516  31529.231  27193.340
2003    30143.422  30887.070  35271.056  34502.096  31107.035  28956.093
2004    29261.554  27114.370  30670.154  31632.078  29891.889  27800.605
2005    29807.860  29921.811  34355.997  34004.470  32896.820  28178.683
2006    32388.490  35828.296  38409.736  37116.575  32923.071  28927.413
2007    32483.761  32209.740  34121.009  30842.830  30254.305  28184.553
2008    31819.053  33073.233  37734.119  39950.646  35089.216  30095.762
2009    34462.001  38483.532  41075.300  40474.468  34080.568  30758.784
2010    35214.695  34368.614  39269.294  43591.310  37066.804  32619.031
2011    47435.791  48853.949  49807.917  48868.248  44577.418  39124.787
2012    45828.117  44592.247  47169.856  44621.589  41597.086  37835.099
2013    42882.331  48765.761  51370.317  47980.078  45506.910  38550.712
2014    49686.405  51537.603  49765.439  49554.961  44856.931  37987.699
2015    47814.907  48750.922  45937.412  42576.926  43955.301  41317.620
2016    58089.881  55092.596  53876.725  48975.925  49043.898  43132.802
2017    66027.418  65484.645  67376.721  62782.187  54427.234  47581.462
2018    63626.543  66241.346  67322.238  65772.266  54525.608  54565.891
2019    63860.077  68955.286  70511.306  64177.848  60977.064  56421.730
2020    65420.145  66322.848  73510.051  72920.106  65425.812  60887.218
2021    76624.292  71541.439  74236.846  68244.802  61085.897  65121.239
2022    86739.642  85004.357        NaN        NaN        NaN        NaN

source
month          9          10         11         12
year
1973    17480.982  18661.753  20446.638  26674.160
1974    21794.475  20413.638  21576.359  23568.166
1975    21039.506  23223.672  25002.478  26578.416
1976    20897.571  21623.302  20357.866  20818.147
1977    16999.677  17792.227  21033.467  23415.655
1978    21725.694  19947.472  20450.822  22662.299
1979    19555.501  20793.550  23016.992  23450.383
1980    19173.210  18605.275  19959.082  23031.770
1981    18572.955  18825.826  19649.741  24571.374
1982    20576.777  20465.608  24037.895  28410.580
1983    22602.813  21664.692  25536.461  32455.752
1984    21851.936  21911.040  23307.830  26961.539
1985    19867.121  21102.722  24206.379  26707.559
1986    22221.906  22413.363  24156.389  27222.208
1987    19404.348  19175.907  18061.373  22336.027
1988    17484.716  16331.662  19672.899  21129.235
1989    24087.527  25411.036  26590.750  27212.986
1990    23098.894  24766.087  25809.528  30447.023
1991    25711.324  24385.390  25179.259  29253.126
1992    23938.070  23798.983  26660.055  31527.586
1993    24361.909  24366.667  25709.171  28920.301
1994    22193.363  24248.402  25657.207  28593.727
1995    26522.622  30280.790  32125.433  35126.135
1996    28281.778  30049.380  30383.764  36450.551
1997    29231.105  31956.575  29634.547  31535.308
1998    27450.052  25770.058  25454.783  32718.519
1999    27043.516  25549.099  27482.290  30895.383
2000    23358.549  23891.357  26125.954  25343.866
2001    20097.295  20669.729  20314.962  24761.946
2002    22892.180  23049.535  25313.337  27485.909
2003    24248.269  24361.051  25550.490  30450.654
2004    26452.188  25010.362  26763.898  32585.291
2005    23977.444  24577.195  26120.574  29218.983
2006    24292.914  24842.875  28023.545  29433.155
2007    22841.729  23397.767  24049.086  27329.076
2008    24584.489  25620.068  25961.225  32753.622
2009    27535.090  31974.019  33488.244  37406.982
2010    30071.332  31036.353  34876.844  37997.858
2011    33842.048  35736.646  38812.204  40408.541
2012    32574.498  35347.292  36540.606  43809.058
2013    35513.919  37883.538  40294.260  42333.508
2014    35425.809  39430.053  44901.356  44470.386
2015    38197.460  40895.098  47117.376  51486.763
2016    42181.713  46527.055  47020.477  54357.769
2017    47842.690  52498.813  51769.453  53838.024
2018    49241.161  51451.998  53647.218  56340.436
2019    55293.288  57428.569  54903.006  57216.976
2020    54737.452  59910.591  65222.203  64343.520
2021    63258.203  65065.088  69649.783  78475.696
2022          NaN        NaN        NaN        NaN

[50 rows x 36 columns]

### 3.Reshaping by melt

In [56]:
df3 =df2
# df20=df3[:10]
# df20
df3

          Total  month  year  non-renewable  renewable
0    160217.989      1  1973     133804.986  26413.002
1    143538.699      2  1973     120065.492  23473.208
2    148158.370      3  1973     122113.112  26045.257
3    139589.440      4  1973     115037.131  24552.309
4    147395.124      5  1973     122121.797  25273.326
..          ...    ...   ...            ...        ...
587  339684.017     12  2021     260132.691  78475.696
588  378966.702      1  2022     299155.908  78793.520
589  327766.846      2  2022     250675.859  76200.267
590  325952.002      3  2022     238240.679  86739.642
591  304348.709      4  2022     218421.044  85004.357

[592 rows x 5 columns]

In [57]:
df3.dtypes

Total            float64
month              int64
year               int64
non-renewable    float64
renewable        float64
dtype: object

In [58]:
df3.melt(id_vars=['month','year'],var_name="source",value_name="Net_elec_generation")

      month  year     source  Net_elec_generation
0         1  1973      Total           160217.989
1         2  1973      Total           143538.699
2         3  1973      Total           148158.370
3         4  1973      Total           139589.440
4         5  1973      Total           147395.124
...     ...   ...        ...                  ...
1771     12  2021  renewable            78475.696
1772      1  2022  renewable            78793.520
1773      2  2022  renewable            76200.267
1774      3  2022  renewable            86739.642
1775      4  2022  renewable            85004.357

[1776 rows x 4 columns]

In [59]:
# df20.melt(id_vars=['month','year'],var_name="source",value_name="Net_elec_generation")

In [60]:
# df20.melt(id_vars=['month','year'],var_name="source",value_name="Net_elec_generation",ignore_index=False)

In [61]:
df3.melt(id_vars=['month','year'],var_name="source",value_name="Net_elec_generation",ignore_index=False)
#after every 591 index is repeated from 0

     month  year     source  Net_elec_generation
0        1  1973      Total           160217.989
1        2  1973      Total           143538.699
2        3  1973      Total           148158.370
3        4  1973      Total           139589.440
4        5  1973      Total           147395.124
..     ...   ...        ...                  ...
587     12  2021  renewable            78475.696
588      1  2022  renewable            78793.520
589      2  2022  renewable            76200.267
590      3  2022  renewable            86739.642
591      4  2022  renewable            85004.357

[1776 rows x 4 columns]

In [62]:
# df3['id'] = df3.index
df3

          Total  month  year  non-renewable  renewable
0    160217.989      1  1973     133804.986  26413.002
1    143538.699      2  1973     120065.492  23473.208
2    148158.370      3  1973     122113.112  26045.257
3    139589.440      4  1973     115037.131  24552.309
4    147395.124      5  1973     122121.797  25273.326
..          ...    ...   ...            ...        ...
587  339684.017     12  2021     260132.691  78475.696
588  378966.702      1  2022     299155.908  78793.520
589  327766.846      2  2022     250675.859  76200.267
590  325952.002      3  2022     238240.679  86739.642
591  304348.709      4  2022     218421.044  85004.357

[592 rows x 5 columns]

In [63]:
# pd.wide_to_long(df3, ["month", "Total"], i="id", j="year")

### 4.Combining with stats and GroupBy

In [64]:
df4=df2

In [65]:
pivot3

            Total                                                              \
month          1           2           3           4           5           6
year
1973   160217.989  143538.699  148158.370  139589.440  147395.124  161243.674
1974   157554.691  142748.458  150342.206  142311.633  153812.873  156440.089
1975   164623.080  147349.000  155760.211  146494.879  153531.080  162716.960
1976   178608.612  156965.799  164466.676  153467.392  157664.467  173673.719
1977   196665.182  162949.088  169437.171  157117.355  169596.403  181031.212
1978   198107.635  173745.731  173460.887  160012.982  175548.628  188585.386
1979   209986.749  186587.309  183154.004  170260.472  178409.356  186976.379
1980   200296.330  188961.379  187744.800  169016.585  176066.486  189748.486
1981   206758.205  179859.910  185833.882  172841.342  178138.553  203020.751
1982   209694.373  180545.573  187967.965  172876.502  177479.981  186447.119
1983   195870.844  172725.190  182768.722  170668.876  174724.813  191367.206
1984   216923.729  189810.043  200387.475  181381.139  192550.198  209967.314
1985   228147.888  198488.497  195250.388  185173.312  197122.843  205681.971
1986   217761.136  192582.016  197114.555  186370.454  197647.498  215334.156
1987   223040.975  194280.625  202129.944  189792.417  206406.878  225907.915
1988   238188.434  217183.084  214293.615  196297.111  208703.604  233065.853
1989   246766.176  233782.777  241946.410  222868.586  234824.770  250919.110
1990   255187.021  229499.204  244761.483  229769.727  241773.529  268992.258
1991   269214.313  228290.131  240561.216  227798.971  254873.018  269099.254
1992   267772.670  239514.031  247733.163  233405.563  242411.928  261076.926
1993   271020.902  248015.328  261247.551  234695.127  244325.583  275359.600
1994   289768.406  249172.290  257998.052  240636.581  252744.936  294161.782
1995   279773.101  252307.149  261342.562  244735.923  264288.242  286258.135
1996   296922.971  270685.247  275019.018  251612.875  282266.414  302716.899
1997   300573.901  258131.029  272258.227  258284.482  272913.783  299091.561
1998   295260.404  260589.918  286877.989  261229.604  299639.908  328903.002
1999   315813.690  274820.273  298144.718  280719.013  300098.190  328923.833
2000   327993.944  294169.282  301579.821  285577.749  322953.681  339053.660
2001   332493.160  282940.198  300706.544  278078.871  300491.621  327693.978
2002   319941.472  281825.708  302549.007  289848.252  307674.569  341023.145
2003   341988.899  299248.775  304317.263  285755.700  307544.887  328693.699
2004   346545.627  314279.910  308812.096  290559.914  327380.264  345085.079
2005   343121.453  298500.316  317458.276  289562.400  315062.110  363671.636
2006   328657.739  307333.430  318729.800  297858.078  330615.570  364259.798
2007   353531.095  323230.395  320471.243  303129.064  330202.758  362754.877
2008   362998.429  325105.597  324629.850  305865.031  325244.802  373109.027
2009   354992.636  300887.398  310602.964  289537.255  311305.872  347658.241
2010   360957.167  319734.727  312167.640  287800.227  327936.492  375759.478
2011   362871.893  313126.607  318709.941  302400.724  323628.238  367727.015
2012   339528.259  309389.420  309090.569  295228.216  336517.631  360826.151
2013   348967.378  309728.080  325398.834  299332.868  322155.640  356822.647
2014   377254.711  324348.436  331823.059  297630.588  324724.300  357844.043
2015   360455.167  334475.546  324191.894  294133.343  322086.912  362409.202
2016   352719.066  313685.401  304389.581  292893.550  316784.457  367781.196
2017   344332.034  291049.672  319335.755  295360.591  323446.738  358522.007
2018   373230.280  306894.214  321546.954  300756.440  338947.606  371885.761
2019   359509.234  315026.484  326657.208  296662.569  330423.048  352988.074
2020   341850.206  319550.114  309586.723  279583.265  304593.238  351744.930
2021   350795.813  326223.389  312284.622  292503.539  318858.513  373754.405
2022   378966.702  327766.846  325952.002  304348.709         NaN         NaN

                                                       ...  renewable  \
month          7           8           9           10  ...         3
year                                                   ...
1973   173733.007  177365.364  156875.032  154197.466  ...  26045.257
1974   178247.304  174119.001  152467.442  152195.832  ...  28053.082
1975   177056.505  179930.892  155440.826  155187.742  ...  28480.561
1976   186691.040  186638.696  165237.437  164009.445  ...  27201.037
1977   199167.726  196363.166  176497.560  166645.282  ...  20436.963
1978   202947.293  206658.749  185802.058  176013.116  ...  25161.617
1979   202522.477  205100.592  180974.646  179953.363  ...  26608.010
1980   217057.853  215629.382  191697.740  178761.034  ...  25013.631
1981   220654.747  210639.415  187051.489  181557.590  ...  21393.690
1982   210865.079  205891.676  180875.268  173172.248  ...  30495.266
1983   220446.836  230193.460  195817.014  183136.711  ...  31037.573
1984   221526.162  229531.666  195411.388  191142.430  ...  31434.051
1985   227003.762  226286.447  202712.422  194995.217  ...  25850.124
1986   242953.552  225402.481  206905.101  197959.776  ...  29729.505
1987   248196.221  247880.760  213221.249  203214.924  ...  24562.927
1988   257742.125  267928.593  220392.242  210813.885  ...  20835.409
1989   273457.735  275419.519  242793.798  235669.018  ...  27761.137
1990   287447.762  290655.259  258356.632  244372.250  ...  34828.779
1991   294647.834  292158.580  256027.328  245378.242  ...  31844.584
1992   293616.745  281927.430  259925.035  244993.925  ...  27999.393
1993   312224.835  311450.190  264032.481  250552.792  ...  31930.748
1994   311256.823  307604.584  266262.327  256528.490  ...  30186.453
1995   330416.095  345780.079  277575.357  263978.440  ...  33754.542
1996   327708.462  329286.330  283151.263  271446.494  ...  39565.711
1997   344516.455  332898.630  301056.672  284970.629  ...  40712.864
1998   361936.460  357365.610  318924.466  284445.547  ...  37954.135
1999   376538.308  364031.383  305515.654  283934.839  ...  37380.334
2000   356527.917  368669.365  312446.647  289451.903  ...  33200.063
2001   357613.700  370532.828  306928.866  294733.613  ...  25499.065
2002   381542.109  374585.823  331279.434  307059.462  ...  26678.710
2003   374396.049  381816.318  323135.536  306740.934  ...  30143.422
2004   377331.697  368439.037  335622.198  312450.223  ...  29261.554
2005   402273.846  404940.681  350217.801  316397.924  ...  29807.860
2006   410420.793  407762.536  332055.321  321567.091  ...  32388.490
2007   393226.432  421796.659  355393.912  332615.416  ...  32483.761
2008   402900.336  388986.719  338056.130  318547.343  ...  31819.053
2009   372542.226  381221.417  327400.612  307040.341  ...  34462.001
2010   409725.440  408884.155  346045.172  307920.691  ...  35214.695
2011   418692.755  406511.315  337931.318  308698.504  ...  47435.791
2012   414639.671  395699.566  334584.877  311650.774  ...  45828.117
2013   394845.621  385285.745  340940.902  314925.463  ...  42882.331
2014   385779.552  384341.148  339886.506  314521.999  ...  49686.405
2015   400418.853  392116.203  350121.648  312111.680  ...  47814.907
2016   411886.942  409700.812  351484.468  312945.164  ...  58089.881
2017   404432.474  384738.580  335914.910  318669.649  ...  66027.418
2018   411290.320  408027.757  356258.302  324931.943  ...  63626.543
2019   410037.810  401429.694  360518.468  320351.885  ...  63860.077
2020   409561.700  398279.697  333258.048  313531.271  ...  65420.145
2021   404748.717  413353.176  348200.651  319638.396  ...  76624.292
2022          NaN         NaN         NaN         NaN  ...  86739.642

                                                                         \
month         4          5          6          7          8          9
year
1973   24552.309  25273.326  24240.615  22884.694  21578.636  17480.982
1974   28346.187  28453.726  27097.194  26735.794  24474.015  21794.475
1975   27133.136  28268.477  27734.136  26075.189  23170.172  21039.506
1976   24748.570  26110.084  26158.453  26659.362  24413.543  20897.571
1977   19225.473  19282.856  17805.593  17364.344  17266.370  16999.677
1978   25788.224  29256.131  25619.274  24968.745  22744.596  21725.694
1979   26029.779  29629.392  25619.443  23392.849  21914.771  19555.501
1980   26455.027  29665.334  28420.038  25225.145  21184.607  19173.210
1981   21519.438  24896.566  27161.385  25937.479  22371.409  18572.955
1982   28552.739  28684.615  28729.295  28060.188  24610.375  20576.777
1983   30709.732  31882.370  31473.524  28959.589  26801.321  22602.813
1984   30961.957  32819.440  29745.637  28424.295  26167.086  21851.936
1985   25482.422  27569.849  24945.752  22459.120  21151.129  19867.121
1986   28710.832  28440.455  27515.672  25398.166  22483.632  22221.906
1987   23287.172  25546.673  22252.261  21578.831  19783.505  19404.348
1988   20359.579  22493.063  20156.057  18268.892  17747.021  17484.716
1989   28808.607  32621.442  30678.854  27670.139  25421.615  24087.527
1990   31732.310  32871.153  32997.759  29496.012  27436.640  23098.894
1991   31033.293  34484.794  31800.550  30056.089  28712.427  25711.324
1992   25380.240  27677.794  29267.757  26672.614  25574.923  23938.070
1993   32283.431  35573.202  32596.186  29951.968  27222.600  24361.909
1994   30572.712  30800.985  30105.325  29936.896  26374.394  22193.363
1995   30558.997  32667.449  35157.625  34457.327  32178.920  26522.622
1996   36497.549  38292.055  38017.707  36317.861  33630.210  28281.778
1997   38323.973  40956.937  40111.762  38208.348  33668.706  29231.105
1998   34045.670  38647.879  36417.367  34869.031  31445.370  27450.052
1999   33453.790  36174.055  36403.530  36335.047  31874.173  27043.516
2000   35068.774  33954.613  30817.602  30702.559  28462.447  23358.549
2001   23043.770  24291.245  25918.383  23452.814  24492.409  20097.295
2002   30204.788  32883.433  34415.516  31529.231  27193.340  22892.180
2003   30887.070  35271.056  34502.096  31107.035  28956.093  24248.269
2004   27114.370  30670.154  31632.078  29891.889  27800.605  26452.188
2005   29921.811  34355.997  34004.470  32896.820  28178.683  23977.444
2006   35828.296  38409.736  37116.575  32923.071  28927.413  24292.914
2007   32209.740  34121.009  30842.830  30254.305  28184.553  22841.729
2008   33073.233  37734.119  39950.646  35089.216  30095.762  24584.489
2009   38483.532  41075.300  40474.468  34080.568  30758.784  27535.090
2010   34368.614  39269.294  43591.310  37066.804  32619.031  30071.332
2011   48853.949  49807.917  48868.248  44577.418  39124.787  33842.048
2012   44592.247  47169.856  44621.589  41597.086  37835.099  32574.498
2013   48765.761  51370.317  47980.078  45506.910  38550.712  35513.919
2014   51537.603  49765.439  49554.961  44856.931  37987.699  35425.809
2015   48750.922  45937.412  42576.926  43955.301  41317.620  38197.460
2016   55092.596  53876.725  48975.925  49043.898  43132.802  42181.713
2017   65484.645  67376.721  62782.187  54427.234  47581.462  47842.690
2018   66241.346  67322.238  65772.266  54525.608  54565.891  49241.161
2019   68955.286  70511.306  64177.848  60977.064  56421.730  55293.288
2020   66322.848  73510.051  72920.106  65425.812  60887.218  54737.452
2021   71541.439  74236.846  68244.802  61085.897  65121.239  63258.203
2022   85004.357        NaN        NaN        NaN        NaN        NaN


month         10         11         12
year
1973   18661.753  20446.638  26674.160
1974   20413.638  21576.359  23568.166
1975   23223.672  25002.478  26578.416
1976   21623.302  20357.866  20818.147
1977   17792.227  21033.467  23415.655
1978   19947.472  20450.822  22662.299
1979   20793.550  23016.992  23450.383
1980   18605.275  19959.082  23031.770
1981   18825.826  19649.741  24571.374
1982   20465.608  24037.895  28410.580
1983   21664.692  25536.461  32455.752
1984   21911.040  23307.830  26961.539
1985   21102.722  24206.379  26707.559
1986   22413.363  24156.389  27222.208
1987   19175.907  18061.373  22336.027
1988   16331.662  19672.899  21129.235
1989   25411.036  26590.750  27212.986
1990   24766.087  25809.528  30447.023
1991   24385.390  25179.259  29253.126
1992   23798.983  26660.055  31527.586
1993   24366.667  25709.171  28920.301
1994   24248.402  25657.207  28593.727
1995   30280.790  32125.433  35126.135
1996   30049.380  30383.764  36450.551
1997   31956.575  29634.547  31535.308
1998   25770.058  25454.783  32718.519
1999   25549.099  27482.290  30895.383
2000   23891.357  26125.954  25343.866
2001   20669.729  20314.962  24761.946
2002   23049.535  25313.337  27485.909
2003   24361.051  25550.490  30450.654
2004   25010.362  26763.898  32585.291
2005   24577.195  26120.574  29218.983
2006   24842.875  28023.545  29433.155
2007   23397.767  24049.086  27329.076
2008   25620.068  25961.225  32753.622
2009   31974.019  33488.244  37406.982
2010   31036.353  34876.844  37997.858
2011   35736.646  38812.204  40408.541
2012   35347.292  36540.606  43809.058
2013   37883.538  40294.260  42333.508
2014   39430.053  44901.356  44470.386
2015   40895.098  47117.376  51486.763
2016   46527.055  47020.477  54357.769
2017   52498.813  51769.453  53838.024
2018   51451.998  53647.218  56340.436
2019   57428.569  54903.006  57216.976
2020   59910.591  65222.203  64343.520
2021   65065.088  69649.783  78475.696
2022         NaN        NaN        NaN

[50 rows x 36 columns]

In [66]:
pivot3.stack()

                 Total  non-renewable  renewable
year month
1973 1      160217.989     133804.986  26413.002
     2      143538.699     120065.492  23473.208
     3      148158.370     122113.112  26045.257
     4      139589.440     115037.131  24552.309
     5      147395.124     122121.797  25273.326
...                ...            ...        ...
2021 12     339684.017     260132.691  78475.696
2022 1      378966.702     299155.908  78793.520
     2      327766.846     250675.859  76200.267
     3      325952.002     238240.679  86739.642
     4      304348.709     218421.044  85004.357

[592 rows x 3 columns]

In [67]:
pivot3.stack().mean(1)

year  month
1973  1        106811.992333
      2         95692.466333
      3         98772.246333
      4         93059.626667
      5         98263.415667
                   ...
2021  12       226097.468000
2022  1        252305.376667
      2        218214.324000
      3        216977.441000
      4        202591.370000
Length: 592, dtype: float64

In [68]:
pivot3.stack().mean(1).unstack()

month,1,2,3,4,5,6,7,8,9,10,11,12
year,,,,,,,,,,,,
1973,106811.992333,95692.466333,98772.246333,93059.626667,98263.415667,107495.782667,115822.005000,118243.576000,104583.355000,102798.310667,98758.405333,102403.238000
1974,105036.461000,95165.638333,100228.137333,94874.422333,102541.915667,104293.392333,118831.536333,116079.334333,101644.961667,101463.887667,100047.236667,106672.679667
1975,109748.720000,98232.667000,103840.141000,97663.252667,102354.053000,108477.973333,118037.670000,119953.928000,103627.217333,103458.495000,102023.398333,113085.530667
1976,119072.408000,104643.866333,109644.450333,102311.595000,105109.644667,115782.479667,124460.693000,124425.797000,110158.291333,109339.630333,112897.527000,122762.738000
1977,131110.121333,108632.724667,112958.114333,104744.903667,113064.269000,120687.474667,132778.484000,130908.777000,117665.039667,111096.854333,111592.048000,123059.513333
1978,132071.756667,115830.487333,115640.591000,106675.321333,117032.419000,125723.590333,135298.195333,137772.499667,123868.038667,117342.077667,117592.728333,128070.235000
1979,139991.165667,124391.539667,122102.669000,113506.981333,118939.570667,124650.919667,135014.984667,136733.728000,120649.764000,119968.909000,118513.005333,125980.113333
1980,133530.886000,125974.252667,125163.200667,112677.723333,117377.657333,126498.990667,144705.235000,143752.921667,127798.493000,119174.022667,119180.907333,130565.951333
1981,137838.803333,119906.607000,123889.254667,115227.561333,118759.035667,135347.167000,147103.164667,140426.277000,124700.992667,121038.393333,117194.502667,130550.466333
1982,139796.249000,120363.715333,125311.976667,115251.001333,118319.987333,124298.079667,140576.719333,137261.117333,120583.512000,115448.165000,115732.506000,123305.295000
1983,130580.562667,115150.126667,121845.814667,113779.250667,116483.208333,127578.137667,146964.557667,153462.306333,130544.675667,122091.140667,122113.787333,141703.555333
1984,144615.819333,126540.028000,133591.650000,120920.759333,128366.798333,139978.209000,147684.108333,153021.110000,130274.259000,127428.287000,127067.910333,133487.972000
1985,152098.592000,132325.664667,130166.925333,123448.874333,131415.229000,137121.313667,151335.841333,150857.631000,135141.614667,129996.811333,128432.634667,146326.948333
1986,145174.091000,128388.011000,131409.703333,124246.969333,131764.998667,143556.104333,161969.035000,150268.320667,137936.733667,131973.184000,131102.457333,142524.361000
1987,148693.983667,129520.416667,134753.296000,126528.278000,137604.585333,150605.276667,165464.146333,165253.839667,142147.499667,135476.616333,133652.924000,147157.580667
1988,158792.289667,144788.722333,142862.410000,130864.740667,139135.736000,155377.235333,171828.083333,178619.062333,146928.161333,140542.590000,139876.661000,155325.092333
1989,164402.358667,155757.252000,161189.182000,148474.130000,156441.421667,167174.479000,182196.731333,183504.587333,161757.604333,157004.253333,156061.612333,182857.160000
1990,170022.318667,152907.014000,163071.961000,153080.758667,161079.991333,179229.112667,191529.479667,193667.811333,172138.695000,162812.471667,154062.525333,170410.861667
1991,179342.049667,152072.245000,160239.984667,151736.149333,169781.186000,179269.671333,196297.730000,194638.227667,170555.053667,163451.335667,160977.746000,169258.263000
1992,178410.089000,159577.772333,165050.418333,155502.072333,161502.928667,173949.647333,195639.473000,187846.595667,173181.720667,163224.260333,162673.030000,178123.503667
1993,180581.878000,165254.382667,174066.311000,156367.879333,162784.998333,183477.528000,208051.166000,207534.737333,175926.115667,166936.471333,167972.553000,181344.323000
1994,193075.125000,166021.093333,171894.889333,160323.924333,168392.812000,196007.391000,207400.736000,204965.910333,177407.754000,170915.181000,167811.768667,179576.033000
1995,186399.219333,168099.828333,174112.193667,163044.848667,176075.980667,190726.323667,220161.215333,230403.871667,184937.805333,175869.445333,174206.499333,190253.073667
1996,197847.819000,180362.508000,183245.183333,167644.340333,188076.781333,201713.689667,218371.479667,219423.391333,188669.933000,180863.501333,179317.114000,189398.913000
1997,200280.343667,171994.991667,181403.227667,172090.696333,181840.265000,199295.415333,229575.380000,221830.162667,200605.488667,189878.162667,180648.251667,197468.474000
1998,196739.160667,173635.288000,191150.884000,174055.222667,199658.830000,219170.821333,241189.864667,238142.631333,212518.464000,189529.256667,177993.091667,198556.345333
1999,210428.545000,183110.624333,198649.230333,187035.768333,199951.545333,219172.315000,250911.624000,242573.673667,203566.862333,189175.977667,180620.208000,196668.910000
2000,218527.282333,195986.239667,200917.867333,190254.184667,215167.107000,225904.791667,237549.931000,245644.229000,208166.783333,192832.588333,189649.202333,212538.518000
2001,221331.550333,188336.149000,200160.644333,185066.762000,199998.991333,218136.818333,238068.411667,246672.575667,204284.640333,196147.502000,185609.164333,203313.775667
2002,212965.032000,187556.658667,201363.260333,192888.209000,204769.421333,226971.263333,253862.759333,249280.915333,220436.169000,204308.581333,197172.882333,216217.375667
2003,227637.355333,199201.444000,202527.970000,190152.976000,204672.187667,218783.002333,249146.455000,254046.695000,214980.112333,204055.591000,198166.455000,220738.389333
2004,230660.507667,209158.489000,205490.638333,193324.843333,217848.129000,229651.161000,251120.765000,245226.101667,223377.153333,207919.894333,201008.359333,227506.665333
2005,228389.392333,198683.629333,211293.575333,192713.786000,209692.586000,242085.290000,267781.656333,269520.217333,233123.449333,210615.476000,203739.634667,231702.787000
2006,218747.975667,204566.882000,212110.991000,198213.615000,220037.232667,242485.015333,273238.035333,271467.975667,221017.507000,214008.990667,205755.122000,223827.342667
2007,235346.759333,215180.563000,213308.195333,201761.999667,219793.106667,241491.950667,261801.219333,280841.212000,236597.542667,221391.842667,209079.280000,230492.436000
2008,241681.922333,216424.181000,216093.382000,203573.931667,216477.696333,248378.817000,268231.052000,258969.102000,225060.270333,212068.008667,206405.706667,228959.881333
2009,236349.639333,200300.084000,206740.793000,192695.779333,207192.237333,231426.072333,248007.851667,253792.825333,217944.687667,204371.163667,197423.181667,233333.526000
2010,240300.030333,212853.434000,207777.745333,191534.933333,218271.105667,250121.855333,272768.289000,272203.416333,230324.640667,204917.180333,203646.621333,241035.567000
2011,241557.500333,208408.868333,212079.162667,201220.193333,215348.848667,244739.408333,278692.181333,270597.483667,224910.265000,205407.147333,202339.235000,223409.124000
2012,225973.197000,205902.328667,205680.375000,196455.293000,223945.114333,240162.157000,276020.308000,263407.205667,222678.344333,207388.692000,203603.427000,222698.041667
2013,232279.064000,206145.309333,216551.487333,199213.938333,214400.577333,237506.765333,262830.054000,256451.617000,226900.090333,209555.427667,209311.993333,234967.214000
2014,251139.124000,215918.676000,220851.183333,198074.211667,216110.334333,238190.345000,256798.574000,255814.360667,226204.540333,209307.334333,211276.335333,224898.554000
2015,239930.249667,222655.323000,215777.650333,195723.638667,214329.743667,241210.420667,266514.967667,260977.341000,233020.486667,207672.970667,200036.511000,215875.388333
2016,234761.693000,208776.571667,202563.076333,194892.617000,210791.282667,244794.022000,274182.964667,272717.936667,233933.776333,208260.704333,197675.240000,229848.693667
2017,229190.610000,193702.361333,212536.799333,196557.010000,215268.270333,238648.279667,269219.422667,256086.716667,223598.632000,212102.852667,205008.409000,233228.970000
2018,248450.436667,204264.716000,213995.268667,200161.605667,225608.481000,247555.746000,273823.333667,271636.506667,237170.707667,216259.807667,214554.242000,227712.977000
2019,239274.939000,209683.340333,217412.446333,197436.713667,219909.786000,234958.320000,272972.982333,267216.225333,239964.959000,213201.234000,210205.402000,225223.404667
2020,227535.806000,212709.648667,206027.306000,186031.154000,202698.833333,234157.150000,272676.941333,265150.709000,221833.402333,208665.141333,200477.942667,229174.549000
2021,233495.559000,217175.636333,207836.153000,194682.068000,212239.820000,248835.450667,269483.455333,275223.789667,231807.593667,212765.898667,210003.960667,226097.468000
2022,252305.376667,218214.324000,216977.441000,202591.370000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
pivot3.groupby(level=1, axis=1).mean()

month,1,2,3,4,5,6,7,8,9,10,11,12
year,,,,,,,,,,,,
1973,106811.992333,95692.466333,98772.246333,93059.626667,98263.415667,107495.782667,115822.005000,118243.576000,104583.355000,102798.310667,98758.405333,102403.238000
1974,105036.461000,95165.638333,100228.137333,94874.422333,102541.915667,104293.392333,118831.536333,116079.334333,101644.961667,101463.887667,100047.236667,106672.679667
1975,109748.720000,98232.667000,103840.141000,97663.252667,102354.053000,108477.973333,118037.670000,119953.928000,103627.217333,103458.495000,102023.398333,113085.530667
1976,119072.408000,104643.866333,109644.450333,102311.595000,105109.644667,115782.479667,124460.693000,124425.797000,110158.291333,109339.630333,112897.527000,122762.738000
1977,131110.121333,108632.724667,112958.114333,104744.903667,113064.269000,120687.474667,132778.484000,130908.777000,117665.039667,111096.854333,111592.048000,123059.513333
1978,132071.756667,115830.487333,115640.591000,106675.321333,117032.419000,125723.590333,135298.195333,137772.499667,123868.038667,117342.077667,117592.728333,128070.235000
1979,139991.165667,124391.539667,122102.669000,113506.981333,118939.570667,124650.919667,135014.984667,136733.728000,120649.764000,119968.909000,118513.005333,125980.113333
1980,133530.886000,125974.252667,125163.200667,112677.723333,117377.657333,126498.990667,144705.235000,143752.921667,127798.493000,119174.022667,119180.907333,130565.951333
1981,137838.803333,119906.607000,123889.254667,115227.561333,118759.035667,135347.167000,147103.164667,140426.277000,124700.992667,121038.393333,117194.502667,130550.466333
1982,139796.249000,120363.715333,125311.976667,115251.001333,118319.987333,124298.079667,140576.719333,137261.117333,120583.512000,115448.165000,115732.506000,123305.295000
1983,130580.562667,115150.126667,121845.814667,113779.250667,116483.208333,127578.137667,146964.557667,153462.306333,130544.675667,122091.140667,122113.787333,141703.555333
1984,144615.819333,126540.028000,133591.650000,120920.759333,128366.798333,139978.209000,147684.108333,153021.110000,130274.259000,127428.287000,127067.910333,133487.972000
1985,152098.592000,132325.664667,130166.925333,123448.874333,131415.229000,137121.313667,151335.841333,150857.631000,135141.614667,129996.811333,128432.634667,146326.948333
1986,145174.091000,128388.011000,131409.703333,124246.969333,131764.998667,143556.104333,161969.035000,150268.320667,137936.733667,131973.184000,131102.457333,142524.361000
1987,148693.983667,129520.416667,134753.296000,126528.278000,137604.585333,150605.276667,165464.146333,165253.839667,142147.499667,135476.616333,133652.924000,147157.580667
1988,158792.289667,144788.722333,142862.410000,130864.740667,139135.736000,155377.235333,171828.083333,178619.062333,146928.161333,140542.590000,139876.661000,155325.092333
1989,164402.358667,155757.252000,161189.182000,148474.130000,156441.421667,167174.479000,182196.731333,183504.587333,161757.604333,157004.253333,156061.612333,182857.160000
1990,170022.318667,152907.014000,163071.961000,153080.758667,161079.991333,179229.112667,191529.479667,193667.811333,172138.695000,162812.471667,154062.525333,170410.861667
1991,179342.049667,152072.245000,160239.984667,151736.149333,169781.186000,179269.671333,196297.730000,194638.227667,170555.053667,163451.335667,160977.746000,169258.263000
1992,178410.089000,159577.772333,165050.418333,155502.072333,161502.928667,173949.647333,195639.473000,187846.595667,173181.720667,163224.260333,162673.030000,178123.503667
1993,180581.878000,165254.382667,174066.311000,156367.879333,162784.998333,183477.528000,208051.166000,207534.737333,175926.115667,166936.471333,167972.553000,181344.323000
1994,193075.125000,166021.093333,171894.889333,160323.924333,168392.812000,196007.391000,207400.736000,204965.910333,177407.754000,170915.181000,167811.768667,179576.033000
1995,186399.219333,168099.828333,174112.193667,163044.848667,176075.980667,190726.323667,220161.215333,230403.871667,184937.805333,175869.445333,174206.499333,190253.073667
1996,197847.819000,180362.508000,183245.183333,167644.340333,188076.781333,201713.689667,218371.479667,219423.391333,188669.933000,180863.501333,179317.114000,189398.913000
1997,200280.343667,171994.991667,181403.227667,172090.696333,181840.265000,199295.415333,229575.380000,221830.162667,200605.488667,189878.162667,180648.251667,197468.474000
1998,196739.160667,173635.288000,191150.884000,174055.222667,199658.830000,219170.821333,241189.864667,238142.631333,212518.464000,189529.256667,177993.091667,198556.345333
1999,210428.545000,183110.624333,198649.230333,187035.768333,199951.545333,219172.315000,250911.624000,242573.673667,203566.862333,189175.977667,180620.208000,196668.910000
2000,218527.282333,195986.239667,200917.867333,190254.184667,215167.107000,225904.791667,237549.931000,245644.229000,208166.783333,192832.588333,189649.202333,212538.518000
2001,221331.550333,188336.149000,200160.644333,185066.762000,199998.991333,218136.818333,238068.411667,246672.575667,204284.640333,196147.502000,185609.164333,203313.775667
2002,212965.032000,187556.658667,201363.260333,192888.209000,204769.421333,226971.263333,253862.759333,249280.915333,220436.169000,204308.581333,197172.882333,216217.375667
2003,227637.355333,199201.444000,202527.970000,190152.976000,204672.187667,218783.002333,249146.455000,254046.695000,214980.112333,204055.591000,198166.455000,220738.389333
2004,230660.507667,209158.489000,205490.638333,193324.843333,217848.129000,229651.161000,251120.765000,245226.101667,223377.153333,207919.894333,201008.359333,227506.665333
2005,228389.392333,198683.629333,211293.575333,192713.786000,209692.586000,242085.290000,267781.656333,269520.217333,233123.449333,210615.476000,203739.634667,231702.787000
2006,218747.975667,204566.882000,212110.991000,198213.615000,220037.232667,242485.015333,273238.035333,271467.975667,221017.507000,214008.990667,205755.122000,223827.342667
2007,235346.759333,215180.563000,213308.195333,201761.999667,219793.106667,241491.950667,261801.219333,280841.212000,236597.542667,221391.842667,209079.280000,230492.436000
2008,241681.922333,216424.181000,216093.382000,203573.931667,216477.696333,248378.817000,268231.052000,258969.102000,225060.270333,212068.008667,206405.706667,228959.881333
2009,236349.639333,200300.084000,206740.793000,192695.779333,207192.237333,231426.072333,248007.851667,253792.825333,217944.687667,204371.163667,197423.181667,233333.526000
2010,240300.030333,212853.434000,207777.745333,191534.933333,218271.105667,250121.855333,272768.289000,272203.416333,230324.640667,204917.180333,203646.621333,241035.567000
2011,241557.500333,208408.868333,212079.162667,201220.193333,215348.848667,244739.408333,278692.181333,270597.483667,224910.265000,205407.147333,202339.235000,223409.124000
2012,225973.197000,205902.328667,205680.375000,196455.293000,223945.114333,240162.157000,276020.308000,263407.205667,222678.344333,207388.692000,203603.427000,222698.041667
2013,232279.064000,206145.309333,216551.487333,199213.938333,214400.577333,237506.765333,262830.054000,256451.617000,226900.090333,209555.427667,209311.993333,234967.214000
2014,251139.124000,215918.676000,220851.183333,198074.211667,216110.334333,238190.345000,256798.574000,255814.360667,226204.540333,209307.334333,211276.335333,224898.554000
2015,239930.249667,222655.323000,215777.650333,195723.638667,214329.743667,241210.420667,266514.967667,260977.341000,233020.486667,207672.970667,200036.511000,215875.388333
2016,234761.693000,208776.571667,202563.076333,194892.617000,210791.282667,244794.022000,274182.964667,272717.936667,233933.776333,208260.704333,197675.240000,229848.693667
2017,229190.610000,193702.361333,212536.799333,196557.010000,215268.270333,238648.279667,269219.422667,256086.716667,223598.632000,212102.852667,205008.409000,233228.970000
2018,248450.436667,204264.716000,213995.268667,200161.605667,225608.481000,247555.746000,273823.333667,271636.506667,237170.707667,216259.807667,214554.242000,227712.977000
2019,239274.939000,209683.340333,217412.446333,197436.713667,219909.786000,234958.320000,272972.982333,267216.225333,239964.959000,213201.234000,210205.402000,225223.404667
2020,227535.806000,212709.648667,206027.306000,186031.154000,202698.833333,234157.150000,272676.941333,265150.709000,221833.402333,208665.141333,200477.942667,229174.549000
2021,233495.559000,217175.636333,207836.153000,194682.068000,212239.820000,248835.450667,269483.455333,275223.789667,231807.593667,212765.898667,210003.960667,226097.468000
2022,252305.376667,218214.324000,216977.441000,202591.370000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 5. Pivot tables

In [70]:
# df5 = df2
# df5
# df5['range'] = 'Low'
# df5['range'][df5['non-renewable']>=df5['renewable']*5] = 'Avg'
# df5['range'][df5['non-renewable']>=df5['renewable']*7] = 'High'
# df5

In [71]:
df5= df3.melt(id_vars=['month','year'],var_name="source",value_name="Net_elec_generation",ignore_index=False)
df5

     month  year     source  Net_elec_generation
0        1  1973      Total           160217.989
1        2  1973      Total           143538.699
2        3  1973      Total           148158.370
3        4  1973      Total           139589.440
4        5  1973      Total           147395.124
..     ...   ...        ...                  ...
587     12  2021  renewable            78475.696
588      1  2022  renewable            78793.520
589      2  2022  renewable            76200.267
590      3  2022  renewable            86739.642
591      4  2022  renewable            85004.357

[1776 rows x 4 columns]

In [72]:
df5['net_elec*2'] = df5['Net_elec_generation']*2
df5

     month  year     source  Net_elec_generation  net_elec*2
0        1  1973      Total           160217.989  320435.978
1        2  1973      Total           143538.699  287077.398
2        3  1973      Total           148158.370  296316.740
3        4  1973      Total           139589.440  279178.880
4        5  1973      Total           147395.124  294790.248
..     ...   ...        ...                  ...         ...
587     12  2021  renewable            78475.696  156951.392
588      1  2022  renewable            78793.520  157587.040
589      2  2022  renewable            76200.267  152400.534
590      3  2022  renewable            86739.642  173479.284
591      4  2022  renewable            85004.357  170008.714

[1776 rows x 5 columns]

In [73]:
pd.pivot_table(df5, values="Net_elec_generation", index=["year", "month"], columns=["source"])

source           Total  non-renewable  renewable
year month
1973 1      160217.989     133804.986  26413.002
     2      143538.699     120065.492  23473.208
     3      148158.370     122113.112  26045.257
     4      139589.440     115037.131  24552.309
     5      147395.124     122121.797  25273.326
...                ...            ...        ...
2021 12     339684.017     260132.691  78475.696
2022 1      378966.702     299155.908  78793.520
     2      327766.846     250675.859  76200.267
     3      325952.002     238240.679  86739.642
     4      304348.709     218421.044  85004.357

[592 rows x 3 columns]

In [74]:
pd.pivot_table(df5, values="Net_elec_generation", index=["year"], columns=["source","month"], aggfunc=np.sum)

source       Total                                                  \
month           1           2           3           4           5
year
1973    160217.989  143538.699  148158.370  139589.440  147395.124
1974    157554.691  142748.458  150342.206  142311.633  153812.873
1975    164623.080  147349.000  155760.211  146494.879  153531.080
1976    178608.612  156965.799  164466.676  153467.392  157664.467
1977    196665.182  162949.088  169437.171  157117.355  169596.403
1978    198107.635  173745.731  173460.887  160012.982  175548.628
1979    209986.749  186587.309  183154.004  170260.472  178409.356
1980    200296.330  188961.379  187744.800  169016.585  176066.486
1981    206758.205  179859.910  185833.882  172841.342  178138.553
1982    209694.373  180545.573  187967.965  172876.502  177479.981
1983    195870.844  172725.190  182768.722  170668.876  174724.813
1984    216923.729  189810.043  200387.475  181381.139  192550.198
1985    228147.888  198488.497  195250.388  185173.312  197122.843
1986    217761.136  192582.016  197114.555  186370.454  197647.498
1987    223040.975  194280.625  202129.944  189792.417  206406.878
1988    238188.434  217183.084  214293.615  196297.111  208703.604
1989    246766.176  233782.777  241946.410  222868.586  234824.770
1990    255187.021  229499.204  244761.483  229769.727  241773.529
1991    269214.313  228290.131  240561.216  227798.971  254873.018
1992    267772.670  239514.031  247733.163  233405.563  242411.928
1993    271020.902  248015.328  261247.551  234695.127  244325.583
1994    289768.406  249172.290  257998.052  240636.581  252744.936
1995    279773.101  252307.149  261342.562  244735.923  264288.242
1996    296922.971  270685.247  275019.018  251612.875  282266.414
1997    300573.901  258131.029  272258.227  258284.482  272913.783
1998    295260.404  260589.918  286877.989  261229.604  299639.908
1999    315813.690  274820.273  298144.718  280719.013  300098.190
2000    327993.944  294169.282  301579.821  285577.749  322953.681
2001    332493.160  282940.198  300706.544  278078.871  300491.621
2002    319941.472  281825.708  302549.007  289848.252  307674.569
2003    341988.899  299248.775  304317.263  285755.700  307544.887
2004    346545.627  314279.910  308812.096  290559.914  327380.264
2005    343121.453  298500.316  317458.276  289562.400  315062.110
2006    328657.739  307333.430  318729.800  297858.078  330615.570
2007    353531.095  323230.395  320471.243  303129.064  330202.758
2008    362998.429  325105.597  324629.850  305865.031  325244.802
2009    354992.636  300887.398  310602.964  289537.255  311305.872
2010    360957.167  319734.727  312167.640  287800.227  327936.492
2011    362871.893  313126.607  318709.941  302400.724  323628.238
2012    339528.259  309389.420  309090.569  295228.216  336517.631
2013    348967.378  309728.080  325398.834  299332.868  322155.640
2014    377254.711  324348.436  331823.059  297630.588  324724.300
2015    360455.167  334475.546  324191.894  294133.343  322086.912
2016    352719.066  313685.401  304389.581  292893.550  316784.457
2017    344332.034  291049.672  319335.755  295360.591  323446.738
2018    373230.280  306894.214  321546.954  300756.440  338947.606
2019    359509.234  315026.484  326657.208  296662.569  330423.048
2020    341850.206  319550.114  309586.723  279583.265  304593.238
2021    350795.813  326223.389  312284.622  292503.539  318858.513
2022    378966.702  327766.846  325952.002  304348.709         NaN

source                                                              ...  \
month           6           7           8           9           10  ...
year                                                                ...
1973    161243.674  173733.007  177365.364  156875.032  154197.466  ...
1974    156440.089  178247.304  174119.001  152467.442  152195.832  ...
1975    162716.960  177056.505  179930.892  155440.826  155187.742  ...
1976    173673.719  186691.040  186638.696  165237.437  164009.445  ...
1977    181031.212  199167.726  196363.166  176497.560  166645.282  ...
1978    188585.386  202947.293  206658.749  185802.058  176013.116  ...
1979    186976.379  202522.477  205100.592  180974.646  179953.363  ...
1980    189748.486  217057.853  215629.382  191697.740  178761.034  ...
1981    203020.751  220654.747  210639.415  187051.489  181557.590  ...
1982    186447.119  210865.079  205891.676  180875.268  173172.248  ...
1983    191367.206  220446.836  230193.460  195817.014  183136.711  ...
1984    209967.314  221526.162  229531.666  195411.388  191142.430  ...
1985    205681.971  227003.762  226286.447  202712.422  194995.217  ...
1986    215334.156  242953.552  225402.481  206905.101  197959.776  ...
1987    225907.915  248196.221  247880.760  213221.249  203214.924  ...
1988    233065.853  257742.125  267928.593  220392.242  210813.885  ...
1989    250919.110  273457.735  275419.519  242793.798  235669.018  ...
1990    268992.258  287447.762  290655.259  258356.632  244372.250  ...
1991    269099.254  294647.834  292158.580  256027.328  245378.242  ...
1992    261076.926  293616.745  281927.430  259925.035  244993.925  ...
1993    275359.600  312224.835  311450.190  264032.481  250552.792  ...
1994    294161.782  311256.823  307604.584  266262.327  256528.490  ...
1995    286258.135  330416.095  345780.079  277575.357  263978.440  ...
1996    302716.899  327708.462  329286.330  283151.263  271446.494  ...
1997    299091.561  344516.455  332898.630  301056.672  284970.629  ...
1998    328903.002  361936.460  357365.610  318924.466  284445.547  ...
1999    328923.833  376538.308  364031.383  305515.654  283934.839  ...
2000    339053.660  356527.917  368669.365  312446.647  289451.903  ...
2001    327693.978  357613.700  370532.828  306928.866  294733.613  ...
2002    341023.145  381542.109  374585.823  331279.434  307059.462  ...
2003    328693.699  374396.049  381816.318  323135.536  306740.934  ...
2004    345085.079  377331.697  368439.037  335622.198  312450.223  ...
2005    363671.636  402273.846  404940.681  350217.801  316397.924  ...
2006    364259.798  410420.793  407762.536  332055.321  321567.091  ...
2007    362754.877  393226.432  421796.659  355393.912  332615.416  ...
2008    373109.027  402900.336  388986.719  338056.130  318547.343  ...
2009    347658.241  372542.226  381221.417  327400.612  307040.341  ...
2010    375759.478  409725.440  408884.155  346045.172  307920.691  ...
2011    367727.015  418692.755  406511.315  337931.318  308698.504  ...
2012    360826.151  414639.671  395699.566  334584.877  311650.774  ...
2013    356822.647  394845.621  385285.745  340940.902  314925.463  ...
2014    357844.043  385779.552  384341.148  339886.506  314521.999  ...
2015    362409.202  400418.853  392116.203  350121.648  312111.680  ...
2016    367781.196  411886.942  409700.812  351484.468  312945.164  ...
2017    358522.007  404432.474  384738.580  335914.910  318669.649  ...
2018    371885.761  411290.320  408027.757  356258.302  324931.943  ...
2019    352988.074  410037.810  401429.694  360518.468  320351.885  ...
2020    351744.930  409561.700  398279.697  333258.048  313531.271  ...
2021    373754.405  404748.717  413353.176  348200.651  319638.396  ...
2022           NaN         NaN         NaN         NaN         NaN  ...

source  renewable                                                         \
month          3          4          5          6          7          8
year
1973    26045.257  24552.309  25273.326  24240.615  22884.694  21578.636
1974    28053.082  28346.187  28453.726  27097.194  26735.794  24474.015
1975    28480.561  27133.136  28268.477  27734.136  26075.189  23170.172
1976    27201.037  24748.570  26110.084  26158.453  26659.362  24413.543
1977    20436.963  19225.473  19282.856  17805.593  17364.344  17266.370
1978    25161.617  25788.224  29256.131  25619.274  24968.745  22744.596
1979    26608.010  26029.779  29629.392  25619.443  23392.849  21914.771
1980    25013.631  26455.027  29665.334  28420.038  25225.145  21184.607
1981    21393.690  21519.438  24896.566  27161.385  25937.479  22371.409
1982    30495.266  28552.739  28684.615  28729.295  28060.188  24610.375
1983    31037.573  30709.732  31882.370  31473.524  28959.589  26801.321
1984    31434.051  30961.957  32819.440  29745.637  28424.295  26167.086
1985    25850.124  25482.422  27569.849  24945.752  22459.120  21151.129
1986    29729.505  28710.832  28440.455  27515.672  25398.166  22483.632
1987    24562.927  23287.172  25546.673  22252.261  21578.831  19783.505
1988    20835.409  20359.579  22493.063  20156.057  18268.892  17747.021
1989    27761.137  28808.607  32621.442  30678.854  27670.139  25421.615
1990    34828.779  31732.310  32871.153  32997.759  29496.012  27436.640
1991    31844.584  31033.293  34484.794  31800.550  30056.089  28712.427
1992    27999.393  25380.240  27677.794  29267.757  26672.614  25574.923
1993    31930.748  32283.431  35573.202  32596.186  29951.968  27222.600
1994    30186.453  30572.712  30800.985  30105.325  29936.896  26374.394
1995    33754.542  30558.997  32667.449  35157.625  34457.327  32178.920
1996    39565.711  36497.549  38292.055  38017.707  36317.861  33630.210
1997    40712.864  38323.973  40956.937  40111.762  38208.348  33668.706
1998    37954.135  34045.670  38647.879  36417.367  34869.031  31445.370
1999    37380.334  33453.790  36174.055  36403.530  36335.047  31874.173
2000    33200.063  35068.774  33954.613  30817.602  30702.559  28462.447
2001    25499.065  23043.770  24291.245  25918.383  23452.814  24492.409
2002    26678.710  30204.788  32883.433  34415.516  31529.231  27193.340
2003    30143.422  30887.070  35271.056  34502.096  31107.035  28956.093
2004    29261.554  27114.370  30670.154  31632.078  29891.889  27800.605
2005    29807.860  29921.811  34355.997  34004.470  32896.820  28178.683
2006    32388.490  35828.296  38409.736  37116.575  32923.071  28927.413
2007    32483.761  32209.740  34121.009  30842.830  30254.305  28184.553
2008    31819.053  33073.233  37734.119  39950.646  35089.216  30095.762
2009    34462.001  38483.532  41075.300  40474.468  34080.568  30758.784
2010    35214.695  34368.614  39269.294  43591.310  37066.804  32619.031
2011    47435.791  48853.949  49807.917  48868.248  44577.418  39124.787
2012    45828.117  44592.247  47169.856  44621.589  41597.086  37835.099
2013    42882.331  48765.761  51370.317  47980.078  45506.910  38550.712
2014    49686.405  51537.603  49765.439  49554.961  44856.931  37987.699
2015    47814.907  48750.922  45937.412  42576.926  43955.301  41317.620
2016    58089.881  55092.596  53876.725  48975.925  49043.898  43132.802
2017    66027.418  65484.645  67376.721  62782.187  54427.234  47581.462
2018    63626.543  66241.346  67322.238  65772.266  54525.608  54565.891
2019    63860.077  68955.286  70511.306  64177.848  60977.064  56421.730
2020    65420.145  66322.848  73510.051  72920.106  65425.812  60887.218
2021    76624.292  71541.439  74236.846  68244.802  61085.897  65121.239
2022    86739.642  85004.357        NaN        NaN        NaN        NaN

source
month          9          10         11         12
year
1973    17480.982  18661.753  20446.638  26674.160
1974    21794.475  20413.638  21576.359  23568.166
1975    21039.506  23223.672  25002.478  26578.416
1976    20897.571  21623.302  20357.866  20818.147
1977    16999.677  17792.227  21033.467  23415.655
1978    21725.694  19947.472  20450.822  22662.299
1979    19555.501  20793.550  23016.992  23450.383
1980    19173.210  18605.275  19959.082  23031.770
1981    18572.955  18825.826  19649.741  24571.374
1982    20576.777  20465.608  24037.895  28410.580
1983    22602.813  21664.692  25536.461  32455.752
1984    21851.936  21911.040  23307.830  26961.539
1985    19867.121  21102.722  24206.379  26707.559
1986    22221.906  22413.363  24156.389  27222.208
1987    19404.348  19175.907  18061.373  22336.027
1988    17484.716  16331.662  19672.899  21129.235
1989    24087.527  25411.036  26590.750  27212.986
1990    23098.894  24766.087  25809.528  30447.023
1991    25711.324  24385.390  25179.259  29253.126
1992    23938.070  23798.983  26660.055  31527.586
1993    24361.909  24366.667  25709.171  28920.301
1994    22193.363  24248.402  25657.207  28593.727
1995    26522.622  30280.790  32125.433  35126.135
1996    28281.778  30049.380  30383.764  36450.551
1997    29231.105  31956.575  29634.547  31535.308
1998    27450.052  25770.058  25454.783  32718.519
1999    27043.516  25549.099  27482.290  30895.383
2000    23358.549  23891.357  26125.954  25343.866
2001    20097.295  20669.729  20314.962  24761.946
2002    22892.180  23049.535  25313.337  27485.909
2003    24248.269  24361.051  25550.490  30450.654
2004    26452.188  25010.362  26763.898  32585.291
2005    23977.444  24577.195  26120.574  29218.983
2006    24292.914  24842.875  28023.545  29433.155
2007    22841.729  23397.767  24049.086  27329.076
2008    24584.489  25620.068  25961.225  32753.622
2009    27535.090  31974.019  33488.244  37406.982
2010    30071.332  31036.353  34876.844  37997.858
2011    33842.048  35736.646  38812.204  40408.541
2012    32574.498  35347.292  36540.606  43809.058
2013    35513.919  37883.538  40294.260  42333.508
2014    35425.809  39430.053  44901.356  44470.386
2015    38197.460  40895.098  47117.376  51486.763
2016    42181.713  46527.055  47020.477  54357.769
2017    47842.690  52498.813  51769.453  53838.024
2018    49241.161  51451.998  53647.218  56340.436
2019    55293.288  57428.569  54903.006  57216.976
2020    54737.452  59910.591  65222.203  64343.520
2021    63258.203  65065.088  69649.783  78475.696
2022          NaN        NaN        NaN        NaN

[50 rows x 36 columns]

In [75]:
pd.pivot_table(df5, values=["Net_elec_generation", "net_elec*2"],index=["year"], columns=["month","source"],aggfunc=np.sum)

       Net_elec_generation                                                     \
month                   1                                    2
source               Total non-renewable  renewable       Total non-renewable
year
1973            160217.989    133804.986  26413.002  143538.699    120065.492
1974            157554.691    128161.539  29393.153  142748.458    115739.129
1975            164623.080    139095.914  25527.166  147349.000    122991.945
1976            178608.612    151915.484  26693.128  156965.799    131839.754
1977            196665.182    175312.508  21352.674  162949.088    147262.459
1978            198107.635    172412.866  25694.769  173745.731    150984.893
1979            209986.749    184344.992  25641.756  186587.309    164776.741
1980            200296.330    174338.443  25957.885  188961.379    166964.054
1981            206758.205    183587.666  23170.539  179859.910    158031.655
1982            209694.373    182095.949  27598.425  180545.573    153229.540
1983            195870.844    165838.416  30032.428  172725.190    144134.207
1984            216923.729    186347.843  30575.886  189810.043    161021.182
1985            228147.888    199406.722  28741.166  198488.497    171536.809
1986            217761.136    194969.546  22791.591  192582.016    168157.597
1987            223040.975    196320.233  26720.743  194280.625    171867.773
1988            238188.434    214831.396  23357.039  217183.084    196933.566
1989            246766.176    220606.033  25834.867  233782.777    210255.368
1990            255187.021    225023.305  29856.630  229499.204    198832.324
1991            269214.313    235717.517  33094.319  228290.131    200249.739
1992            267772.670    238028.981  29428.616  239514.031    214464.064
1993            271020.902    237847.450  32877.282  248015.328    220869.567
1994            289768.406    261105.937  28351.032  249172.290    222628.433
1995            279773.101    249596.508  29828.049  252307.149    222577.227
1996            296922.971    260522.062  36098.424  270685.247    234117.682
1997            300573.901    261382.181  38884.949  258131.029    221482.806
1998            295260.404    259185.442  35771.636  260589.918    224903.659
1999            315813.690    279363.486  36108.459  274820.273    240349.143
2000            327993.944    296612.661  30975.242  294169.282    264750.748
2001            332493.160    307213.135  24288.356  282940.198    259991.980
2002            319941.472    291309.797  27643.827  281825.708    255439.001
2003            341988.899    314624.984  26298.183  299248.775    273372.932
2004            346545.627    316333.141  29102.755  314279.910    286484.280
2005            343121.453    311496.142  30550.582  298500.316    270068.126
2006            328657.739    292247.379  35338.809  307333.430    274678.033
2007            353531.095    318368.441  34140.742  323230.395    296314.757
2008            362998.429    331770.962  30276.376  325105.597    296480.428
2009            354992.636    319328.101  34728.181  300887.398    271383.568
2010            360957.167    325319.829  34623.095  319734.727    287685.863
2011            362871.893    322186.722  39613.886  313126.607    272265.853
2012            339528.259    295726.817  42664.515  309389.420    271274.830
2013            348967.378    301988.004  45881.810  309728.080    268278.576
2014            377254.711    329325.331  46837.330  324348.436    285455.792
2015            360455.167    312627.198  46708.384  334475.546    289099.091
2016            352719.066    299584.205  51981.808  313685.401    260165.989
2017            344332.034    287117.988  56121.808  291049.672    235719.739
2018            373230.280    311842.583  60278.447  306894.214    248001.809
2019            359509.234    299431.657  58883.926  315026.484    259240.651
2020            341850.206    277929.403  62827.809  319550.114    252424.427
2021            350795.813    281855.100  67835.764  326223.389    265166.887
2022            378966.702    299155.908  78793.520  327766.846    250675.859

                                                                    ...  \
month                      3                                    4   ...
source  renewable       Total non-renewable  renewable       Total  ...
year                                                                ...
1973    23473.208  148158.370    122113.112  26045.257  139589.440  ...
1974    27009.328  150342.206    122289.124  28053.082  142311.633  ...
1975    24357.056  155760.211    127279.651  28480.561  146494.879  ...
1976    25126.046  164466.676    137265.638  27201.037  153467.392  ...
1977    15686.627  169437.171    149000.209  20436.963  157117.355  ...
1978    22760.838  173460.887    148299.269  25161.617  160012.982  ...
1979    21810.569  183154.004    156545.993  26608.010  170260.472  ...
1980    21997.325  187744.800    162731.171  25013.631  169016.585  ...
1981    21828.256  185833.882    164440.192  21393.690  172841.342  ...
1982    27316.033  187967.965    157472.699  30495.266  172876.502  ...
1983    28590.983  182768.722    151731.149  31037.573  170668.876  ...
1984    28788.859  200387.475    168953.424  31434.051  181381.139  ...
1985    26951.688  195250.388    169400.264  25850.124  185173.312  ...
1986    24424.420  197114.555    167385.050  29729.505  186370.454  ...
1987    22412.852  202129.944    177567.017  24562.927  189792.417  ...
1988    20249.517  214293.615    193458.206  20835.409  196297.111  ...
1989    23233.611  241946.410    213859.999  27761.137  222868.586  ...
1990    30389.514  244761.483    209625.621  34828.779  229769.727  ...
1991    27676.865  240561.216    208314.154  31844.584  227798.971  ...
1992    24755.222  247733.163    219418.699  27999.393  233405.563  ...
1993    26878.253  261247.551    229020.634  31930.748  234695.127  ...
1994    26262.557  257998.052    227500.163  30186.453  240636.581  ...
1995    29415.109  261342.562    227239.477  33754.542  244735.923  ...
1996    36284.595  275019.018    235150.821  39565.711  251612.875  ...
1997    36371.140  272258.227    231238.592  40712.864  258284.482  ...
1998    35412.287  286877.989    248620.528  37954.135  261229.604  ...
1999    34162.457  298144.718    260422.639  37380.334  280719.013  ...
2000    29038.689  301579.821    267973.718  33200.063  285577.749  ...
2001    22076.269  300706.544    274276.324  25499.065  278078.871  ...
2002    25405.267  302549.007    274862.064  26678.710  289848.252  ...
2003    24982.625  304317.263    273123.225  30143.422  285755.700  ...
2004    26711.277  308812.096    278398.265  29261.554  290559.914  ...
2005    27482.446  317458.276    286614.590  29807.860  289562.400  ...
2006    31689.183  318729.800    285214.683  32388.490  297858.078  ...
2007    25996.537  320471.243    286969.582  32483.761  303129.064  ...
2008    27686.518  324629.850    291831.243  31819.053  305865.031  ...
2009    28629.286  310602.964    275157.414  34462.001  289537.255  ...
2010    31139.712  312167.640    275950.901  35214.695  287800.227  ...
2011    39834.145  318709.941    270091.756  47435.791  302400.724  ...
2012    37042.736  309090.569    262122.439  45828.117  295228.216  ...
2013    40429.272  325398.834    281373.297  42882.331  299332.868  ...
2014    37951.800  331823.059    281044.086  49686.405  297630.588  ...
2015    44391.332  324191.894    275326.150  47814.907  294133.343  ...
2016    52478.325  304389.581    245209.767  58089.881  292893.550  ...
2017    54337.673  319335.755    252247.225  66027.418  295360.591  ...
2018    57898.125  321546.954    256812.309  63626.543  300756.440  ...
2019    54782.886  326657.208    261720.054  63860.077  296662.569  ...
2020    66154.405  309586.723    243075.050  65420.145  279583.265  ...
2021    60136.633  312284.622    234599.545  76624.292  292503.539  ...
2022    76200.267  325952.002    238240.679  86739.642  304348.709  ...

        net_elec*2                                                    \
month           9           10                                    11
source   renewable       Total non-renewable   renewable       Total
year
1973     34961.964  308394.932    271071.426   37323.506  296275.218
1974     43588.950  304391.664    263564.386   40827.276  300141.710
1975     42079.012  310375.484    263928.142   46447.344  306070.194
1976     41795.142  328018.890    284772.288   43246.604  338692.582
1977     33999.354  333290.564    297706.108   35584.454  334776.144
1978     43451.388  352026.232    312131.290   39894.944  352778.186
1979     39111.002  359906.726    318319.628   41587.100  355539.016
1980     38346.420  357522.068    320311.518   37210.550  357542.722
1981     37145.910  363115.180    325463.528   37651.652  351583.506
1982     41153.554  346344.496    305413.278   40931.216  347197.518
1983     45205.626  366273.422    322944.038   43329.384  366341.362
1984     43703.872  382284.860    338462.782   43822.080  381203.730
1985     39734.242  389990.434    347784.990   42205.444  385297.904
1986     44443.812  395919.552    351092.826   44826.726  393307.372
1987     38808.696  406429.848    368078.036   38351.814  400958.772
1988     34969.432  421627.770    388964.446   32663.324  419629.984
1989     48175.054  471338.036    419865.412   50822.072  468499.620
1990     46197.788  488744.500    438598.156   49532.174  462484.754
1991     51422.648  490756.484    441180.750   48770.780  483322.730
1992     47876.140  489987.850    441759.746   47597.966  488323.998
1993     48723.818  501105.584    451779.910   48733.334  504204.276
1994     44386.726  513056.980    463937.302   48496.804  503736.696
1995     53045.244  527956.880    466698.212   60561.580  522956.798
1996     56563.556  542892.988    482189.260   60098.760  538244.070
1997     58462.210  569941.258    505414.568   63913.150  542241.632
1998     54900.104  568891.094    516744.330   51540.116  534272.816
1999     54087.032  567869.678    516087.990   51098.198  542191.344
2000     46717.098  578903.806    530309.010   47782.714  569340.550
2001     40194.590  589467.226    546078.328   41339.458  557867.884
2002     45784.360  614118.924    565633.494   46099.070  592579.122
2003     48496.538  613481.868    562129.576   48722.102  595733.426
2004     52904.376  624900.446    572598.196   50020.724  604202.512
2005     47954.888  632795.848    581742.618   49154.390  612230.472
2006     48585.828  643134.182    591234.012   49685.750  618317.652
2007     45683.458  665230.832    616324.690   46795.534  628205.086
2008     49168.978  637094.686    584073.230   51240.136  620092.482
2009     55070.180  614080.682    548198.262   63948.038  593269.340
2010     60142.664  615841.382    551588.994   62072.706  612019.258
2011     67684.096  617397.008    543572.584   71473.292  608204.310
2012     65148.996  623301.548    550336.020   70694.584  611950.070
2013     71027.838  629850.926    551714.564   75767.076  629079.284
2014     70851.618  629043.998    547939.902   78860.106  634990.018
2015     76394.920  624223.360    540024.268   81790.196  601306.536
2016     84363.426  625890.328    530619.788   93054.110  594123.544
2017     95685.380  637339.298    530280.192  104997.626  616104.684
2018     98482.322  649863.886    544790.964  102903.996  644737.314
2019    110586.576  640703.770    523646.496  114857.138  631698.184
2020    109474.904  627062.542    505107.124  119821.182  602500.362
2021    126516.406  639276.792    507188.424  130130.176  630989.834
2022           NaN         NaN           NaN         NaN         NaN


month                                     12
source non-renewable   renewable       Total non-renewable   renewable
year
1973      255381.938   40893.276  307209.716    253861.392   53348.320
1974      256988.992   43152.718  320018.038    272881.708   47136.332
1975      256065.240   50004.956  339256.592    286099.760   53156.832
1976      297976.848   40715.732  368288.214    326651.920   41636.294
1977      292709.210   42066.934  369178.540    322347.230   46831.310
1978      311876.540   40901.644  384210.706    338886.106   45324.598
1979      309505.032   46033.984  377940.342    331039.572   46900.766
1980      317624.558   39918.164  391697.854    345634.314   46063.540
1981      312284.028   39299.482  391651.398    342508.652   49142.748
1982      299121.728   48075.790  369915.886    313094.724   56821.160
1983      315268.440   51072.922  425110.666    360199.162   64911.504
1984      334588.072   46615.660  400463.916    346540.838   53923.078
1985      336885.146   48412.758  438980.846    385565.726   53415.118
1986      344994.594   48312.778  427573.084    373128.666   54444.416
1987      364836.026   36122.746  441472.744    396800.686   44672.054
1988      380284.184   39345.798  465975.278    423716.806   42258.470
1989      414688.554   53181.500  548896.756    493820.232   54425.972
1990      410271.342   51619.056  511539.670    450031.454   60894.046
1991      432185.228   50358.518  508177.266    448866.060   58506.252
1992      434394.072   53320.110  534685.582    471000.268   63055.172
1993      452212.700   51418.342  544329.140    485896.196   57840.602
1994      451819.502   51314.414  539039.538    481229.206   57187.454
1995      458031.332   64250.866  571107.764    500158.408   70252.270
1996      476891.086   60767.528  568499.226    494993.150   72901.102
1997      482378.784   59269.094  592712.194    529028.034   63070.616
1998      482776.168   50909.566  595972.362    529928.672   65437.038
1999      486565.324   54964.580  590348.474    527874.220   61790.766
2000      516302.756   52251.908  638021.596    586521.780   50687.732
2001      515157.178   40629.924  610992.656    559366.106   49523.892
2002      539831.498   50626.674  649667.408    592665.028   54971.818
2003      542164.324   51100.980  663360.862    600168.166   60901.308
2004      548319.848   53527.796  683895.926    615973.484   65170.582
2005      557966.188   52241.148  696202.142    635576.614   58437.966
2006      560165.990   56047.090  672566.492    611531.254   58866.310
2007      578172.422   48098.172  692580.662    635715.802   54658.152
2008      566419.308   51922.450  687796.508    620455.536   65507.244
2009      524293.262   66976.488  701014.590    624172.602   74813.964
2010      540106.782   69753.688  724238.162    645979.524   75995.716
2011      528206.692   77624.408  671480.926    588156.736   80817.082
2012      536589.280   73081.212  669270.178    579299.956   87618.116
2013      546204.156   80588.520  706042.496    619093.772   84667.016
2014      542865.282   89802.712  675913.312    584537.240   88940.772
2015      504677.778   94234.752  648854.448    543424.356  102973.526
2016      497886.942   94040.954  690685.154    579691.470  108715.538
2017      510406.864  103538.906  700831.616    590866.156  107676.048
2018      535293.702  107294.436  684278.224    569318.766  112680.872
2019      519728.216  109806.012  676803.294    560103.182  114433.952
2020      469922.888  130444.406  688692.190    557668.064  128687.040
2021      489734.364  139299.566  679368.034    520265.382  156951.392
2022             NaN         NaN         NaN           NaN         NaN

[50 rows x 72 columns]

In [76]:
# tab5= pd.pivot_table(df5, values=["Net_elec_generation", "net_elec*2"],index=["year"], columns=["month","source"],aggfunc=np.sum)

In [77]:
# print(tab5.to_string(na_rep=""))

In [78]:
pd.pivot_table(df5['month year source Net_elec_generation net_elec*2'.split()], index=["year", "month"], columns=["source"])

           Net_elec_generation                           net_elec*2  \
source                   Total non-renewable  renewable       Total
year month
1973 1              160217.989    133804.986  26413.002  320435.978
     2              143538.699    120065.492  23473.208  287077.398
     3              148158.370    122113.112  26045.257  296316.740
     4              139589.440    115037.131  24552.309  279178.880
     5              147395.124    122121.797  25273.326  294790.248
...                        ...           ...        ...         ...
2021 12             339684.017    260132.691  78475.696  679368.034
2022 1              378966.702    299155.908  78793.520  757933.404
     2              327766.846    250675.859  76200.267  655533.692
     3              325952.002    238240.679  86739.642  651904.004
     4              304348.709    218421.044  85004.357  608697.418


source     non-renewable   renewable
year month
1973 1        267609.972   52826.004
     2        240130.984   46946.416
     3        244226.224   52090.514
     4        230074.262   49104.618
     5        244243.594   50546.652
...                  ...         ...
2021 12       520265.382  156951.392
2022 1        598311.816  157587.040
     2        501351.718  152400.534
     3        476481.358  173479.284
     4        436842.088  170008.714

[592 rows x 6 columns]

In [79]:
tab_df5= pd.pivot_table(df5, values=["Net_elec_generation", "net_elec*2"],index=["year","month"], columns=["source"])
print(tab_df5.to_string(na_rep="  "))

           Net_elec_generation                           net_elec*2
source                   Total non-renewable  renewable       Total non-renewable   renewable
year month
1973 1              160217.989    133804.986  26413.002  320435.978    267609.972   52826.004
     2              143538.699    120065.492  23473.208  287077.398    240130.984   46946.416
     3              148158.370    122113.112  26045.257  296316.740    244226.224   52090.514
     4              139589.440    115037.131  24552.309  279178.880    230074.262   49104.618
     5              147395.124    122121.797  25273.326  294790.248    244243.594   50546.652
     6              161243.674    137003.059  24240.615  322487.348    274006.118   48481.230
     7              173733.007    150848.314  22884.694  347466.014    301696.628   45769.388
     8              177365.364    155786.728  21578.636  354730.728    311573.456   43157.272
     9              156875.032    139394.051  17480.982  313750.064    278788.102   34961.964
     10             154197.466    135535.713  18661.753  308394.932    271071.426   37323.506
     11             148137.609    127690.969  20446.638  296275.218    255381.938   40893.276
     12             153604.858    126930.696  26674.160  307209.716    253861.392   53348.320
1974 1              157554.691    128161.539  29393.153  315109.382    256323.078   58786.306
     2              142748.458    115739.129  27009.328  285496.916    231478.258   54018.656
     3              150342.206    122289.124  28053.082  300684.412    244578.248   56106.164
     4              142311.633    113965.447  28346.187  284623.266    227930.894   56692.374
     5              153812.873    125359.148  28453.726  307625.746    250718.296   56907.452
     6              156440.089    129342.894  27097.194  312880.178    258685.788   54194.388
     7              178247.304    151511.511  26735.794  356494.608    303023.022   53471.588
     8              174119.001    149644.987  24474.015  348238.002    299289.974   48948.030
     9              152467.442    130672.968  21794.475  304934.884    261345.936   43588.950
     10             152195.832    131782.193  20413.638  304391.664    263564.386   40827.276
     11             150070.855    128494.496  21576.359  300141.710    256988.992   43152.718
     12             160009.019    136440.854  23568.166  320018.038    272881.708   47136.332
1975 1              164623.080    139095.914  25527.166  329246.160    278191.828   51054.332
     2              147349.000    122991.945  24357.056  294698.000    245983.890   48714.112
     3              155760.211    127279.651  28480.561  311520.422    254559.302   56961.122
     4              146494.879    119361.743  27133.136  292989.758    238723.486   54266.272
     5              153531.080    125262.602  28268.477  307062.160    250525.204   56536.954
     6              162716.960    134982.824  27734.136  325433.920    269965.648   55468.272
     7              177056.505    150981.316  26075.189  354113.010    301962.632   52150.378
     8              179930.892    156760.720  23170.172  359861.784    313521.440   46340.344
     9              155440.826    134401.320  21039.506  310881.652    268802.640   42079.012
     10             155187.742    131964.071  23223.672  310375.484    263928.142   46447.344
     11             153035.097    128032.620  25002.478  306070.194    256065.240   50004.956
     12             169628.296    143049.880  26578.416  339256.592    286099.760   53156.832
1976 1              178608.612    151915.484  26693.128  357217.224    303830.968   53386.256
     2              156965.799    131839.754  25126.046  313931.598    263679.508   50252.092
     3              164466.676    137265.638  27201.037  328933.352    274531.276   54402.074
     4              153467.392    128718.823  24748.570  306934.784    257437.646   49497.140
     5              157664.467    131554.383  26110.084  315328.934    263108.766   52220.168
     6              173673.719    147515.267  26158.453  347347.438    295030.534   52316.906
     7              186691.040    160031.677  26659.362  373382.080    320063.354   53318.724
     8              186638.696    162225.152  24413.543  373277.392    324450.304   48827.086
     9              165237.437    144339.866  20897.571  330474.874    288679.732   41795.142
     10             164009.445    142386.144  21623.302  328018.890    284772.288   43246.604
     11             169346.291    148988.424  20357.866  338692.582    297976.848   40715.732
     12             184144.107    163325.960  20818.147  368288.214    326651.920   41636.294
1977 1              196665.182    175312.508  21352.674  393330.364    350625.016   42705.348
     2              162949.088    147262.459  15686.627  325898.176    294524.918   31373.254
     3              169437.171    149000.209  20436.963  338874.342    298000.418   40873.926
     4              157117.355    137891.883  19225.473  314234.710    275783.766   38450.946
     5              169596.403    150313.548  19282.856  339192.806    300627.096   38565.712
     6              181031.212    163225.619  17805.593  362062.424    326451.238   35611.186
     7              199167.726    181803.382  17364.344  398335.452    363606.764   34728.688
     8              196363.166    179096.795  17266.370  392726.332    358193.590   34532.740
     9              176497.560    159497.882  16999.677  352995.120    318995.764   33999.354
     10             166645.282    148853.054  17792.227  333290.564    297706.108   35584.454
     11             167388.072    146354.605  21033.467  334776.144    292709.210   42066.934
     12             184589.270    161173.615  23415.655  369178.540    322347.230   46831.310
1978 1              198107.635    172412.866  25694.769  396215.270    344825.732   51389.538
     2              173745.731    150984.893  22760.838  347491.462    301969.786   45521.676
     3              173460.887    148299.269  25161.617  346921.774    296598.538   50323.234
     4              160012.982    134224.758  25788.224  320025.964    268449.516   51576.448
     5              175548.628    146292.498  29256.131  351097.256    292584.996   58512.262
     6              188585.386    162966.111  25619.274  377170.772    325932.222   51238.548
     7              202947.293    177978.548  24968.745  405894.586    355957.096   49937.490
     8              206658.749    183914.154  22744.596  413317.498    367828.308   45489.192
     9              185802.058    164076.364  21725.694  371604.116    328152.728   43451.388
     10             176013.116    156065.645  19947.472  352026.232    312131.290   39894.944
     11             176389.093    155938.270  20450.822  352778.186    311876.540   40901.644
     12             192105.353    169443.053  22662.299  384210.706    338886.106   45324.598
1979 1              209986.749    184344.992  25641.756  419973.498    368689.984   51283.512
     2              186587.309    164776.741  21810.569  373174.618    329553.482   43621.138
     3              183154.004    156545.993  26608.010  366308.008    313091.986   53216.020
     4              170260.472    144230.693  26029.779  340520.944    288461.386   52059.558
     5              178409.356    148779.964  29629.392  356818.712    297559.928   59258.784
     6              186976.379    161356.937  25619.443  373952.758    322713.874   51238.886
     7              202522.477    179129.628  23392.849  405044.954    358259.256   46785.698
     8              205100.592    183185.821  21914.771  410201.184    366371.642   43829.542
     9              180974.646    161419.145  19555.501  361949.292    322838.290   39111.002
     10             179953.363    159159.814  20793.550  359906.726    318319.628   41587.100
     11             177769.508    154752.516  23016.992  355539.016    309505.032   46033.984
     12             188970.171    165519.786  23450.383  377940.342    331039.572   46900.766
1980 1              200296.330    174338.443  25957.885  400592.660    348676.886   51915.770
     2              188961.379    166964.054  21997.325  377922.758    333928.108   43994.650
     3              187744.800    162731.171  25013.631  375489.600    325462.342   50027.262
     4              169016.585    142561.558  26455.027  338033.170    285123.116   52910.054
     5              176066.486    146401.152  29665.334  352132.972    292802.304   59330.668
     6              189748.486    161328.448  28420.038  379496.972    322656.896   56840.076
     7              217057.853    191832.707  25225.145  434115.706    383665.414   50450.290
     8              215629.382    194444.776  21184.607  431258.764    388889.552   42369.214
     9              191697.740    172524.529  19173.210  383395.480    345049.058   38346.420
     10             178761.034    160155.759  18605.275  357522.068    320311.518   37210.550
     11             178771.361    158812.279  19959.082  357542.722    317624.558   39918.164
     12             195848.927    172817.157  23031.770  391697.854    345634.314   46063.540
1981 1              206758.205    183587.666  23170.539  413516.410    367175.332   46341.078
     2              179859.910    158031.655  21828.256  359719.820    316063.310   43656.512
     3              185833.882    164440.192  21393.690  371667.764    328880.384   42787.380
     4              172841.342    151321.904  21519.438  345682.684    302643.808   43038.876
     5              178138.553    153241.988  24896.566  356277.106    306483.976   49793.132
     6              203020.751    175859.365  27161.385  406041.502    351718.730   54322.770
     7              220654.747    194717.268  25937.479  441309.494    389434.536   51874.958
     8              210639.415    188268.007  22371.409  421278.830    376536.014   44742.818
     9              187051.489    168478.534  18572.955  374102.978    336957.068   37145.910
     10             181557.590    162731.764  18825.826  363115.180    325463.528   37651.652
     11             175791.753    156142.014  19649.741  351583.506    312284.028   39299.482
     12             195825.699    171254.326  24571.374  391651.398    342508.652   49142.748
1982 1              209694.373    182095.949  27598.425  419388.746    364191.898   55196.850
     2              180545.573    153229.540  27316.033  361091.146    306459.080   54632.066
     3              187967.965    157472.699  30495.266  375935.930    314945.398   60990.532
     4              172876.502    144323.763  28552.739  345753.004    288647.526   57105.478
     5              177479.981    148795.366  28684.615  354959.962    297590.732   57369.230
     6              186447.119    157717.825  28729.295  372894.238    315435.650   57458.590
     7              210865.079    182804.891  28060.188  421730.158    365609.782   56120.376
     8              205891.676    181281.301  24610.375  411783.352    362562.602   49220.750
     9              180875.268    160298.491  20576.777  361750.536    320596.982   41153.554
     10             173172.248    152706.639  20465.608  346344.496    305413.278   40931.216
     11             173598.759    149560.864  24037.895  347197.518    299121.728   48075.790
     12             184957.943    156547.362  28410.580  369915.886    313094.724   56821.160
1983 1              195870.844    165838.416  30032.428  391741.688    331676.832   60064.856
     2              172725.190    144134.207  28590.983  345450.380    288268.414   57181.966
     3              182768.722    151731.149  31037.573  365537.444    303462.298   62075.146
     4              170668.876    139959.144  30709.732  341337.752    279918.288   61419.464
     5              174724.813    142842.442  31882.370  349449.626    285684.884   63764.740
     6              191367.206    159893.683  31473.524  382734.412    319787.366   62947.048
     7              220446.836    191487.248  28959.589  440893.672    382974.496   57919.178
     8              230193.460    203392.138  26801.321  460386.920    406784.276   53602.642
     9              195817.014    173214.200  22602.813  391634.028    346428.400   45205.626
     10             183136.711    161472.019  21664.692  366273.422    322944.038   43329.384
     11             183170.681    157634.220  25536.461  366341.362    315268.440   51072.922
     12             212555.333    180099.581  32455.752  425110.666    360199.162   64911.504
1984 1              216923.729    186347.843  30575.886  433847.458    372695.686   61151.772
     2              189810.043    161021.182  28788.859  379620.086    322042.364   57577.718
     3              200387.475    168953.424  31434.051  400774.950    337906.848   62868.102
     4              181381.139    150419.182  30961.957  362762.278    300838.364   61923.914
     5              192550.198    159730.757  32819.440  385100.396    319461.514   65638.880
     6              209967.314    180221.676  29745.637  419934.628    360443.352   59491.274
     7              221526.162    193101.868  28424.295  443052.324    386203.736   56848.590
     8              229531.666    203364.578  26167.086  459063.332    406729.156   52334.172
     9              195411.388    173559.453  21851.936  390822.776    347118.906   43703.872
     10             191142.430    169231.391  21911.040  382284.860    338462.782   43822.080
     11             190601.865    167294.036  23307.830  381203.730    334588.072   46615.660
     12             200231.958    173270.419  26961.539  400463.916    346540.838   53923.078
1985 1              228147.888    199406.722  28741.166  456295.776    398813.444   57482.332
     2              198488.497    171536.809  26951.688  396976.994    343073.618   53903.376
     3              195250.388    169400.264  25850.124  390500.776    338800.528   51700.248
     4              185173.312    159690.889  25482.422  370346.624    319381.778   50964.844
     5              197122.843    169552.995  27569.849  394245.686    339105.990   55139.698
     6              205681.971    180736.218  24945.752  411363.942    361472.436   49891.504
     7              227003.762    204544.642  22459.120  454007.524    409089.284   44918.240
     8              226286.447    205135.317  21151.129  452572.894    410270.634   42302.258
     9              202712.422    182845.301  19867.121  405424.844    365690.602   39734.242
     10             194995.217    173892.495  21102.722  389990.434    347784.990   42205.444
     11             192648.952    168442.573  24206.379  385297.904    336885.146   48412.758
     12             219490.423    192782.863  26707.559  438980.846    385565.726   53415.118
1986 1              217761.136    194969.546  22791.591  435522.272    389939.092   45583.182
     2              192582.016    168157.597  24424.420  385164.032    336315.194   48848.840
     3              197114.555    167385.050  29729.505  394229.110    334770.100   59459.010
     4              186370.454    157659.622  28710.832  372740.908    315319.244   57421.664
     5              197647.498    169207.043  28440.455  395294.996    338414.086   56880.910
     6              215334.156    187818.485  27515.672  430668.312    375636.970   55031.344
     7              242953.552    217555.387  25398.166  485907.104    435110.774   50796.332
     8              225402.481    202918.849  22483.632  450804.962    405837.698   44967.264
     9              206905.101    184683.194  22221.906  413810.202    369366.388   44443.812
     10             197959.776    175546.413  22413.363  395919.552    351092.826   44826.726
     11             196653.686    172497.297  24156.389  393307.372    344994.594   48312.778
     12             213786.542    186564.333  27222.208  427573.084    373128.666   54444.416
1987 1              223040.975    196320.233  26720.743  446081.950    392640.466   53441.486
     2              194280.625    171867.773  22412.852  388561.250    343735.546   44825.704
     3              202129.944    177567.017  24562.927  404259.888    355134.034   49125.854
     4              189792.417    166505.245  23287.172  379584.834    333010.490   46574.344
     5              206406.878    180860.205  25546.673  412813.756    361720.410   51093.346
     6              225907.915    203655.654  22252.261  451815.830    407311.308   44504.522
     7              248196.221    226617.387  21578.831  496392.442    453234.774   43157.662
     8              247880.760    228097.254  19783.505  495761.520    456194.508   39567.010
     9              213221.249    193816.902  19404.348  426442.498    387633.804   38808.696
     10             203214.924    184039.018  19175.907  406429.848    368078.036   38351.814
     11             200479.386    182418.013  18061.373  400958.772    364836.026   36122.746
     12             220736.372    198400.343  22336.027  441472.744    396800.686   44672.054
1988 1              238188.434    214831.396  23357.039  476376.868    429662.792   46714.078
     2              217183.084    196933.566  20249.517  434366.168    393867.132   40499.034
     3              214293.615    193458.206  20835.409  428587.230    386916.412   41670.818
     4              196297.111    175937.532  20359.579  392594.222    351875.064   40719.158
     5              208703.604    186210.541  22493.063  417407.208    372421.082   44986.126
     6              233065.853    212909.796  20156.057  466131.706    425819.592   40312.114
     7              257742.125    239473.233  18268.892  515484.250    478946.466   36537.784
     8              267928.593    250181.573  17747.021  535857.186    500363.146   35494.042
     9              220392.242    202907.526  17484.716  440784.484    405815.052   34969.432
     10             210813.885    194482.223  16331.662  421627.770    388964.446   32663.324
     11             209814.992    190142.092  19672.899  419629.984    380284.184   39345.798
     12             232987.639    211858.403  21129.235  465975.278    423716.806   42258.470
1989 1              246766.176    220606.033  25834.867  493532.352    441212.066   51669.734
     2              233782.777    210255.368  23233.611  467565.554    420510.736   46467.222
     3              241946.410    213859.999  27761.137  483892.820    427719.998   55522.274
     4              222868.586    193745.197  28808.607  445737.172    387490.394   57617.214
     5              234824.770    201878.053  32621.442  469649.540    403756.106   65242.884
     6              250919.110    219925.473  30678.854  501838.220    439850.946   61357.708
     7              273457.735    245462.320  27670.139  546915.470    490924.640   55340.278
     8              275419.519    249672.628  25421.615  550839.038    499345.256   50843.230
     9              242793.798    218391.488  24087.527  485587.596    436782.976   48175.054
     10             235669.018    209932.706  25411.036  471338.036    419865.412   50822.072
     11             234249.810    207344.277  26590.750  468499.620    414688.554   53181.500
     12             274448.378    246910.116  27212.986  548896.756    493820.232   54425.972
1990 1              255187.021    225023.305  29856.630  510374.042    450046.610   59713.260
     2              229499.204    198832.324  30389.514  458998.408    397664.648   60779.028
     3              244761.483    209625.621  34828.779  489522.966    419251.242   69657.558
     4              229769.727    197740.239  31732.310  459539.454    395480.478   63464.620
     5              241773.529    208595.292  32871.153  483547.058    417190.584   65742.306
     6              268992.258    235697.321  32997.759  537984.516    471394.642   65995.518

In [80]:
# pd.pivot_table(df5, values="Net_elec_generation", index=pd.Grouper(freq="M", key="year"), columns="year")

In [81]:
# pd.pivot_table(df5, values="Total", index=["year", "month"], columns=["source"])

In [82]:
# pd.pivot_table(df5, values="Total", index=["year", "month"], columns=["range"],aggfunc=np.sum)

In [83]:
# pd.pivot_table(df20, values=["non-renewable","renewable"], index=["month"], columns=["year","source"],aggfunc=np.sum)

In [84]:
# pd.pivot_table(df5, values='Total', index=["year"], columns=["range","month"],aggfunc=np.sum)

In [85]:
# df20 = pd.DataFrame(
#     {
#         "A": ["one", "one", "two", "three"] * 6,
#         "B": ["A", "B", "C"] * 8,
#         "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 4,
#         "D": np.random.randn(24),
#         "E": np.random.randn(24),
       
#     }
# )

In [86]:
# df20[:10]

In [87]:
# pd.pivot_table(df20, values="D", index=["A", "B"], columns=["C"])

In [88]:
# pd.pivot_table(df20, values="D", index=["B"], columns=["A", "C"])

In [89]:
# pd.pivot_table(df20, values="D", index=["B"], columns=["A", "C"], aggfunc=np.sum)

### 5.1 Adding margins

In [90]:
tab= df5.pivot_table(values=["Net_elec_generation", "net_elec*2"],index=["year","month"], columns=["source"],margins=True,aggfunc=np.mean)
tab

           Net_elec_generation                                              \
source                   Total  non-renewable     renewable            All
year month
1973 1           160217.989000  133804.986000  26413.002000  106811.992333
     2           143538.699000  120065.492000  23473.208000   95692.466333
     3           148158.370000  122113.112000  26045.257000   98772.246333
     4           139589.440000  115037.131000  24552.309000   93059.626667
     5           147395.124000  122121.797000  25273.326000   98263.415667
...                        ...            ...           ...            ...
2022 1           378966.702000  299155.908000  78793.520000  252305.376667
     2           327766.846000  250675.859000  76200.267000  218214.324000
     3           325952.002000  238240.679000  86739.642000  216977.441000
     4           304348.709000  218421.044000  85004.357000  202591.370000
All              274140.774188  240052.508899  33537.541399  182576.941495

               net_elec*2
source              Total  non-renewable      renewable            All
year month
1973 1      320435.978000  267609.972000   52826.004000  213623.984667
     2      287077.398000  240130.984000   46946.416000  191384.932667
     3      296316.740000  244226.224000   52090.514000  197544.492667
     4      279178.880000  230074.262000   49104.618000  186119.253333
     5      294790.248000  244243.594000   50546.652000  196526.831333
...                   ...            ...            ...            ...
2022 1      757933.404000  598311.816000  157587.040000  504610.753333
     2      655533.692000  501351.718000  152400.534000  436428.648000
     3      651904.004000  476481.358000  173479.284000  433954.882000
     4      608697.418000  436842.088000  170008.714000  405182.740000
All         548281.548375  480105.017797   67075.082797  365153.882990

[593 rows x 8 columns]

In [91]:
tab.stack()

                          Net_elec_generation     net_elec*2
year month source
1973 1     All                  106811.992333  213623.984667
           Total                160217.989000  320435.978000
           non-renewable        133804.986000  267609.972000
           renewable             26413.002000   52826.004000
     2     All                   95692.466333  191384.932667
...                                       ...            ...
2022 4     renewable             85004.357000  170008.714000
All        All                  182576.941495  365153.882990
           Total                274140.774188  548281.548375
           non-renewable        240052.508899  480105.017797
           renewable             33537.541399   67075.082797

[2372 rows x 2 columns]

### 6. Cross tabulations

In [92]:
df6= df2
# # mean = df5['Total'].mean()

In [93]:
df6['tot_range'] = 'Low'
df6['ren_range'] = 'low'
df6['non-ren_range'] = 'lo'

In [94]:
df6['tot_range'][df6['Total']>=df6['Total'].mean()] = 'High'
df6['ren_range'][df6['renewable']>=df6['renewable'].mean()] = 'high'
df6['non-ren_range'][df6['non-renewable']>=df6['non-renewable'].mean()] = 'hi'

C:\Users\reddy\AppData\Local\Temp\ipykernel_15032\1605494091.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['tot_range'][df6['Total']>=df6['Total'].mean()] = 'High'
C:\Users\reddy\AppData\Local\Temp\ipykernel_15032\1605494091.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['ren_range'][df6['renewable']>=df6['renewable'].mean()] = 'high'
C:\Users\reddy\AppData\Local\Temp\ipykernel_15032\1605494091.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['non-ren_range'][df6['non-renewable']>=df6['non-renewable'].mean()] = 'hi'

In [95]:
df6

,Total,month,year,non-renewable,renewable,tot_range,ren_range,non-ren_range
0,160217.989,1,1973,133804.986,26413.002,Low,low,lo
1,143538.699,2,1973,120065.492,23473.208,Low,low,lo
2,148158.370,3,1973,122113.112,26045.257,Low,low,lo
3,139589.440,4,1973,115037.131,24552.309,Low,low,lo
4,147395.124,5,1973,122121.797,25273.326,Low,low,lo
...,...,...,...,...,...,...,...,...
587,339684.017,12,2021,260132.691,78475.696,High,high,hi
588,378966.702,1,2022,299155.908,78793.520,High,high,hi
589,327766.846,2,2022,250675.859,76200.267,High,high,hi
590,325952.002,3,2022,238240.679,86739.642,High,high,lo
591,304348.709,4,2022,218421.044,85004.357,High,high,lo

In [96]:
month = np.array(df6['month'])
year = np.array(df6['year'])
tot_range = np.array(df6['tot_range'])
ren_range = np.array(df6['ren_range'])
non_ren_range = np.array(df6['non-ren_range'])

In [97]:
pd.crosstab(month, [tot_range, ren_range,non_ren_range], rownames=["month"], colnames=["tot_range", "ren_range","non-ren_range"])

tot_range     High         Low
ren_range     high    low high low
non-ren_range   hi lo  hi   lo  hi  lo
month
1               20  0   9    0   0  21
2               12  1  11    3   0  23
3               14  3   9    3   0  21
4                9  7   8    3   0  23
5               21  1   3    3   0  21
6               23  0   6    0   0  20
7               19  0  13    0   1  16
8               13  0  20    0   1  15
9               10  0  17    0   1  21
10              11  0  14    0   1  23
11              11  1  10    0   3  24
12              15  0  13    0   2  19

In [98]:
pd.crosstab([month,tot_range], [ren_range,non_ren_range], rownames=["month",'tot_range'], colnames=[ "ren_range","non-ren_range"])

ren_range       high    low
non-ren_range     hi lo  hi  lo
month tot_range
1     High        20  0   9   0
      Low          0  0   0  21
2     High        12  1  11   0
      Low          0  3   0  23
3     High        14  3   9   0
      Low          0  3   0  21
4     High         9  7   8   0
      Low          0  3   0  23
5     High        21  1   3   0
      Low          0  3   0  21
6     High        23  0   6   0
      Low          0  0   0  20
7     High        19  0  13   0
      Low          0  0   1  16
8     High        13  0  20   0
      Low          0  0   1  15
9     High        10  0  17   0
      Low          0  0   1  21
10    High        11  0  14   0
      Low          0  0   1  23
11    High        11  1  10   0
      Low          0  0   3  24
12    High        15  0  13   0
      Low          0  0   2  19

In [99]:
pd.crosstab(df6['month'],df6['tot_range']) 
#If crosstab() receives only two Series, it will provide a frequency table.

tot_range  High  Low
month
1            29   21
2            24   26
3            26   24
4            24   26
5            25   24
6            29   20
7            32   17
8            33   16
9            27   22
10           25   24
11           22   27
12           28   21

In [100]:
# crosstab() can also be implemented to Categorical data.
pd.crosstab(ren_range,non_ren_range)

col_0   hi   lo
row_0
high   178   25
low    142  247

### 6.1 Normalization

###### Frequency tables can also be normalized to show percentages rather than counts using the normalize argument:

In [101]:
pd.crosstab(df6['month'],df6['tot_range'], normalize=True)

tot_range      High       Low
month
1          0.048986  0.035473
2          0.040541  0.043919
3          0.043919  0.040541
4          0.040541  0.043919
5          0.042230  0.040541
6          0.048986  0.033784
7          0.054054  0.028716
8          0.055743  0.027027
9          0.045608  0.037162
10         0.042230  0.040541
11         0.037162  0.045608
12         0.047297  0.035473

###### can also normalize values within each row or column:

In [102]:
pd.crosstab(df6['month'],df6['tot_range'], normalize='columns')

tot_range      High       Low
month
1          0.089506  0.078358
2          0.074074  0.097015
3          0.080247  0.089552
4          0.074074  0.097015
5          0.077160  0.089552
6          0.089506  0.074627
7          0.098765  0.063433
8          0.101852  0.059701
9          0.083333  0.082090
10         0.077160  0.089552
11         0.067901  0.100746
12         0.086420  0.078358

In [103]:
pd.crosstab(df6['month'],df6['tot_range'], normalize='index')

tot_range      High       Low
month
1          0.580000  0.420000
2          0.480000  0.520000
3          0.520000  0.480000
4          0.480000  0.520000
5          0.510204  0.489796
6          0.591837  0.408163
7          0.653061  0.346939
8          0.673469  0.326531
9          0.551020  0.448980
10         0.510204  0.489796
11         0.448980  0.551020
12         0.571429  0.428571

###### can also be passed a third Series and an aggregation function (aggfunc) that will be applied to the values of the third Series within each group defined by the first two Series

In [104]:
pd.crosstab(df6['month'],df6['year'],values=df6['Total'],aggfunc=np.sum)

year,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
month,,,,,,,,,,,,,,,,,,,,,
1,160217.989,157554.691,164623.080,178608.612,196665.182,198107.635,209986.749,200296.330,206758.205,209694.373,...,348967.378,377254.711,360455.167,352719.066,344332.034,373230.280,359509.234,341850.206,350795.813,378966.702
2,143538.699,142748.458,147349.000,156965.799,162949.088,173745.731,186587.309,188961.379,179859.910,180545.573,...,309728.080,324348.436,334475.546,313685.401,291049.672,306894.214,315026.484,319550.114,326223.389,327766.846
3,148158.370,150342.206,155760.211,164466.676,169437.171,173460.887,183154.004,187744.800,185833.882,187967.965,...,325398.834,331823.059,324191.894,304389.581,319335.755,321546.954,326657.208,309586.723,312284.622,325952.002
4,139589.440,142311.633,146494.879,153467.392,157117.355,160012.982,170260.472,169016.585,172841.342,172876.502,...,299332.868,297630.588,294133.343,292893.550,295360.591,300756.440,296662.569,279583.265,292503.539,304348.709
5,147395.124,153812.873,153531.080,157664.467,169596.403,175548.628,178409.356,176066.486,178138.553,177479.981,...,322155.640,324724.300,322086.912,316784.457,323446.738,338947.606,330423.048,304593.238,318858.513,NaN
6,161243.674,156440.089,162716.960,173673.719,181031.212,188585.386,186976.379,189748.486,203020.751,186447.119,...,356822.647,357844.043,362409.202,367781.196,358522.007,371885.761,352988.074,351744.930,373754.405,NaN
7,173733.007,178247.304,177056.505,186691.040,199167.726,202947.293,202522.477,217057.853,220654.747,210865.079,...,394845.621,385779.552,400418.853,411886.942,404432.474,411290.320,410037.810,409561.700,404748.717,NaN
8,177365.364,174119.001,179930.892,186638.696,196363.166,206658.749,205100.592,215629.382,210639.415,205891.676,...,385285.745,384341.148,392116.203,409700.812,384738.580,408027.757,401429.694,398279.697,413353.176,NaN
9,156875.032,152467.442,155440.826,165237.437,176497.560,185802.058,180974.646,191697.740,187051.489,180875.268,...,340940.902,339886.506,350121.648,351484.468,335914.910,356258.302,360518.468,333258.048,348200.651,NaN
10,154197.466,152195.832,155187.742,164009.445,166645.282,176013.116,179953.363,178761.034,181557.590,173172.248,...,314925.463,314521.999,312111.680,312945.164,318669.649,324931.943,320351.885,313531.271,319638.396,NaN
11,148137.609,150070.855,153035.097,169346.291,167388.072,176389.093,177769.508,178771.361,175791.753,173598.759,...,314539.642,317495.009,300653.268,297061.772,308052.342,322368.657,315849.092,301250.181,315494.917,NaN
12,153604.858,160009.019,169628.296,184144.107,184589.270,192105.353,188970.171,195848.927,195825.699,184957.943,...,353021.248,337956.656,324427.224,345342.577,350415.808,342139.112,338401.647,344346.095,339684.017,NaN

### 6.2 Adding margins

###### Finally, one can also add margins or normalize this output.

In [105]:
pd.crosstab(df6['month'],df6['year'],values=df6['Total'],aggfunc=np.sum,normalize=True,margins=True)

year,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,All
month,,,,,,,,,,,,,,,,,,,,,
1,0.000987,0.000971,0.001014,0.001101,0.001212,0.001221,0.001294,0.001234,0.001274,0.001292,...,0.002325,0.002221,0.002173,0.002122,0.002300,0.002215,0.002106,0.002162,0.002335,0.088447
2,0.000884,0.000880,0.000908,0.000967,0.001004,0.001071,0.001150,0.001164,0.001108,0.001112,...,0.001999,0.002061,0.001933,0.001793,0.001891,0.001941,0.001969,0.002010,0.002020,0.078326
3,0.000913,0.000926,0.000960,0.001013,0.001044,0.001069,0.001129,0.001157,0.001145,0.001158,...,0.002045,0.001998,0.001876,0.001968,0.001981,0.002013,0.001908,0.001924,0.002008,0.080332
4,0.000860,0.000877,0.000903,0.000946,0.000968,0.000986,0.001049,0.001041,0.001065,0.001065,...,0.001834,0.001812,0.001805,0.001820,0.001853,0.001828,0.001723,0.001802,0.001875,0.074766
5,0.000908,0.000948,0.000946,0.000971,0.001045,0.001082,0.001099,0.001085,0.001098,0.001094,...,0.002001,0.001985,0.001952,0.001993,0.002089,0.002036,0.001877,0.001965,0.000000,0.078892
6,0.000994,0.000964,0.001003,0.001070,0.001115,0.001162,0.001152,0.001169,0.001251,0.001149,...,0.002205,0.002233,0.002266,0.002209,0.002291,0.002175,0.002167,0.002303,0.000000,0.086805
7,0.001071,0.001098,0.001091,0.001150,0.001227,0.001251,0.001248,0.001337,0.001360,0.001299,...,0.002377,0.002467,0.002538,0.002492,0.002534,0.002527,0.002524,0.002494,0.000000,0.096157
8,0.001093,0.001073,0.001109,0.001150,0.001210,0.001273,0.001264,0.001329,0.001298,0.001269,...,0.002368,0.002416,0.002524,0.002371,0.002514,0.002474,0.002454,0.002547,0.000000,0.095700
9,0.000967,0.000939,0.000958,0.001018,0.001088,0.001145,0.001115,0.001181,0.001153,0.001115,...,0.002094,0.002157,0.002166,0.002070,0.002195,0.002221,0.002053,0.002146,0.000000,0.082868
10,0.000950,0.000938,0.000956,0.001011,0.001027,0.001085,0.001109,0.001101,0.001119,0.001067,...,0.001938,0.001923,0.001928,0.001964,0.002002,0.001974,0.001932,0.001970,0.000000,0.077735
11,0.000913,0.000925,0.000943,0.001043,0.001031,0.001087,0.001095,0.001102,0.001083,0.001070,...,0.001956,0.001853,0.001830,0.001898,0.001986,0.001946,0.001856,0.001944,0.000000,0.076059
12,0.000946,0.000986,0.001045,0.001135,0.001137,0.001184,0.001164,0.001207,0.001207,0.001140,...,0.002082,0.001999,0.002128,0.002159,0.002108,0.002085,0.002122,0.002093,0.000000,0.083913
All,0.011486,0.011524,0.011835,0.012576,0.013109,0.013614,0.013868,0.014108,0.014160,0.013829,...,0.025224,0.025125,0.025119,0.024858,0.025746,0.025435,0.024691,0.025359,0.008238,1.000000

### 7. Tiling

In [106]:
import numpy as np
arr_tot = np.array(df['Total'])

In [107]:
arr_tot

array([160217.989, 143538.699, 148158.37 , 139589.44 , 147395.124,
       161243.674, 173733.007, 177365.364, 156875.032, 154197.466,
       148137.609, 153604.858, 157554.691, 142748.458, 150342.206,
       142311.633, 153812.873, 156440.089, 178247.304, 174119.001,
       152467.442, 152195.832, 150070.855, 160009.019, 164623.08 ,
       147349.   , 155760.211, 146494.879, 153531.08 , 162716.96 ,
       177056.505, 179930.892, 155440.826, 155187.742, 153035.097,
       169628.296, 178608.612, 156965.799, 164466.676, 153467.392,
       157664.467, 173673.719, 186691.04 , 186638.696, 165237.437,
       164009.445, 169346.291, 184144.107, 196665.182, 162949.088,
       169437.171, 157117.355, 169596.403, 181031.212, 199167.726,
       196363.166, 176497.56 , 166645.282, 167388.072, 184589.27 ,
       198107.635, 173745.731, 173460.887, 160012.982, 175548.628,
       188585.386, 202947.293, 206658.749, 185802.058, 176013.116,
       176389.093, 192105.353, 209986.749, 186587.309, 183154.004,
       170260.472, 178409.356, 186976.379, 202522.477, 205100.592,
       180974.646, 179953.363, 177769.508, 188970.171, 200296.33 ,
       188961.379, 187744.8  , 169016.585, 176066.486, 189748.486,
       217057.853, 215629.382, 191697.74 , 178761.034, 178771.361,
       195848.927, 206758.205, 179859.91 , 185833.882, 172841.342,
       178138.553, 203020.751, 220654.747, 210639.415, 187051.489,
       181557.59 , 175791.753, 195825.699, 209694.373, 180545.573,
       187967.965, 172876.502, 177479.981, 186447.119, 210865.079,
       205891.676, 180875.268, 173172.248, 173598.759, 184957.943,
       195870.844, 172725.19 , 182768.722, 170668.876, 174724.813,
       191367.206, 220446.836, 230193.46 , 195817.014, 183136.711,
       183170.681, 212555.333, 216923.729, 189810.043, 200387.475,
       181381.139, 192550.198, 209967.314, 221526.162, 229531.666,
       195411.388, 191142.43 , 190601.865, 200231.958, 228147.888,
       198488.497, 195250.388, 185173.312, 197122.843, 205681.971,
       227003.762, 226286.447, 202712.422, 194995.217, 192648.952,
       219490.423, 217761.136, 192582.016, 197114.555, 186370.454,
       197647.498, 215334.156, 242953.552, 225402.481, 206905.101,
       197959.776, 196653.686, 213786.542, 223040.975, 194280.625,
       202129.944, 189792.417, 206406.878, 225907.915, 248196.221,
       247880.76 , 213221.249, 203214.924, 200479.386, 220736.372,
       238188.434, 217183.084, 214293.615, 196297.111, 208703.604,
       233065.853, 257742.125, 267928.593, 220392.242, 210813.885,
       209814.992, 232987.639, 246766.176, 233782.777, 241946.41 ,
       222868.586, 234824.77 , 250919.11 , 273457.735, 275419.519,
       242793.798, 235669.018, 234249.81 , 274448.378, 255187.021,
       229499.204, 244761.483, 229769.727, 241773.529, 268992.258,
       287447.762, 290655.259, 258356.632, 244372.25 , 231242.377,
       255769.835, 269214.313, 228290.131, 240561.216, 227798.971,
       254873.018, 269099.254, 294647.834, 292158.58 , 256027.328,
       245378.242, 241661.365, 254088.633, 267772.67 , 239514.031,
       247733.163, 233405.563, 242411.928, 261076.926, 293616.745,
       281927.43 , 259925.035, 244993.925, 244161.999, 267342.791,
       271020.902, 248015.328, 261247.551, 234695.127, 244325.583,
       275359.6  , 312224.835, 311450.19 , 264032.481, 250552.792,
       252102.138, 272164.57 , 289768.406, 249172.29 , 257998.052,
       240636.581, 252744.936, 294161.782, 311256.823, 307604.584,
       266262.327, 256528.49 , 251868.348, 269519.769, 279773.101,
       252307.149, 261342.562, 244735.923, 264288.242, 286258.135,
       330416.095, 345780.079, 277575.357, 263978.44 , 261478.399,
       285553.882, 296922.971, 270685.247, 275019.018, 251612.875,
       282266.414, 302716.899, 327708.462, 329286.33 , 283151.263,
       271446.494, 269122.035, 284249.613, 300573.901, 258131.029,
       272258.227, 258284.482, 272913.783, 299091.561, 344516.455,
       332898.63 , 301056.672, 284970.629, 271120.816, 296356.097,
       295260.404, 260589.918, 286877.989, 261229.604, 299639.908,
       328903.002, 361936.46 , 357365.61 , 318924.466, 284445.547,
       267136.408, 297986.181, 315813.69 , 274820.273, 298144.718,
       280719.013, 300098.19 , 328923.833, 376538.308, 364031.383,
       305515.654, 283934.839, 271095.672, 295174.237, 327993.944,
       294169.282, 301579.821, 285577.749, 322953.681, 339053.66 ,
       356527.917, 368669.365, 312446.647, 289451.903, 284670.275,
       319010.798, 332493.16 , 282940.198, 300706.544, 278078.871,
       300491.621, 327693.978, 357613.7  , 370532.828, 306928.866,
       294733.613, 278933.942, 305496.328, 319941.472, 281825.708,
       302549.007, 289848.252, 307674.569, 341023.145, 381542.109,
       374585.823, 331279.434, 307059.462, 296289.561, 324833.704,
       341988.899, 299248.775, 304317.263, 285755.7  , 307544.887,
       328693.699, 374396.049, 381816.318, 323135.536, 306740.934,
       297866.713, 331680.431, 346545.627, 314279.91 , 308812.096,
       290559.914, 327380.264, 345085.079, 377331.697, 368439.037,
       335622.198, 312450.223, 302101.256, 341947.963, 343121.453,
       298500.316, 317458.276, 289562.4  , 315062.11 , 363671.636,
       402273.846, 404940.681, 350217.801, 316397.924, 306115.236,
       348101.071, 328657.739, 307333.43 , 318729.8  , 297858.078,
       330615.57 , 364259.798, 410420.793, 407762.536, 332055.321,
       321567.091, 309158.826, 336283.246, 353531.095, 323230.395,
       320471.243, 303129.064, 330202.758, 362754.877, 393226.432,
       421796.659, 355393.912, 332615.416, 314102.543, 346290.331,
       362998.429, 325105.597, 324629.85 , 305865.031, 325244.802,
       373109.027, 402900.336, 388986.719, 338056.13 , 318547.343,
       310046.241, 343898.254, 354992.636, 300887.398, 310602.964,
       289537.255, 311305.872, 347658.241, 372542.226, 381221.417,
       327400.612, 307040.341, 296634.67 , 350507.295, 360957.167,
       319734.727, 312167.64 , 287800.227, 327936.492, 375759.478,
       409725.44 , 408884.155, 346045.172, 307920.691, 306009.629,
       362119.081, 362871.893, 313126.607, 318709.941, 302400.724,
       323628.238, 367727.015, 418692.755, 406511.315, 337931.318,
       308698.504, 304102.155, 335740.463, 339528.259, 309389.42 ,
       309090.569, 295228.216, 336517.631, 360826.151, 414639.671,
       395699.566, 334584.877, 311650.774, 305975.035, 334635.089,
       348967.378, 309728.08 , 325398.834, 299332.868, 322155.64 ,
       356822.647, 394845.621, 385285.745, 340940.902, 314925.463,
       314539.642, 353021.248, 377254.711, 324348.436, 331823.059,
       297630.588, 324724.3  , 357844.043, 385779.552, 384341.148,
       339886.506, 314521.999, 317495.009, 337956.656, 360455.167,
       334475.546, 324191.894, 294133.343, 322086.912, 362409.202,
       400418.853, 392116.203, 350121.648, 312111.68 , 300653.268,
       324427.224, 352719.066, 313685.401, 304389.581, 292893.55 ,
       316784.457, 367781.196, 411886.942, 409700.812, 351484.468,
       312945.164, 297061.772, 345342.577, 344332.034, 291049.672,
       319335.755, 295360.591, 323446.738, 358522.007, 404432.474,
       384738.58 , 335914.91 , 318669.649, 308052.342, 350415.808,
       373230.28 , 306894.214, 321546.954, 300756.44 , 338947.606,
       371885.761, 411290.32 , 408027.757, 356258.302, 324931.943,
       322368.657, 342139.112, 359509.234, 315026.484, 326657.208,
       296662.569, 330423.048, 352988.074, 410037.81 , 401429.694,
       360518.468, 320351.885, 315849.092, 338401.647, 341850.206,
       319550.114, 309586.723, 279583.265, 304593.238, 351744.93 ,
       409561.7  , 398279.697, 333258.048, 313531.271, 301250.181,
       344346.095, 350795.813, 326223.389, 312284.622, 292503.539,
       318858.513, 373754.405, 404748.717, 413353.176, 348200.651,
       319638.396, 315494.917, 339684.017, 378966.702, 327766.846,
       325952.002, 304348.709])

In [108]:
pd.cut(arr_tot,bins=100)  #equal-width bins are formed

[(159343.945, 162166.018], (142411.512, 145233.584], (148055.657, 150877.729], (139307.233, 142411.512], (145233.584, 148055.657], ..., (337134.493, 339956.565], (376643.504, 379465.576], (325846.205, 328668.277], (325846.205, 328668.277], (303269.627, 306091.699]]
Length: 592
Categories (100, interval[float64, right]): [(139307.233, 142411.512] < (142411.512, 145233.584] < (145233.584, 148055.657] < (148055.657, 150877.729] ... (410508.37, 413330.442] < (413330.442, 416152.515] < (416152.515, 418974.587] < (418974.587, 421796.659]]

In [109]:
pd.cut(arr_tot,bins=[0,])

[NaN, NaN, NaN, NaN, NaN, ..., NaN, NaN, NaN, NaN, NaN]
Length: 592
Categories (0, interval[int64, right]): []

### 8. Computing indicator / dummy variables

In [184]:
df9 = pd.DataFrame({"key": list("bbacab"), "data1": range(6)})

In [185]:
df9

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [187]:
pd.get_dummies(df9["key"])

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [254]:
df8= df3.drop('tot_range ren_range non-ren_range'.split(),axis=1).melt(id_vars=['month','year'],var_name="source",value_name="Net_elec_generation")
# df20= df8.drop(['year','month'],axis=1)
# df20 = df20.sample(frac = 1)
# df20= df20.reset_index()
# #20['index']

In [255]:
df8

      month  year     source  Net_elec_generation
0         1  1973      Total           160217.989
1         2  1973      Total           143538.699
2         3  1973      Total           148158.370
3         4  1973      Total           139589.440
4         5  1973      Total           147395.124
...     ...   ...        ...                  ...
1771     12  2021  renewable            78475.696
1772      1  2022  renewable            78793.520
1773      2  2022  renewable            76200.267
1774      3  2022  renewable            86739.642
1775      4  2022  renewable            85004.357

[1776 rows x 4 columns]

In [256]:
df8 = df8.sample(frac = 1)
df8= df8.reset_index()

In [257]:
df8

      index  month  year         source  Net_elec_generation
0      1341      2  1986      renewable            24424.420
1       993      6  2006  non-renewable           326078.673
2      1408      9  1991      renewable            25711.324
3      1487      4  1998      renewable            34045.670
4       137      6  1984          Total           209967.314
...     ...    ...   ...            ...                  ...
1771    511      8  2015          Total           392116.203
1772    226     11  1991          Total           241661.365
1773   1183      4  2022  non-renewable           218421.044
1774   1005      6  2007  non-renewable           330878.145
1775    334     11  2000          Total           284670.275

[1776 rows x 5 columns]

In [258]:
df8 =df8.drop('index'.split(),axis=1)

In [259]:
df8

      month  year         source  Net_elec_generation
0         2  1986      renewable            24424.420
1         6  2006  non-renewable           326078.673
2         9  1991      renewable            25711.324
3         4  1998      renewable            34045.670
4         6  1984          Total           209967.314
...     ...   ...            ...                  ...
1771      8  2015          Total           392116.203
1772     11  1991          Total           241661.365
1773      4  2022  non-renewable           218421.044
1774      6  2007  non-renewable           330878.145
1775     11  2000          Total           284670.275

[1776 rows x 4 columns]

In [260]:
pd.get_dummies(df8["source"])

      Total  non-renewable  renewable
0         0              0          1
1         0              1          0
2         0              0          1
3         0              0          1
4         1              0          0
...     ...            ...        ...
1771      1              0          0
1772      1              0          0
1773      0              1          0
1774      0              1          0
1775      1              0          0

[1776 rows x 3 columns]

In [262]:
pd.get_dummies(df8["month"])

      1   2   3   4   5   6   7   8   9   10  11  12
0      0   1   0   0   0   0   0   0   0   0   0   0
1      0   0   0   0   0   1   0   0   0   0   0   0
2      0   0   0   0   0   0   0   0   1   0   0   0
3      0   0   0   1   0   0   0   0   0   0   0   0
4      0   0   0   0   0   1   0   0   0   0   0   0
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
1771   0   0   0   0   0   0   0   1   0   0   0   0
1772   0   0   0   0   0   0   0   0   0   0   1   0
1773   0   0   0   1   0   0   0   0   0   0   0   0
1774   0   0   0   0   0   1   0   0   0   0   0   0
1775   0   0   0   0   0   0   0   0   0   0   1   0

[1776 rows x 12 columns]

In [193]:
pd.get_dummies(df8["year"])

,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1771,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1772,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1773,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1774,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1775,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [263]:
# df8=df8.drop('non-renewable renewable '.split(),axis=1)

In [ ]:
# df8['id'] = df8.index
# df8['range'] ='low'

# df8['range'][df['Total']>=df['Total'].mean()] ='high'

In [264]:
# df8

In [265]:
# pd.get_dummies(df8['range'])

In [266]:
# df10 = df3.melt(id_vars=['month','year'],var_name="source",value_name="Net_elec_generation")

In [267]:
# df10

### 9. Factorizing Values

In [269]:
df9= df8
df9

      month  year         source  Net_elec_generation
0         2  1986      renewable            24424.420
1         6  2006  non-renewable           326078.673
2         9  1991      renewable            25711.324
3         4  1998      renewable            34045.670
4         6  1984          Total           209967.314
...     ...   ...            ...                  ...
1771      8  2015          Total           392116.203
1772     11  1991          Total           241661.365
1773      4  2022  non-renewable           218421.044
1774      6  2007  non-renewable           330878.145
1775     11  2000          Total           284670.275

[1776 rows x 4 columns]

In [273]:
ser = pd.Series(df9['year'])
ser.drop

0       1986
1       2006
2       1991
3       1998
4       1984
        ...
1771    2015
1772    1991
1773    2022
1774    2007
1775    2000
Name: year, Length: 1775, dtype: int64

In [271]:
labels, uniques = pd.factorize(ser)

### 10. Examples

In [130]:
# df10= df5
# df10 = df10[df10['source']!= 'id']
# df10[df10['year']==2022]
df5

     month  year     source  Net_elec_generation  net_elec*2
0        1  1973      Total           160217.989  320435.978
1        2  1973      Total           143538.699  287077.398
2        3  1973      Total           148158.370  296316.740
3        4  1973      Total           139589.440  279178.880
4        5  1973      Total           147395.124  294790.248
..     ...   ...        ...                  ...         ...
587     12  2021  renewable            78475.696  156951.392
588      1  2022  renewable            78793.520  157587.040
589      2  2022  renewable            76200.267  152400.534
590      3  2022  renewable            86739.642  173479.284
591      4  2022  renewable            85004.357  170008.714

[1776 rows x 5 columns]

In [114]:
df10.isnull().sum()

month                  0
year                   0
source                 0
Net_elec_generation    0
net_elec*2             0
dtype: int64

### 10.1 Pivoting with single aggregations

In [115]:
df10.pivot_table(values="Net_elec_generation", index="year", columns="source", aggfunc="mean")

source          Total  non-renewable     renewable
year
1973    155338.052667  132194.337333  23143.715000
1974    155859.950250  130283.690833  25576.259750
1975    160062.880667  134513.717167  25549.163750
1976    170076.140083  145842.214333  24233.925750
1977    177287.290583  158315.463250  18971.827167
1978    184114.742583  160216.369083  23898.373417
1979    187555.418833  163600.169167  23955.249583
1980    190800.030250  167076.002750  23724.027417
1981    191497.778000  169006.223583  22491.554833
1982    187031.040500  160569.557500  26461.483000
1983    192787.140500  164308.203917  28478.936500
1984    201622.113917  173876.317417  27745.796333
1985    206083.510167  181497.257333  24586.252583
1986    207539.246083  182080.234667  25459.011583
1987    214607.305500  192513.753667  22093.551583
1988    225617.598083  205777.173917  19840.424083
1989    247262.173917  219831.971500  27111.047583
1990    253152.278083  223373.444750  29477.527417
1991    256149.907083  226319.001750  29436.001667
1992    256990.183833  229790.089583  26890.104417
1993    266432.591417  236752.684667  29389.309833
1994    270626.865667  242547.701083  27773.587750
1995    279457.280333  247275.879417  31839.416500
1996    287015.635083  251728.896333  34989.132083
1997    291014.356833  254913.673500  35799.684500
1998    301691.291417  268397.274750  32996.398917
1999    307900.817500  274826.992417  32738.511083
2000    316842.086833  287197.618083  29244.976250
2001    311386.970750  287152.588583  23242.186917
2002    321537.687167  292519.188667  27891.256083
2003    323598.767000  293531.887583  28896.503667
2004    330879.605333  301110.536417  28583.035083
2005    337951.895833  307625.735333  29257.738750
2006    338725.185667  306042.813750  31601.171833
2007    346395.393750  316555.205167  28820.927917
2008    343282.313250  311078.314000  31220.360583
2009    329194.243917  293775.511833  34424.704583
2010    343754.991583  307527.467917  35156.245167
2011    341678.410667  298255.978833  42242.965000
2012    337313.771500  295362.957833  40801.891583
2013    338830.339000  294582.010833  43116.034667
2014    341133.833917  295644.911667  44367.147667
2015    339800.078333  293701.969417  44929.125083
2016    339722.915500  288346.814583  50229.914500
2017    336189.213333  278423.859417  56674.010667
2018    348189.778833  288699.405250  58409.273083
2019    343987.934417  282592.673583  60284.330167
2020    333927.955667  268049.843583  64806.846667
2021    342961.679583  273510.393500  68439.640167
2022    334258.564750  251623.372500  81684.446500

In [116]:
# df10.pivot_table(values="Net_elec_generation", index="year", columns="source", aggfunc="mean",fill_value=0)

In [117]:
df10.pivot_table(values="Net_elec_generation", index="source", columns="year", aggfunc="sum")

year,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
source,,,,,,,,,,,,,,,,,,,,,
Total,1864056.632,1870319.403,1920754.568,2040913.681,2127447.487,2209376.911,2250665.026,2289600.363,2297973.336,2244372.486,...,4065964.068,4093606.007,4077600.940,4076674.986,4034270.560,4178277.346,4127855.213,4007135.468,4115540.155,1337034.259
non-renewable,1586332.048,1563404.290,1614164.606,1750106.572,1899785.559,1922596.429,1963202.030,2004912.033,2028074.683,1926834.690,...,3534984.130,3547738.940,3524423.633,3460161.775,3341086.313,3464392.863,3391112.083,3216598.123,3282124.722,1006493.490
renewable,277724.580,306915.117,306589.965,290807.109,227661.926,286780.481,287462.995,284688.329,269898.658,317537.796,...,517392.416,532405.772,539149.501,602758.974,680088.128,700911.277,723411.962,777682.160,821275.682,326737.786

In [118]:
df10.pivot_table(index="source", columns="year", fill_value=0, aggfunc="size")

year,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
source,,,,,,,,,,,,,,,,,,,,,
Total,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,4
non-renewable,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,4
renewable,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,4

### 10.2 Pivoting with multiple aggregations

In [119]:
#for performing multiple aggregation
df10.pivot_table(values=['Net_elec_generation'],index="year", columns="source", fill_value=0, aggfunc=['mean','sum'])

                      mean                                              sum  \
       Net_elec_generation                              Net_elec_generation
source               Total  non-renewable     renewable               Total
year
1973         155338.052667  132194.337333  23143.715000         1864056.632
1974         155859.950250  130283.690833  25576.259750         1870319.403
1975         160062.880667  134513.717167  25549.163750         1920754.568
1976         170076.140083  145842.214333  24233.925750         2040913.681
1977         177287.290583  158315.463250  18971.827167         2127447.487
1978         184114.742583  160216.369083  23898.373417         2209376.911
1979         187555.418833  163600.169167  23955.249583         2250665.026
1980         190800.030250  167076.002750  23724.027417         2289600.363
1981         191497.778000  169006.223583  22491.554833         2297973.336
1982         187031.040500  160569.557500  26461.483000         2244372.486
1983         192787.140500  164308.203917  28478.936500         2313445.686
1984         201622.113917  173876.317417  27745.796333         2419465.367
1985         206083.510167  181497.257333  24586.252583         2473002.122
1986         207539.246083  182080.234667  25459.011583         2490470.953
1987         214607.305500  192513.753667  22093.551583         2575287.666
1988         225617.598083  205777.173917  19840.424083         2707411.177
1989         247262.173917  219831.971500  27111.047583         2967146.087
1990         253152.278083  223373.444750  29477.527417         3037827.337
1991         256149.907083  226319.001750  29436.001667         3073798.885
1992         256990.183833  229790.089583  26890.104417         3083882.206
1993         266432.591417  236752.684667  29389.309833         3197191.097
1994         270626.865667  242547.701083  27773.587750         3247522.388
1995         279457.280333  247275.879417  31839.416500         3353487.364
1996         287015.635083  251728.896333  34989.132083         3444187.621
1997         291014.356833  254913.673500  35799.684500         3492172.282
1998         301691.291417  268397.274750  32996.398917         3620295.497
1999         307900.817500  274826.992417  32738.511083         3694809.810
2000         316842.086833  287197.618083  29244.976250         3802105.042
2001         311386.970750  287152.588583  23242.186917         3736643.649
2002         321537.687167  292519.188667  27891.256083         3858452.246
2003         323598.767000  293531.887583  28896.503667         3883185.204
2004         330879.605333  301110.536417  28583.035083         3970555.264
2005         337951.895833  307625.735333  29257.738750         4055422.750
2006         338725.185667  306042.813750  31601.171833         4064702.228
2007         346395.393750  316555.205167  28820.927917         4156744.725
2008         343282.313250  311078.314000  31220.360583         4119387.759
2009         329194.243917  293775.511833  34424.704583         3950330.927
2010         343754.991583  307527.467917  35156.245167         4125059.899
2011         341678.410667  298255.978833  42242.965000         4100140.928
2012         337313.771500  295362.957833  40801.891583         4047765.258
2013         338830.339000  294582.010833  43116.034667         4065964.068
2014         341133.833917  295644.911667  44367.147667         4093606.007
2015         339800.078333  293701.969417  44929.125083         4077600.940
2016         339722.915500  288346.814583  50229.914500         4076674.986
2017         336189.213333  278423.859417  56674.010667         4034270.560
2018         348189.778833  288699.405250  58409.273083         4178277.346
2019         343987.934417  282592.673583  60284.330167         4127855.213
2020         333927.955667  268049.843583  64806.846667         4007135.468
2021         342961.679583  273510.393500  68439.640167         4115540.155
2022         334258.564750  251623.372500  81684.446500         1337034.259



source non-renewable   renewable
year
1973     1586332.048  277724.580
1974     1563404.290  306915.117
1975     1614164.606  306589.965
1976     1750106.572  290807.109
1977     1899785.559  227661.926
1978     1922596.429  286780.481
1979     1963202.030  287462.995
1980     2004912.033  284688.329
1981     2028074.683  269898.658
1982     1926834.690  317537.796
1983     1971698.447  341747.238
1984     2086515.809  332949.556
1985     2177967.088  295035.031
1986     2184962.816  305508.139
1987     2310165.044  265122.619
1988     2469326.087  238085.089
1989     2637983.658  325332.571
1990     2680481.337  353730.329
1991     2715828.021  353232.020
1992     2757481.075  322681.253
1993     2841032.216  352671.718
1994     2910572.413  333283.053
1995     2967310.553  382072.998
1996     3020746.756  419869.585
1997     3058964.082  429596.214
1998     3220767.297  395956.787
1999     3297923.909  392862.133
2000     3446371.417  350939.715
2001     3445831.063  278906.243
2002     3510230.264  334695.073
2003     3522382.651  346758.044
2004     3613326.437  342996.421
2005     3691508.824  351092.865
2006     3672513.765  379214.062
2007     3798662.462  345851.135
2008     3732939.768  374644.327
2009     3525306.142  413096.455
2010     3690329.615  421874.942
2011     3579071.746  506915.580
2012     3544355.494  489622.699
2013     3534984.130  517392.416
2014     3547738.940  532405.772
2015     3524423.633  539149.501
2016     3460161.775  602758.974
2017     3341086.313  680088.128
2018     3464392.863  700911.277
2019     3391112.083  723411.962
2020     3216598.123  777682.160
2021     3282124.722  821275.682
2022     1006493.490  326737.786

In [120]:
#for aggregation multiple value columns
df10.pivot_table(values=['Net_elec_generation','net_elec*2'],index="year", columns="source", fill_value=0, aggfunc=['mean','sum'])

                      mean                                              \
       Net_elec_generation                                  net_elec*2
source               Total  non-renewable     renewable          Total
year
1973         155338.052667  132194.337333  23143.715000  310676.105333
1974         155859.950250  130283.690833  25576.259750  311719.900500
1975         160062.880667  134513.717167  25549.163750  320125.761333
1976         170076.140083  145842.214333  24233.925750  340152.280167
1977         177287.290583  158315.463250  18971.827167  354574.581167
1978         184114.742583  160216.369083  23898.373417  368229.485167
1979         187555.418833  163600.169167  23955.249583  375110.837667
1980         190800.030250  167076.002750  23724.027417  381600.060500
1981         191497.778000  169006.223583  22491.554833  382995.556000
1982         187031.040500  160569.557500  26461.483000  374062.081000
1983         192787.140500  164308.203917  28478.936500  385574.281000
1984         201622.113917  173876.317417  27745.796333  403244.227833
1985         206083.510167  181497.257333  24586.252583  412167.020333
1986         207539.246083  182080.234667  25459.011583  415078.492167
1987         214607.305500  192513.753667  22093.551583  429214.611000
1988         225617.598083  205777.173917  19840.424083  451235.196167
1989         247262.173917  219831.971500  27111.047583  494524.347833
1990         253152.278083  223373.444750  29477.527417  506304.556167
1991         256149.907083  226319.001750  29436.001667  512299.814167
1992         256990.183833  229790.089583  26890.104417  513980.367667
1993         266432.591417  236752.684667  29389.309833  532865.182833
1994         270626.865667  242547.701083  27773.587750  541253.731333
1995         279457.280333  247275.879417  31839.416500  558914.560667
1996         287015.635083  251728.896333  34989.132083  574031.270167
1997         291014.356833  254913.673500  35799.684500  582028.713667
1998         301691.291417  268397.274750  32996.398917  603382.582833
1999         307900.817500  274826.992417  32738.511083  615801.635000
2000         316842.086833  287197.618083  29244.976250  633684.173667
2001         311386.970750  287152.588583  23242.186917  622773.941500
2002         321537.687167  292519.188667  27891.256083  643075.374333
2003         323598.767000  293531.887583  28896.503667  647197.534000
2004         330879.605333  301110.536417  28583.035083  661759.210667
2005         337951.895833  307625.735333  29257.738750  675903.791667
2006         338725.185667  306042.813750  31601.171833  677450.371333
2007         346395.393750  316555.205167  28820.927917  692790.787500
2008         343282.313250  311078.314000  31220.360583  686564.626500
2009         329194.243917  293775.511833  34424.704583  658388.487833
2010         343754.991583  307527.467917  35156.245167  687509.983167
2011         341678.410667  298255.978833  42242.965000  683356.821333
2012         337313.771500  295362.957833  40801.891583  674627.543000
2013         338830.339000  294582.010833  43116.034667  677660.678000
2014         341133.833917  295644.911667  44367.147667  682267.667833
2015         339800.078333  293701.969417  44929.125083  679600.156667
2016         339722.915500  288346.814583  50229.914500  679445.831000
2017         336189.213333  278423.859417  56674.010667  672378.426667
2018         348189.778833  288699.405250  58409.273083  696379.557667
2019         343987.934417  282592.673583  60284.330167  687975.868833
2020         333927.955667  268049.843583  64806.846667  667855.911333
2021         342961.679583  273510.393500  68439.640167  685923.359167
2022         334258.564750  251623.372500  81684.446500  668517.129500

                                                     sum                \
                                     Net_elec_generation
source  non-renewable      renewable               Total non-renewable
year
1973    264388.674667   46287.430000         1864056.632   1586332.048
1974    260567.381667   51152.519500         1870319.403   1563404.290
1975    269027.434333   51098.327500         1920754.568   1614164.606
1976    291684.428667   48467.851500         2040913.681   1750106.572
1977    316630.926500   37943.654333         2127447.487   1899785.559
1978    320432.738167   47796.746833         2209376.911   1922596.429
1979    327200.338333   47910.499167         2250665.026   1963202.030
1980    334152.005500   47448.054833         2289600.363   2004912.033
1981    338012.447167   44983.109667         2297973.336   2028074.683
1982    321139.115000   52922.966000         2244372.486   1926834.690
1983    328616.407833   56957.873000         2313445.686   1971698.447
1984    347752.634833   55491.592667         2419465.367   2086515.809
1985    362994.514667   49172.505167         2473002.122   2177967.088
1986    364160.469333   50918.023167         2490470.953   2184962.816
1987    385027.507333   44187.103167         2575287.666   2310165.044
1988    411554.347833   39680.848167         2707411.177   2469326.087
1989    439663.943000   54222.095167         2967146.087   2637983.658
1990    446746.889500   58955.054833         3037827.337   2680481.337
1991    452638.003500   58872.003333         3073798.885   2715828.021
1992    459580.179167   53780.208833         3083882.206   2757481.075
1993    473505.369333   58778.619667         3197191.097   2841032.216
1994    485095.402167   55547.175500         3247522.388   2910572.413
1995    494551.758833   63678.833000         3353487.364   2967310.553
1996    503457.792667   69978.264167         3444187.621   3020746.756
1997    509827.347000   71599.369000         3492172.282   3058964.082
1998    536794.549500   65992.797833         3620295.497   3220767.297
1999    549653.984833   65477.022167         3694809.810   3297923.909
2000    574395.236167   58489.952500         3802105.042   3446371.417
2001    574305.177167   46484.373833         3736643.649   3445831.063
2002    585038.377333   55782.512167         3858452.246   3510230.264
2003    587063.775167   57793.007333         3883185.204   3522382.651
2004    602221.072833   57166.070167         3970555.264   3613326.437
2005    615251.470667   58515.477500         4055422.750   3691508.824
2006    612085.627500   63202.343667         4064702.228   3672513.765
2007    633110.410333   57641.855833         4156744.725   3798662.462
2008    622156.628000   62440.721167         4119387.759   3732939.768
2009    587551.023667   68849.409167         3950330.927   3525306.142
2010    615054.935833   70312.490333         4125059.899   3690329.615
2011    596511.957667   84485.930000         4100140.928   3579071.746
2012    590725.915667   81603.783167         4047765.258   3544355.494
2013    589164.021667   86232.069333         4065964.068   3534984.130
2014    591289.823333   88734.295333         4093606.007   3547738.940
2015    587403.938833   89858.250167         4077600.940   3524423.633
2016    576693.629167  100459.829000         4076674.986   3460161.775
2017    556847.718833  113348.021333         4034270.560   3341086.313
2018    577398.810500  116818.546167         4178277.346   3464392.863
2019    565185.347167  120568.660333         4127855.213   3391112.083
2020    536099.687167  129613.693333         4007135.468   3216598.123
2021    547020.787000  136879.280333         4115540.155   3282124.722
2022    503246.745000  163368.893000         1337034.259   1006493.490


                     net_elec*2
source   renewable        Total non-renewable    renewable
year
1973    277724.580  3728113.264   3172664.096   555449.160
1974    306915.117  3740638.806   3126808.580   613830.234
1975    306589.965  3841509.136   3228329.212   613179.930
1976    290807.109  4081827.362   3500213.144   581614.218
1977    227661.926  4254894.974   3799571.118   455323.852
1978    286780.481  4418753.822   3845192.858   573560.962
1979    287462.995  4501330.052   3926404.060   574925.990
1980    284688.329  4579200.726   4009824.066   569376.658
1981    269898.658  4595946.672   4056149.366   539797.316
1982    317537.796  4488744.972   3853669.380   635075.592
1983    341747.238  4626891.372   3943396.894   683494.476
1984    332949.556  4838930.734   4173031.618   665899.112
1985    295035.031  4946004.244   4355934.176   590070.062
1986    305508.139  4980941.906   4369925.632   611016.278
1987    265122.619  5150575.332   4620330.088   530245.238
1988    238085.089  5414822.354   4938652.174   476170.178
1989    325332.571  5934292.174   5275967.316   650665.142
1990    353730.329  6075654.674   5360962.674   707460.658
1991    353232.020  6147597.770   5431656.042   706464.040
1992    322681.253  6167764.412   5514962.150   645362.506
1993    352671.718  6394382.194   5682064.432   705343.436
1994    333283.053  6495044.776   5821144.826   666566.106
1995    382072.998  6706974.728   5934621.106   764145.996
1996    419869.585  6888375.242   6041493.512   839739.170
1997    429596.214  6984344.564   6117928.164   859192.428
1998    395956.787  7240590.994   6441534.594   791913.574
1999    392862.133  7389619.620   6595847.818   785724.266
2000    350939.715  7604210.084   6892742.834   701879.430
2001    278906.243  7473287.298   6891662.126   557812.486
2002    334695.073  7716904.492   7020460.528   669390.146
2003    346758.044  7766370.408   7044765.302   693516.088
2004    342996.421  7941110.528   7226652.874   685992.842
2005    351092.865  8110845.500   7383017.648   702185.730
2006    379214.062  8129404.456   7345027.530   758428.124
2007    345851.135  8313489.450   7597324.924   691702.270
2008    374644.327  8238775.518   7465879.536   749288.654
2009    413096.455  7900661.854   7050612.284   826192.910
2010    421874.942  8250119.798   7380659.230   843749.884
2011    506915.580  8200281.856   7158143.492  1013831.160
2012    489622.699  8095530.516   7088710.988   979245.398
2013    517392.416  8131928.136   7069968.260  1034784.832
2014    532405.772  8187212.014   7095477.880  1064811.544
2015    539149.501  8155201.880   7048847.266  1078299.002
2016    602758.974  8153349.972   6920323.550  1205517.948
2017    680088.128  8068541.120   6682172.626  1360176.256
2018    700911.277  8356554.692   6928785.726  1401822.554
2019    723411.962  8255710.426   6782224.166  1446823.924
2020    777682.160  8014270.936   6433196.246  1555364.320
2021    821275.682  8231080.310   6564249.444  1642551.364
2022    326737.786  2674068.518   2012986.980   653475.572

In [121]:
# to subdivide over multiple columns we can pass in a list to the columns parameter.
df10.pivot_table(values=['Net_elec_generation'],index="year", columns=['month','source'], fill_value=0, aggfunc=['mean'])

                      mean                                                     \
       Net_elec_generation
month                   1                                    2
source               Total non-renewable  renewable       Total non-renewable
year
1973            160217.989    133804.986  26413.002  143538.699    120065.492
1974            157554.691    128161.539  29393.153  142748.458    115739.129
1975            164623.080    139095.914  25527.166  147349.000    122991.945
1976            178608.612    151915.484  26693.128  156965.799    131839.754
1977            196665.182    175312.508  21352.674  162949.088    147262.459
1978            198107.635    172412.866  25694.769  173745.731    150984.893
1979            209986.749    184344.992  25641.756  186587.309    164776.741
1980            200296.330    174338.443  25957.885  188961.379    166964.054
1981            206758.205    183587.666  23170.539  179859.910    158031.655
1982            209694.373    182095.949  27598.425  180545.573    153229.540
1983            195870.844    165838.416  30032.428  172725.190    144134.207
1984            216923.729    186347.843  30575.886  189810.043    161021.182
1985            228147.888    199406.722  28741.166  198488.497    171536.809
1986            217761.136    194969.546  22791.591  192582.016    168157.597
1987            223040.975    196320.233  26720.743  194280.625    171867.773
1988            238188.434    214831.396  23357.039  217183.084    196933.566
1989            246766.176    220606.033  25834.867  233782.777    210255.368
1990            255187.021    225023.305  29856.630  229499.204    198832.324
1991            269214.313    235717.517  33094.319  228290.131    200249.739
1992            267772.670    238028.981  29428.616  239514.031    214464.064
1993            271020.902    237847.450  32877.282  248015.328    220869.567
1994            289768.406    261105.937  28351.032  249172.290    222628.433
1995            279773.101    249596.508  29828.049  252307.149    222577.227
1996            296922.971    260522.062  36098.424  270685.247    234117.682
1997            300573.901    261382.181  38884.949  258131.029    221482.806
1998            295260.404    259185.442  35771.636  260589.918    224903.659
1999            315813.690    279363.486  36108.459  274820.273    240349.143
2000            327993.944    296612.661  30975.242  294169.282    264750.748
2001            332493.160    307213.135  24288.356  282940.198    259991.980
2002            319941.472    291309.797  27643.827  281825.708    255439.001
2003            341988.899    314624.984  26298.183  299248.775    273372.932
2004            346545.627    316333.141  29102.755  314279.910    286484.280
2005            343121.453    311496.142  30550.582  298500.316    270068.126
2006            328657.739    292247.379  35338.809  307333.430    274678.033
2007            353531.095    318368.441  34140.742  323230.395    296314.757
2008            362998.429    331770.962  30276.376  325105.597    296480.428
2009            354992.636    319328.101  34728.181  300887.398    271383.568
2010            360957.167    325319.829  34623.095  319734.727    287685.863
2011            362871.893    322186.722  39613.886  313126.607    272265.853
2012            339528.259    295726.817  42664.515  309389.420    271274.830
2013            348967.378    301988.004  45881.810  309728.080    268278.576
2014            377254.711    329325.331  46837.330  324348.436    285455.792
2015            360455.167    312627.198  46708.384  334475.546    289099.091
2016            352719.066    299584.205  51981.808  313685.401    260165.989
2017            344332.034    287117.988  56121.808  291049.672    235719.739
2018            373230.280    311842.583  60278.447  306894.214    248001.809
2019            359509.234    299431.657  58883.926  315026.484    259240.651
2020            341850.206    277929.403  62827.809  319550.114    252424.427
2021            350795.813    281855.100  67835.764  326223.389    265166.887
2022            378966.702    299155.908  78793.520  327766.846    250675.859

                                                                    ...  \
                                                                    ...
month                      3                                    4   ...
source  renewable       Total non-renewable  renewable       Total  ...
year                                                                ...
1973    23473.208  148158.370    122113.112  26045.257  139589.440  ...
1974    27009.328  150342.206    122289.124  28053.082  142311.633  ...
1975    24357.056  155760.211    127279.651  28480.561  146494.879  ...
1976    25126.046  164466.676    137265.638  27201.037  153467.392  ...
1977    15686.627  169437.171    149000.209  20436.963  157117.355  ...
1978    22760.838  173460.887    148299.269  25161.617  160012.982  ...
1979    21810.569  183154.004    156545.993  26608.010  170260.472  ...
1980    21997.325  187744.800    162731.171  25013.631  169016.585  ...
1981    21828.256  185833.882    164440.192  21393.690  172841.342  ...
1982    27316.033  187967.965    157472.699  30495.266  172876.502  ...
1983    28590.983  182768.722    151731.149  31037.573  170668.876  ...
1984    28788.859  200387.475    168953.424  31434.051  181381.139  ...
1985    26951.688  195250.388    169400.264  25850.124  185173.312  ...
1986    24424.420  197114.555    167385.050  29729.505  186370.454  ...
1987    22412.852  202129.944    177567.017  24562.927  189792.417  ...
1988    20249.517  214293.615    193458.206  20835.409  196297.111  ...
1989    23233.611  241946.410    213859.999  27761.137  222868.586  ...
1990    30389.514  244761.483    209625.621  34828.779  229769.727  ...
1991    27676.865  240561.216    208314.154  31844.584  227798.971  ...
1992    24755.222  247733.163    219418.699  27999.393  233405.563  ...
1993    26878.253  261247.551    229020.634  31930.748  234695.127  ...
1994    26262.557  257998.052    227500.163  30186.453  240636.581  ...
1995    29415.109  261342.562    227239.477  33754.542  244735.923  ...
1996    36284.595  275019.018    235150.821  39565.711  251612.875  ...
1997    36371.140  272258.227    231238.592  40712.864  258284.482  ...
1998    35412.287  286877.989    248620.528  37954.135  261229.604  ...
1999    34162.457  298144.718    260422.639  37380.334  280719.013  ...
2000    29038.689  301579.821    267973.718  33200.063  285577.749  ...
2001    22076.269  300706.544    274276.324  25499.065  278078.871  ...
2002    25405.267  302549.007    274862.064  26678.710  289848.252  ...
2003    24982.625  304317.263    273123.225  30143.422  285755.700  ...
2004    26711.277  308812.096    278398.265  29261.554  290559.914  ...
2005    27482.446  317458.276    286614.590  29807.860  289562.400  ...
2006    31689.183  318729.800    285214.683  32388.490  297858.078  ...
2007    25996.537  320471.243    286969.582  32483.761  303129.064  ...
2008    27686.518  324629.850    291831.243  31819.053  305865.031  ...
2009    28629.286  310602.964    275157.414  34462.001  289537.255  ...
2010    31139.712  312167.640    275950.901  35214.695  287800.227  ...
2011    39834.145  318709.941    270091.756  47435.791  302400.724  ...
2012    37042.736  309090.569    262122.439  45828.117  295228.216  ...
2013    40429.272  325398.834    281373.297  42882.331  299332.868  ...
2014    37951.800  331823.059    281044.086  49686.405  297630.588  ...
2015    44391.332  324191.894    275326.150  47814.907  294133.343  ...
2016    52478.325  304389.581    245209.767  58089.881  292893.550  ...
2017    54337.673  319335.755    252247.225  66027.418  295360.591  ...
2018    57898.125  321546.954    256812.309  63626.543  300756.440  ...
2019    54782.886  326657.208    261720.054  63860.077  296662.569  ...
2020    66154.405  309586.723    243075.050  65420.145  279583.265  ...
2021    60136.633  312284.622    234599.545  76624.292  292503.539  ...
2022    76200.267  325952.002    238240.679  86739.642  304348.709  ...

                                                                    \

month          9           10                                   11
source  renewable       Total non-renewable  renewable       Total
year
1973    17480.982  154197.466    135535.713  18661.753  148137.609
1974    21794.475  152195.832    131782.193  20413.638  150070.855
1975    21039.506  155187.742    131964.071  23223.672  153035.097
1976    20897.571  164009.445    142386.144  21623.302  169346.291
1977    16999.677  166645.282    148853.054  17792.227  167388.072
1978    21725.694  176013.116    156065.645  19947.472  176389.093
1979    19555.501  179953.363    159159.814  20793.550  177769.508
1980    19173.210  178761.034    160155.759  18605.275  178771.361
1981    18572.955  181557.590    162731.764  18825.826  175791.753
1982    20576.777  173172.248    152706.639  20465.608  173598.759
1983    22602.813  183136.711    161472.019  21664.692  183170.681
1984    21851.936  191142.430    169231.391  21911.040  190601.865
1985    19867.121  194995.217    173892.495  21102.722  192648.952
1986    22221.906  197959.776    175546.413  22413.363  196653.686
1987    19404.348  203214.924    184039.018  19175.907  200479.386
1988    17484.716  210813.885    194482.223  16331.662  209814.992
1989    24087.527  235669.018    209932.706  25411.036  234249.810
1990    23098.894  244372.250    219299.078  24766.087  231242.377
1991    25711.324  245378.242    220590.375  24385.390  241661.365
1992    23938.070  244993.925    220879.873  23798.983  244161.999
1993    24361.909  250552.792    225889.955  24366.667  252102.138
1994    22193.363  256528.490    231968.651  24248.402  251868.348
1995    26522.622  263978.440    233349.106  30280.790  261478.399
1996    28281.778  271446.494    241094.630  30049.380  269122.035
1997    29231.105  284970.629    252707.284  31956.575  271120.816
1998    27450.052  284445.547    258372.165  25770.058  267136.408
1999    27043.516  283934.839    258043.995  25549.099  271095.672
2000    23358.549  289451.903    265154.505  23891.357  284670.275
2001    20097.295  294733.613    273039.164  20669.729  278933.942
2002    22892.180  307059.462    282816.747  23049.535  296289.561
2003    24248.269  306740.934    281064.788  24361.051  297866.713
2004    26452.188  312450.223    286299.098  25010.362  302101.256
2005    23977.444  316397.924    290871.309  24577.195  306115.236
2006    24292.914  321567.091    295617.006  24842.875  309158.826
2007    22841.729  332615.416    308162.345  23397.767  314102.543
2008    24584.489  318547.343    292036.615  25620.068  310046.241
2009    27535.090  307040.341    274099.131  31974.019  296634.670
2010    30071.332  307920.691    275794.497  31036.353  306009.629
2011    33842.048  308698.504    271786.292  35736.646  304102.155
2012    32574.498  311650.774    275168.010  35347.292  305975.035
2013    35513.919  314925.463    275857.282  37883.538  314539.642
2014    35425.809  314521.999    273969.951  39430.053  317495.009
2015    38197.460  312111.680    270012.134  40895.098  300653.268
2016    42181.713  312945.164    265309.894  46527.055  297061.772
2017    47842.690  318669.649    265140.096  52498.813  308052.342
2018    49241.161  324931.943    272395.482  51451.998  322368.657
2019    55293.288  320351.885    261823.248  57428.569  315849.092
2020    54737.452  313531.271    252553.562  59910.591  301250.181
2021    63258.203  319638.396    253594.212  65065.088  315494.917
2022        0.000       0.000         0.000      0.000       0.000



month                                    12
source non-renewable  renewable       Total non-renewable  renewable
year
1973      127690.969  20446.638  153604.858    126930.696  26674.160
1974      128494.496  21576.359  160009.019    136440.854  23568.166
1975      128032.620  25002.478  169628.296    143049.880  26578.416
1976      148988.424  20357.866  184144.107    163325.960  20818.147
1977      146354.605  21033.467  184589.270    161173.615  23415.655
1978      155938.270  20450.822  192105.353    169443.053  22662.299
1979      154752.516  23016.992  188970.171    165519.786  23450.383
1980      158812.279  19959.082  195848.927    172817.157  23031.770
1981      156142.014  19649.741  195825.699    171254.326  24571.374
1982      149560.864  24037.895  184957.943    156547.362  28410.580
1983      157634.220  25536.461  212555.333    180099.581  32455.752
1984      167294.036  23307.830  200231.958    173270.419  26961.539
1985      168442.573  24206.379  219490.423    192782.863  26707.559
1986      172497.297  24156.389  213786.542    186564.333  27222.208
1987      182418.013  18061.373  220736.372    198400.343  22336.027
1988      190142.092  19672.899  232987.639    211858.403  21129.235
1989      207344.277  26590.750  274448.378    246910.116  27212.986
1990      205135.671  25809.528  255769.835    225015.727  30447.023
1991      216092.614  25179.259  254088.633    224433.030  29253.126
1992      217197.036  26660.055  267342.791    235500.134  31527.586
1993      226106.350  25709.171  272164.570    242948.098  28920.301
1994      225909.751  25657.207  269519.769    240614.603  28593.727
1995      229015.666  32125.433  285553.882    250079.204  35126.135
1996      238445.543  30383.764  284249.613    247496.575  36450.551
1997      241189.392  29634.547  296356.097    264514.017  31535.308
1998      241388.084  25454.783  297986.181    264964.336  32718.519
1999      243282.662  27482.290  295174.237    263937.110  30895.383
2000      258151.378  26125.954  319010.798    293260.890  25343.866
2001      257578.589  20314.962  305496.328    279683.053  24761.946
2002      269915.749  25313.337  324833.704    296332.514  27485.909
2003      271082.162  25550.490  331680.431    300084.083  30450.654
2004      274159.924  26763.898  341947.963    307986.742  32585.291
2005      278983.094  26120.574  348101.071    317788.307  29218.983
2006      280082.995  28023.545  336283.246    305765.627  29433.155
2007      289086.211  24049.086  346290.331    317857.901  27329.076
2008      283209.654  25961.225  343898.254    310227.768  32753.622
2009      262146.631  33488.244  350507.295    312086.301  37406.982
2010      270053.391  34876.844  362119.081    322989.762  37997.858
2011      264103.346  38812.204  335740.463    294078.368  40408.541
2012      268294.640  36540.606  334635.089    289649.978  43809.058
2013      273102.078  40294.260  353021.248    309546.886  42333.508
2014      271432.641  44901.356  337956.656    292268.620  44470.386
2015      252338.889  47117.376  324427.224    271712.178  51486.763
2016      248943.471  47020.477  345342.577    289845.735  54357.769
2017      255203.432  51769.453  350415.808    295433.078  53838.024
2018      267646.851  53647.218  342139.112    284659.383  56340.436
2019      259864.108  54903.006  338401.647    280051.591  57216.976
2020      234961.444  65222.203  344346.095    278834.032  64343.520
2021      244867.182  69649.783  339684.017    260132.691  78475.696
2022           0.000      0.000       0.000         0.000      0.000

[50 rows x 36 columns]

### 11. Exploding a list-like column

In [122]:
keys = ["panda1", "panda2", "panda3"]

values = [["eats", "shoots"], ["shoots", "leaves"], ["eats", "leaves"]]

df12 = pd.DataFrame({"keys": keys, "values": values})

In [123]:
df12

     keys            values
0  panda1    [eats, shoots]
1  panda2  [shoots, leaves]
2  panda3    [eats, leaves]

In [124]:
df1

          Total  month  year  tot/mean_tot
0    160217.989      1  1973      0.584437
1    143538.699      2  1973      0.523595
2    148158.370      3  1973      0.540446
3    139589.440      4  1973      0.509189
4    147395.124      5  1973      0.537662
..          ...    ...   ...           ...
587  339684.017     12  2021      1.239086
588  378966.702      1  2022      1.382380
589  327766.846      2  2022      1.195615
590  325952.002      3  2022      1.188995
591  304348.709      4  2022      1.110191

[592 rows x 4 columns]

In [125]:
df11= df1

In [126]:
df11

          Total  month  year  tot/mean_tot
0    160217.989      1  1973      0.584437
1    143538.699      2  1973      0.523595
2    148158.370      3  1973      0.540446
3    139589.440      4  1973      0.509189
4    147395.124      5  1973      0.537662
..          ...    ...   ...           ...
587  339684.017     12  2021      1.239086
588  378966.702      1  2022      1.382380
589  327766.846      2  2022      1.195615
590  325952.002      3  2022      1.188995
591  304348.709      4  2022      1.110191

[592 rows x 4 columns]

In [127]:
keys11 = list(set(df11['year']))  
# keys11

In [151]:
lst= list(df11['Total'])
lst[12:24]

[157554.691,
 142748.458,
 150342.206,
 142311.633,
 153812.873,
 156440.089,
 178247.304,
 174119.001,
 152467.442,
 152195.832,
 150070.855,
 160009.019]

In [168]:
List = []

# for i in range(len(lst)):
# #     while i<12:
# #         list1.append(lst[i])


# #     if (i%12!=0):
#         for j in range(12):
#             list1.append(lst[j])
# #     list2.append(list1)
# #     list1 =[]
# #     if (i%12!=0):
    
# #     else:
# #         list2.append(list1)
# #         list1.clear


# for i in range(12):
#     for j in range(12):
#         list1.append(lst[j])
    
# list2.append(list1)
# list1 =[]

for i in range(0,592-592%12,12):
    value.append(lst[i:i+12])
value.append(lst[i+12:])
        
# print()
# list2.append(list1)
# list1 =[]

In [169]:
df12 = pd.DataFrame({"keys": keys11, "values": value})

In [170]:
df12

    keys                                             values
0   1973  [160217.989, 143538.699, 148158.37, 139589.44,...
1   1974  [157554.691, 142748.458, 150342.206, 142311.63...
2   1975  [164623.08, 147349.0, 155760.211, 146494.879, ...
3   1976  [178608.612, 156965.799, 164466.676, 153467.39...
4   1977  [196665.182, 162949.088, 169437.171, 157117.35...
5   1978  [198107.635, 173745.731, 173460.887, 160012.98...
6   1979  [209986.749, 186587.309, 183154.004, 170260.47...
7   1980  [200296.33, 188961.379, 187744.8, 169016.585, ...
8   1981  [206758.205, 179859.91, 185833.882, 172841.342...
9   1982  [209694.373, 180545.573, 187967.965, 172876.50...
10  1983  [195870.844, 172725.19, 182768.722, 170668.876...
11  1984  [216923.729, 189810.043, 200387.475, 181381.13...
12  1985  [228147.888, 198488.497, 195250.388, 185173.31...
13  1986  [217761.136, 192582.016, 197114.555, 186370.45...
14  1987  [223040.975, 194280.625, 202129.944, 189792.41...
15  1988  [238188.434, 217183.084, 214293.615, 196297.11...
16  1989  [246766.176, 233782.777, 241946.41, 222868.586...
17  1990  [255187.021, 229499.204, 244761.483, 229769.72...
18  1991  [269214.313, 228290.131, 240561.216, 227798.97...
19  1992  [267772.67, 239514.031, 247733.163, 233405.563...
20  1993  [271020.902, 248015.328, 261247.551, 234695.12...
21  1994  [289768.406, 249172.29, 257998.052, 240636.581...
22  1995  [279773.101, 252307.149, 261342.562, 244735.92...
23  1996  [296922.971, 270685.247, 275019.018, 251612.87...
24  1997  [300573.901, 258131.029, 272258.227, 258284.48...
25  1998  [295260.404, 260589.918, 286877.989, 261229.60...
26  1999  [315813.69, 274820.273, 298144.718, 280719.013...
27  2000  [327993.944, 294169.282, 301579.821, 285577.74...
28  2001  [332493.16, 282940.198, 300706.544, 278078.871...
29  2002  [319941.472, 281825.708, 302549.007, 289848.25...
30  2003  [341988.899, 299248.775, 304317.263, 285755.7,...
31  2004  [346545.627, 314279.91, 308812.096, 290559.914...
32  2005  [343121.453, 298500.316, 317458.276, 289562.4,...
33  2006  [328657.739, 307333.43, 318729.8, 297858.078, ...
34  2007  [353531.095, 323230.395, 320471.243, 303129.06...
35  2008  [362998.429, 325105.597, 324629.85, 305865.031...
36  2009  [354992.636, 300887.398, 310602.964, 289537.25...
37  2010  [360957.167, 319734.727, 312167.64, 287800.227...
38  2011  [362871.893, 313126.607, 318709.941, 302400.72...
39  2012  [339528.259, 309389.42, 309090.569, 295228.216...
40  2013  [348967.378, 309728.08, 325398.834, 299332.868...
41  2014  [377254.711, 324348.436, 331823.059, 297630.58...
42  2015  [360455.167, 334475.546, 324191.894, 294133.34...
43  2016  [352719.066, 313685.401, 304389.581, 292893.55...
44  2017  [344332.034, 291049.672, 319335.755, 295360.59...
45  2018  [373230.28, 306894.214, 321546.954, 300756.44,...
46  2019  [359509.234, 315026.484, 326657.208, 296662.56...
47  2020  [341850.206, 319550.114, 309586.723, 279583.26...
48  2021  [350795.813, 326223.389, 312284.622, 292503.53...
49  2022   [378966.702, 327766.846, 325952.002, 304348.709]

In [165]:
df12["values"].explode()

0     160217.989
0     143538.699
0      148158.37
0      139589.44
0     147395.124
         ...
48    339684.017
49    378966.702
49    327766.846
49    325952.002
49    304348.709
Name: values, Length: 592, dtype: object

In [274]:
df12["values"].explode()

0     160217.989
0     143538.699
0      148158.37
0      139589.44
0     147395.124
         ...
48    339684.017
49    378966.702
49    327766.846
49    325952.002
49    304348.709
Name: values, Length: 592, dtype: object

In [ ]:
# data=zip(df[df.columns[0]],df[df.columns[1]],df[df.columns[2]],df[df.columns[4]],df[df.columns[5]])